// src/ui/components/form-fields/FormField.vue
<template>
  <div
    :class="containerClass || CSS_CLASSES.FORM_GROUP"
    :data-field-name="fieldPath || field.field"
  >
    <TextField
      v-if="field.type === 'text'"
      :field-id="fieldId"
      :model-value="modelValue"
      :label="field.label"
      :placeholder="field.placeholder"
      :required="required"
      :error="error"
      input-type="text"
      :show-label="showLabel"
      @update:model-value="handleUpdate"
    />
    <TextField
      v-else-if="field.type === 'url'"
      :field-id="fieldId"
      :model-value="modelValue"
      :label="field.label"
      :placeholder="field.placeholder"
      :required="required"
      :error="error"
      input-type="url"
      :show-label="showLabel"
      @update:model-value="handleUpdate"
    />
    <TextField
      v-else-if="field.type === 'email'"
      :field-id="fieldId"
      :model-value="modelValue"
      :label="field.label"
      :placeholder="field.placeholder"
      :required="required"
      :error="error"
      input-type="email"
      :show-label="showLabel"
      @update:model-value="handleUpdate"
    />
    <TextareaField
      v-else-if="field.type === 'textarea'"
      :field-id="fieldId"
      :model-value="modelValue"
      :label="field.label"
      :placeholder="field.placeholder"
      :required="required"
      :error="error"
      :show-label="showLabel"
      @update:model-value="handleUpdate"
    />
    <NumberField
      v-else-if="field.type === 'number'"
      :field-id="fieldId"
      :model-value="modelValue"
      :label="field.label"
      :placeholder="field.placeholder"
      :required="required"
      :error="error"
      :show-label="showLabel"
      @update:model-value="handleUpdate"
    />
    <ColorField
      v-else-if="field.type === 'color'"
      :field-id="fieldId"
      :model-value="modelValue"
      :label="field.label"
      :required="required"
      :error="error"
      :show-label="showLabel"
      @update:model-value="handleUpdate"
    />
    <SelectField
      v-else-if="field.type === 'select'"
      :field-id="fieldId"
      :model-value="modelValue"
      :label="field.label"
      :placeholder="field.placeholder"
      :required="required"
      :error="error"
      :options="field.options || []"
      :show-label="showLabel"
      @update:model-value="handleUpdate"
    />
    <CheckboxField
      v-else-if="field.type === 'checkbox'"
      :field-id="fieldId"
      :model-value="modelValue"
      :label="field.label"
      :required="required"
      :error="error"
      @update:model-value="handleUpdate"
    />
    <RadioField
      v-else-if="field.type === 'radio'"
      :field-id="fieldId"
      :model-value="modelValue"
      :label="field.label"
      :required="required"
      :error="error"
      :options="field.options || []"
      @update:model-value="handleUpdate"
    />
    <ImageUploadField
      v-else-if="field.type === 'image'"
      :model-value="modelValue"
      :label="showLabel ? field.label : ''"
      :required="required"
      :placeholder="field.placeholder"
      :error="error"
      :image-upload-config="field.imageUploadConfig"
      @update:model-value="handleUpdate"
    />
    <slot v-else :field="field" :field-id="fieldId" :model-value="modelValue" :error="error" />
    <div v-if="error" :class="CSS_CLASSES.FORM_ERRORS">
      <span :class="CSS_CLASSES.ERROR">{{ error }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { IFormFieldConfig } from '../../../core/types/form';
import { CSS_CLASSES } from '../../../utils/constants';
import ImageUploadField from '../ImageUploadField.vue';
import CheckboxField from './CheckboxField.vue';
import ColorField from './ColorField.vue';
import NumberField from './NumberField.vue';
import RadioField from './RadioField.vue';
import SelectField from './SelectField.vue';
import TextareaField from './TextareaField.vue';
import TextField from './TextField.vue';

interface Props {
  field: IFormFieldConfig;
  fieldId: string;
  modelValue?: any;
  required?: boolean;
  error?: string;
  showLabel?: boolean;
  containerClass?: string;
  fieldPath?: string;
}

withDefaults(defineProps<Props>(), {
  modelValue: undefined,
  required: false,
  error: '',
  showLabel: true,
  containerClass: '',
  fieldPath: undefined,
});

const emit = defineEmits<{
  'update:modelValue': [value: any];
}>();

const handleUpdate = (value: any) => {
  emit('update:modelValue', value);
};
</script>

// src/react/components/form-fields/FormField.tsx
import type { ReactNode } from 'react';

import type { IFormFieldConfig } from '../../../core/types/form';
import { CSS_CLASSES } from '../../../utils/constants';
import { ImageUploadField } from '../ImageUploadField';
import { CheckboxField } from './CheckboxField';
import { ColorField } from './ColorField';
import { NumberField } from './NumberField';
import { RadioField } from './RadioField';
import { SelectField } from './SelectField';
import { TextareaField } from './TextareaField';
import { TextField } from './TextField';

export interface IFormFieldProps {
  field: IFormFieldConfig;
  fieldId: string;
  modelValue?: unknown;
  required?: boolean;
  error?: string;
  showLabel?: boolean;
  containerClass?: string;
  fieldPath?: string;
  onChange: (value: unknown) => void;
  children?: ReactNode;
}

export function FormField({
  field,
  fieldId,
  modelValue,
  required = false,
  error = '',
  showLabel = true,
  containerClass,
  fieldPath,
  onChange,
  children,
}: IFormFieldProps) {
  const renderField = () => {
    switch (field.type) {
      case 'text':
        return (
          <TextField
            fieldId={fieldId}
            modelValue={String(modelValue ?? '')}
            label={field.label}
            placeholder={field.placeholder}
            required={required}
            error={error}
            inputType="text"
            showLabel={showLabel}
            onChange={onChange}
          />
        );
      case 'url':
        return (
          <TextField
            fieldId={fieldId}
            modelValue={String(modelValue ?? '')}
            label={field.label}
            placeholder={field.placeholder}
            required={required}
            error={error}
            inputType="url"
            showLabel={showLabel}
            onChange={onChange}
          />
        );
      case 'email':
        return (
          <TextField
            fieldId={fieldId}
            modelValue={String(modelValue ?? '')}
            label={field.label}
            placeholder={field.placeholder}
            required={required}
            error={error}
            inputType="email"
            showLabel={showLabel}
            onChange={onChange}
          />
        );
      case 'textarea':
        return (
          <TextareaField
            fieldId={fieldId}
            modelValue={String(modelValue ?? '')}
            label={field.label}
            placeholder={field.placeholder}
            required={required}
            error={error}
            showLabel={showLabel}
            onChange={onChange}
          />
        );
      case 'number':
        return (
          <NumberField
            fieldId={fieldId}
            modelValue={
              modelValue === undefined || modelValue === null || modelValue === ''
                ? undefined
                : Number(modelValue)
            }
            label={field.label}
            placeholder={field.placeholder}
            required={required}
            error={error}
            showLabel={showLabel}
            onChange={onChange}
          />
        );
      case 'color':
        return (
          <ColorField
            fieldId={fieldId}
            modelValue={String(modelValue ?? '#333333')}
            label={field.label}
            required={required}
            error={error}
            showLabel={showLabel}
            onChange={onChange}
          />
        );
      case 'select':
        return (
          <SelectField
            fieldId={fieldId}
            modelValue={modelValue as string | number | undefined}
            label={field.label}
            placeholder={field.placeholder}
            required={required}
            error={error}
            options={field.options || []}
            showLabel={showLabel}
            onChange={onChange}
          />
        );
      case 'checkbox':
        return (
          <CheckboxField
            fieldId={fieldId}
            modelValue={Boolean(modelValue)}
            label={field.label}
            required={required}
            error={error}
            onChange={onChange}
          />
        );
      case 'radio':
        return (
          <RadioField
            fieldId={fieldId}
            modelValue={modelValue as string | number | undefined}
            label={field.label}
            required={required}
            error={error}
            options={field.options || []}
            onChange={onChange}
          />
        );
      case 'image':
        return (
          <ImageUploadField
            modelValue={modelValue}
            label={showLabel ? field.label : ''}
            required={required}
            placeholder={field.placeholder}
            error={error}
            imageUploadConfig={field.imageUploadConfig}
            fieldNamePath={fieldPath || field.field}
            onChange={onChange}
          />
        );
      default:
        return children;
    }
  };

  return (
    <div
      className={containerClass || CSS_CLASSES.FORM_GROUP}
      data-field-name={fieldPath || field.field}
    >
      {renderField()}
      {error ? (
        <div className={CSS_CLASSES.FORM_ERRORS}>
          <span className={CSS_CLASSES.ERROR}>{error}</span>
        </div>
      ) : null}
    </div>
  );
}
