// src/ui/components/form-fields/SelectField.vue
<template>
  <label v-if="showLabel" :for="fieldId" class="bb-form-label">
    {{ label }}
    <span v-if="required" class="bb-required">*</span>
  </label>
  <CustomDropdown
    :model-value="modelValue"
    :options="dropdownOptions"
    :placeholder="placeholder || 'Выберите...'"
    :clearable="isClearable"
    :invalid="showError"
    @update:model-value="handleUpdate"
  />
  <div v-if="showError && error" class="bb-form-errors">
    <span :class="CSS_CLASSES.ERROR">{{ error }}</span>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

import { CSS_CLASSES } from '../../../utils/constants';
import CustomDropdown from '../CustomDropdown.vue';

interface IOption {
  value: string | number;
  label: string;
  disabled?: boolean;
}

interface Props {
  fieldId: string;
  modelValue?: string | number;
  label?: string;
  placeholder?: string;
  required?: boolean;
  error?: string;
  options?: Option[];
  showLabel?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '',
  label: '',
  placeholder: '',
  required: false,
  error: '',
  options: () => [] as IOption[],
  showLabel: true,
});

const emit = defineEmits<{
  'update:modelValue': [value: string | number];
}>();

type TDropdownValue = string | number | (string | number)[] | null;

const dropdownOptions = computed(() => {
  return props.options.map(option => ({
    value: option.value,
    label: option.label,
    disabled: option.disabled ?? false,
  }));
});

const showError = computed(() => !!props.error);

const isClearable = computed(() => !props.required);

const handleUpdate = (value: TDropdownValue) => {
  if (Array.isArray(value)) {
    const [first] = value;
    emit('update:modelValue', (first ?? '') as string | number);
    return;
  }

  if (value === null || value === undefined) {
    emit('update:modelValue', '' as string);
    return;
  }

  emit('update:modelValue', value as string | number);
};
</script>

// src/react/components/form-fields/SelectField.tsx
import { useMemo } from 'react';

import { CSS_CLASSES } from '../../../utils/constants';
import { CustomDropdown, type TDropdownValue } from '../CustomDropdown';

export interface ISelectOption {
  value: string | number;
  label: string;
  disabled?: boolean;
}

export interface ISelectFieldProps {
  fieldId: string;
  modelValue?: string | number;
  label?: string;
  placeholder?: string;
  required?: boolean;
  error?: string;
  options?: ISelectOption[];
  showLabel?: boolean;
  onChange: (value: string | number) => void;
}

export function SelectField({
  fieldId,
  modelValue = '',
  label = '',
  placeholder = '',
  required = false,
  error = '',
  options = [],
  showLabel = true,
  onChange,
}: ISelectFieldProps) {
  const dropdownOptions = useMemo(
    () =>
      options.map(option => ({
        value: option.value,
        label: option.label,
        disabled: option.disabled ?? false,
      })),
    [options]
  );

  const showError = Boolean(error);
  const isClearable = !required;

  const handleUpdate = (value: TDropdownValue) => {
    if (Array.isArray(value)) {
      const [first] = value;
      onChange((first ?? '') as string | number);
      return;
    }

    if (value === null || value === undefined) {
      onChange('' as string);
      return;
    }

    onChange(value as string | number);
  };

  return (
    <>
      {showLabel ? (
        <label htmlFor={fieldId} className={CSS_CLASSES.FORM_LABEL}>
          {label}
          {required ? <span className={CSS_CLASSES.REQUIRED}>*</span> : null}
        </label>
      ) : null}
      <CustomDropdown
        modelValue={modelValue}
        options={dropdownOptions}
        placeholder={placeholder || 'Выберите...'}
        clearable={isClearable}
        invalid={showError}
        onChange={handleUpdate}
      />
    </>
  );
}
