// examples/react19/src/components/blocks/ButtonBlock.tsx
import { useState } from 'react'

interface IButtonBlockProps {
  text: string
  backgroundColor?: string
  color?: string
  borderRadius?: number
  padding?: string
}

export default function ButtonBlock({
  text,
  backgroundColor = '#007bff',
  color = '#ffffff',
  borderRadius = 4,
  padding = '8px 16px',
}: IButtonBlockProps) {
  const [isLoading, setIsLoading] = useState(false)

  return (
    <div className="button-block" style={{ textAlign: 'center', margin: '20px 0' }}>
      <div className="container">
        <button
          type="button"
          className="custom-button"
          disabled={isLoading}
          style={{
            backgroundColor,
            color,
            borderRadius: `${borderRadius}px`,
            padding,
            border: 'none',
            cursor: 'pointer',
            fontSize: '16px',
            fontWeight: 500,
          }}
          onClick={() => {
            setIsLoading(true)
            setTimeout(() => setIsLoading(false), 1000)
          }}
        >
          {isLoading ? 'Загрузка...' : text}
        </button>
      </div>
    </div>
  )
}

// examples/vue3-theme/src/components/ButtonBlock.vue
<template>
  <div class="button-block">
    <div class="container">
      <button class="custom-button" :style="buttonStyle" type="button">
        {{ text }}
      </button>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  text: {
    type: String,
    required: true,
  },
  backgroundColor: {
    type: String,
    default: '#007bff',
  },
  color: {
    type: String,
    default: '#ffffff',
  },
  borderRadius: {
    type: Number,
    default: 4,
  },
  padding: {
    type: String,
    default: '8px 16px',
  },
})

const buttonStyle = computed(() => ({
  backgroundColor: props.backgroundColor,
  color: props.color,
  borderRadius: `${props.borderRadius}px`,
  padding: props.padding,
  border: 'none',
  cursor: 'pointer',
  fontSize: '16px',
}))
</script>

<style scoped>
.button-block {
  padding: 16px 0;
  text-align: center;
}
</style>
