// examples/react/src/components/blocks/LinkBlock.tsx
interface ILinkBlockProps {
  text?: string
  url?: string
  linkTarget?: '_self' | '_blank'
  hasBackground?: boolean
  backgroundColor?: string
  padding?: string
}

function scrollToBlockAnchor(url: string) {
  if (!url.startsWith('#')) {
    return false
  }

  const blockId = url.slice(1)
  const target = document.querySelector(`[data-block-id="${blockId}"]`)
  target?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  return true
}

export default function LinkBlock({
  text = 'Ссылка',
  url = '#',
  linkTarget = '_self',
  hasBackground = false,
  backgroundColor = '#f0f0f0',
  padding = '12px 24px',
}: ILinkBlockProps) {
  const blockStyle: React.CSSProperties = {}
  if (hasBackground) {
    blockStyle.backgroundColor = backgroundColor
    blockStyle.padding = padding
    blockStyle.borderRadius = '8px'
  }

  return (
    <div className="link-block" style={{ textAlign: 'center', margin: '20px 0', ...blockStyle }}>
      <div className="container">
        <a
          href={url}
          target={linkTarget}
          rel={linkTarget === '_blank' ? 'noopener noreferrer' : undefined}
          className="link-block__link"
          style={{
            color: 'var(--bb-color-primary, #0066cc)',
            textDecoration: 'none',
            fontSize: '16px',
            fontWeight: 500,
          }}
          onClick={event => {
            if (scrollToBlockAnchor(url)) {
              event.preventDefault()
            }
          }}
        >
          {text}
        </a>
      </div>
    </div>
  )
}

// examples/nuxt4/app/components/blocks/LinkBlock.vue
<template>
  <div class="link-block" :style="blockStyle">
    <div class="container">
      <a
        :href="url"
        :target="linkTarget"
        :rel="linkRel"
        class="link-block__link"
        @click="handleClick"
      >
        {{ text }}
      </a>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  text: {
    type: String,
    default: 'Ссылка'
  },
  url: {
    type: String,
    default: '#'
  },
  linkTarget: {
    type: String,
    default: '_self'
  },
  hasBackground: {
    type: Boolean,
    default: false
  },
  backgroundColor: {
    type: String,
    default: '#f0f0f0'
  },
  padding: {
    type: String,
    default: '12px 24px'
  }
})

const linkTarget = computed(() => props.linkTarget)
const linkRel = computed(() => {
  return props.linkTarget === '_blank' ? 'noopener noreferrer' : ''
})

const blockStyle = computed(() => {
  const styles = {}
  if (props.hasBackground) {
    styles.backgroundColor = props.backgroundColor
    styles.padding = props.padding
    styles.borderRadius = '8px'
  }
  return styles
})

const handleClick = (event) => {
  if (!props.url.startsWith('#')) {
    return
  }

  event.preventDefault()
  const blockId = props.url.slice(1)
  const target = document.querySelector(`[data-block-id="${blockId}"]`)
  target?.scrollIntoView({ behavior: 'smooth', block: 'start' })
}
</script>

<style scoped>
.link-block {
  text-align: center;
  margin: 20px 0;
}

.link-block__link {
  color: var(--bb-color-primary);
  text-decoration: none;
  font-size: 16px;
  font-weight: 500;
  transition: color 0.2s ease;
}

.link-block__link:hover {
  color: var(--bb-color-primary-dark);
  text-decoration: underline;
}

.link-block__link:visited {
  color: var(--bb-color-primary);
}
</style>
