// src/react/components/form-fields/NumberField.tsx
import { CSS_CLASSES } from '../../../utils/constants';

export interface INumberFieldProps {
  fieldId: string;
  modelValue?: number;
  label?: string;
  placeholder?: string;
  required?: boolean;
  error?: string;
  showLabel?: boolean;
  onChange: (value: number | undefined) => void;
}

export function NumberField({
  fieldId,
  modelValue,
  label = '',
  placeholder = '',
  required = false,
  error = '',
  showLabel = true,
  onChange,
}: INumberFieldProps) {
  const inputClass = error
    ? `${CSS_CLASSES.FORM_CONTROL} ${CSS_CLASSES.ERROR}`
    : CSS_CLASSES.FORM_CONTROL;

  return (
    <>
      {showLabel ? (
        <label htmlFor={fieldId} className={CSS_CLASSES.FORM_LABEL}>
          {label}
          {required ? <span className={CSS_CLASSES.REQUIRED}>*</span> : null}
        </label>
      ) : null}
      <input
        id={fieldId}
        type="number"
        value={modelValue === undefined || modelValue === null ? '' : modelValue}
        placeholder={placeholder}
        className={inputClass}
        onChange={event =>
          onChange(event.target.value === '' ? undefined : Number(event.target.value))
        }
      />
    </>
  );
}

// src/ui/components/form-fields/NumberField.vue
<template>
  <label v-if="showLabel" :for="fieldId" class="bb-form-label">
    {{ label }}
    <span v-if="required" class="bb-required">*</span>
  </label>
  <input
    :id="fieldId"
    :value="modelValue"
    type="number"
    :placeholder="placeholder"
    :class="inputClass"
    @input="handleInput"
  />
  <div v-if="showError && error" class="bb-form-errors">
    <span :class="CSS_CLASSES.ERROR">{{ error }}</span>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

import { CSS_CLASSES } from '../../../utils/constants';

interface Props {
  fieldId: string;
  modelValue?: number;
  label?: string;
  placeholder?: string;
  required?: boolean;
  error?: string;
  showLabel?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: undefined,
  label: '',
  placeholder: '',
  required: false,
  error: '',
  showLabel: true,
});

const emit = defineEmits<{
  'update:modelValue': [value: number];
}>();

const inputClass = computed(() => {
  const baseClass = CSS_CLASSES.FORM_CONTROL;
  return props.error ? `${baseClass} ${CSS_CLASSES.ERROR}` : baseClass;
});

const showError = computed(() => !!props.error);

const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement;
  const value = target.value === '' ? undefined : Number(target.value);
  emit('update:modelValue', value);
};
</script>
