// src/react/components/CustomDropdown.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent,
  type ReactNode,
  type UIEvent,
} from 'react';
import { createPortal } from 'react-dom';

import { CSS_CLASSES } from '../../utils/constants';
import { useUiStrings } from '../context/uiStringsContext';
import { Icon } from './icons/Icon';

export interface IDropdownOption {
  value: string | number;
  label: string;
  disabled?: boolean;
  meta?: Record<string, unknown>;
  group?: string;
}

export type TDropdownValue = string | number | (string | number)[] | null;

export type TScrollSnapshot = { top: number; height: number };

export interface IDropdownTriggerState {
  isOpen: boolean;
  hasValue: boolean;
  selectedOptions: IDropdownOption[];
  multiple: boolean;
  disabled: boolean;
}

export interface IDropdownTriggerActions {
  open: () => Promise<void>;
  close: () => void;
  toggle: () => void;
  clear: () => void;
}

export interface IDropdownPanelState {
  isOpen: boolean;
  selectedOptions: IDropdownOption[];
  highlightedIndex: number;
}

export interface IDropdownPanelActions {
  open: () => Promise<void>;
  close: () => void;
  toggle: () => void;
  updatePosition: () => void;
}

export interface ICustomDropdownRef {
  open: () => Promise<void>;
  close: () => void;
  toggle: () => void;
  updatePosition: () => void;
  saveScrollPosition: () => number;
  restoreScrollPosition: (scrollTop: number) => void;
  saveScrollSnapshot: () => TScrollSnapshot;
  restoreScrollFromSnapshot: (snapshot: TScrollSnapshot | null | undefined) => void;
  isOpen: boolean;
}

export interface ICustomDropdownProps {
  modelValue: TDropdownValue;
  onChange: (value: TDropdownValue) => void;
  options?: IDropdownOption[];
  placeholder?: string;
  multiple?: boolean;
  disabled?: boolean;
  clearable?: boolean;
  loading?: boolean;
  loadingText?: string;
  emptyText?: string;
  errorText?: string | null;
  invalid?: boolean;
  teleportTo?: string;
  maxHeight?: number;
  chipDisplayLimit?: number;
  className?: string;
  renderTrigger?: (props: {
    state: IDropdownTriggerState;
    actions: IDropdownTriggerActions;
  }) => ReactNode;
  renderPanel?: (props: {
    state: IDropdownPanelState;
    actions: IDropdownPanelActions;
  }) => ReactNode;
  children?: ReactNode;
  beforeOptions?: ReactNode;
  afterOptions?: ReactNode;
  renderOption?: (option: IDropdownOption, selected: boolean) => ReactNode;
  renderLoading?: ReactNode;
  renderError?: ReactNode;
  renderEmpty?: ReactNode;
  onOpen?: () => void;
  onClose?: () => void;
  onScrollBottom?: () => void;
  onClear?: () => void;
}

type TScrollAncestor = HTMLElement | Window;

function nextTick(callback: () => void): void {
  queueMicrotask(() => {
    requestAnimationFrame(callback);
  });
}

function resolvePortalTarget(teleportTo: string): HTMLElement {
  if (teleportTo === 'body') {
    return document.body;
  }
  const element = document.querySelector(teleportTo);
  return (element as HTMLElement | null) ?? document.body;
}

function isElementScrollable(element: HTMLElement): boolean {
  const style = window.getComputedStyle(element);
  const overflowY = style.overflowY;
  const overflow = style.overflow;
  const isScrollable =
    overflowY === 'scroll' || overflowY === 'auto' || overflow === 'scroll' || overflow === 'auto';

  if (!isScrollable) {
    return false;
  }

  return element.scrollHeight > element.clientHeight;
}

function findScrollableAncestors(element: HTMLElement | null): HTMLElement[] {
  const ancestors: HTMLElement[] = [];
  if (!element) {
    return ancestors;
  }

  let current = element.parentElement;
  while (current && current !== document.body) {
    if (isElementScrollable(current)) {
      ancestors.push(current);
    }
    current = current.parentElement;
  }

  return ancestors;
}

export const CustomDropdown = forwardRef<ICustomDropdownRef, ICustomDropdownProps>(
  function CustomDropdown(
    {
      modelValue,
      onChange,
      options = [],
      placeholder,
      multiple = false,
      disabled = false,
      clearable = false,
      loading = false,
      loadingText,
      emptyText,
      errorText = null,
      invalid = false,
      teleportTo = 'body',
      maxHeight = 320,
      chipDisplayLimit = 3,
      className,
      renderTrigger,
      renderPanel,
      children,
      beforeOptions,
      afterOptions,
      renderOption,
      renderLoading,
      renderError,
      renderEmpty,
      onOpen,
      onClose,
      onScrollBottom,
      onClear,
    },
    ref
  ) {
    const uiStrings = useUiStrings();
    const resolvedPlaceholder = placeholder ?? uiStrings.dropdownPlaceholder;
    const resolvedLoadingText = loadingText ?? uiStrings.dropdownLoading;
    const resolvedEmptyText = emptyText ?? uiStrings.dropdownEmpty;

    const rootRef = useRef<HTMLDivElement>(null);
    const triggerRef = useRef<HTMLDivElement>(null);
    const panelRef = useRef<HTMLDivElement>(null);
    const contentRef = useRef<HTMLDivElement>(null);
    const lastScrollSnapshotRef = useRef<TScrollSnapshot | null>(null);
    const scrollListenersRef = useRef<Array<{ ancestor: TScrollAncestor; handler: () => void }>>(
      []
    );

    const [isOpen, setIsOpen] = useState(false);
    const [highlightedIndex, setHighlightedIndex] = useState(-1);
    const [panelStyle, setPanelStyle] = useState<CSSProperties>({});
    const [portalTarget, setPortalTarget] = useState<HTMLElement | null>(null);

    const selectedOptions = useMemo<IDropdownOption[]>(() => {
      if (multiple) {
        const value = Array.isArray(modelValue) ? modelValue : [];
        return options.filter(option => value.includes(option.value));
      }

      if (modelValue === null || modelValue === undefined || modelValue === '') {
        return [];
      }

      const option = options.find(item => item.value === modelValue);
      return option ? [option] : [];
    }, [modelValue, multiple, options]);

    const displayValue = selectedOptions.length > 0 ? (selectedOptions[0]?.label ?? '') : '';

    const multipleSummary = useMemo(() => {
      if (!multiple || selectedOptions.length === 0) {
        return '';
      }

      const limit = 3;
      const visible = selectedOptions.slice(0, limit);
      const rest = selectedOptions.length - limit;
      const labels = visible.map(option => option.label);

      if (rest > 0) {
        labels.push(`+${rest}`);
      }

      return labels.join(', ');
    }, [multiple, selectedOptions]);

    const hasValue = useMemo(() => {
      if (multiple) {
        return Array.isArray(modelValue) && modelValue.length > 0;
      }
      return modelValue !== null && modelValue !== undefined && modelValue !== '';
    }, [modelValue, multiple]);

    const showClear = clearable && hasValue && !disabled;

    const contentStyle = useMemo(
      () => ({
        maxHeight: `${maxHeight}px`,
      }),
      [maxHeight]
    );

    const cleanupScrollableAncestors = useCallback(() => {
      scrollListenersRef.current.forEach(({ ancestor, handler }) => {
        ancestor.removeEventListener('scroll', handler);
      });
      scrollListenersRef.current = [];
    }, []);

    const updatePosition = useCallback(() => {
      if (!isOpen || !triggerRef.current || !panelRef.current) {
        return;
      }

      const rect = triggerRef.current.getBoundingClientRect();
      const viewportMargin = 8;
      const spaceBelow = Math.max(0, window.innerHeight - rect.bottom - viewportMargin);
      const spaceAbove = Math.max(0, rect.top - viewportMargin);
      const shouldShowAbove = spaceBelow < spaceAbove;
      const availableSpace = shouldShowAbove ? spaceAbove : spaceBelow;
      const effectiveMaxHeight = Math.min(
        maxHeight,
        Math.max(160, availableSpace > 0 ? availableSpace : maxHeight)
      );

      const dropdownHeight = Math.min(panelRef.current.scrollHeight, effectiveMaxHeight);

      let top = shouldShowAbove
        ? rect.top - dropdownHeight - viewportMargin
        : rect.bottom + viewportMargin;
      const viewportOffsetTop = window.visualViewport?.offsetTop ?? 0;
      top += viewportOffsetTop;

      const maxTop = window.innerHeight - dropdownHeight - viewportMargin;
      const minTop = viewportMargin;
      top = Math.max(minTop, Math.min(maxTop, top));

      setPanelStyle({
        left: `${rect.left}px`,
        width: `${rect.width}px`,
        top: `${top}px`,
        maxHeight: `${effectiveMaxHeight}px`,
      });
    }, [isOpen, maxHeight]);

    const handleWindowChange = useCallback(() => {
      if (isOpen) {
        updatePosition();
      }
    }, [isOpen, updatePosition]);

    const attachScrollableAncestors = useCallback(() => {
      cleanupScrollableAncestors();
      const triggerElement = triggerRef.current;
      if (!triggerElement) {
        return;
      }

      const ancestors = findScrollableAncestors(triggerElement);
      const scrollableAncestors: TScrollAncestor[] = [window, ...ancestors];

      scrollableAncestors.forEach(ancestor => {
        const handler = handleWindowChange;
        ancestor.addEventListener('scroll', handler, { passive: true });
        scrollListenersRef.current.push({ ancestor, handler });
      });
    }, [cleanupScrollableAncestors, handleWindowChange]);

    const getNextIndex = useCallback(
      (direction: 1 | -1, currentIndex: number) => {
        if (options.length === 0) {
          return -1;
        }

        let nextIndex = currentIndex;

        for (let i = 0; i < options.length; i += 1) {
          nextIndex = (nextIndex + direction + options.length) % options.length;
          const option = options[nextIndex];
          if (!option?.disabled) {
            return nextIndex;
          }
        }

        return currentIndex;
      },
      [options]
    );

    const highlight = useCallback(
      (index: number) => {
        if (options[index]?.disabled) {
          return;
        }
        setHighlightedIndex(index);
      },
      [options]
    );

    const highlightInitial = useCallback(() => {
      if (multiple) {
        setHighlightedIndex(getNextIndex(1, -1));
        return;
      }

      const selectedIndex = options.findIndex(option => option.value === modelValue);

      if (selectedIndex >= 0 && !options[selectedIndex]?.disabled) {
        setHighlightedIndex(selectedIndex);
        return;
      }

      setHighlightedIndex(getNextIndex(1, -1));
    }, [getNextIndex, modelValue, multiple, options]);

    const isOpenRef = useRef(isOpen);
    isOpenRef.current = isOpen;

    const close = useCallback(() => {
      if (!isOpenRef.current) {
        return;
      }
      setIsOpen(false);
      setHighlightedIndex(-1);
      cleanupScrollableAncestors();
      onClose?.();
      lastScrollSnapshotRef.current = null;
    }, [cleanupScrollableAncestors, onClose]);

    const open = useCallback(async () => {
      if (disabled) {
        return;
      }

      if (isOpen) {
        await new Promise<void>(resolve => nextTick(resolve));
        updatePosition();
        return;
      }

      lastScrollSnapshotRef.current = null;
      setIsOpen(true);
      onOpen?.();

      await new Promise<void>(resolve => nextTick(resolve));
      updatePosition();
      highlightInitial();
    }, [disabled, highlightInitial, isOpen, onOpen, updatePosition]);

    const toggle = useCallback(() => {
      if (isOpen) {
        close();
      } else {
        void open();
      }
    }, [close, isOpen, open]);

    const saveScrollPosition = useCallback((): number => {
      if (!contentRef.current) {
        return 0;
      }
      return contentRef.current.scrollTop;
    }, []);

    const restoreScrollPosition = useCallback((scrollTop: number) => {
      if (!contentRef.current || scrollTop <= 0) {
        return;
      }
      nextTick(() => {
        if (contentRef.current) {
          contentRef.current.scrollTop = scrollTop;
        }
      });
    }, []);

    const saveScrollSnapshot = useCallback((): TScrollSnapshot => {
      const top = contentRef.current?.scrollTop ?? 0;
      const height = contentRef.current?.scrollHeight ?? 0;
      return { top, height };
    }, []);

    const restoreScrollFromSnapshot = useCallback((snapshot: TScrollSnapshot | null | undefined) => {
      if (!contentRef.current || !snapshot) {
        return;
      }
      nextTick(() => {
        if (!contentRef.current) {
          return;
        }
        const prevTop = snapshot.top;
        const prevHeight = snapshot.height;
        const newHeight = contentRef.current.scrollHeight;
        const client = contentRef.current.clientHeight;
        if (prevHeight === 0) {
          contentRef.current.scrollTop = 0;
          return;
        }
        const delta = Math.max(0, newHeight - prevHeight);
        const distanceFromBottomPrev = prevHeight - (prevTop + client);
        const wasNearBottom = distanceFromBottomPrev >= 0 && distanceFromBottomPrev <= 48;
        const targetTop = wasNearBottom ? prevTop + delta : prevTop;
        contentRef.current.scrollTop = Math.max(0, targetTop);
      });
    }, []);

    const isOptionSelected = useCallback(
      (value: string | number) => {
        if (multiple) {
          const currentValue = Array.isArray(modelValue) ? modelValue : [];
          return currentValue.includes(value);
        }

        return modelValue === value;
      },
      [modelValue, multiple]
    );

    const onOptionClick = useCallback(
      (option: IDropdownOption) => {
        if (option.disabled) {
          return;
        }

        if (multiple) {
          const currentValue = Array.isArray(modelValue) ? [...modelValue] : [];

          if (currentValue.includes(option.value)) {
            onChange(currentValue.filter(value => value !== option.value));
          } else {
            onChange([...currentValue, option.value]);
          }
        } else {
          onChange(option.value);
          close();
        }
      },
      [close, modelValue, multiple, onChange]
    );

    const removeOption = useCallback(
      (value: string | number) => {
        if (!multiple || disabled) {
          return;
        }

        const currentValue = Array.isArray(modelValue) ? modelValue : [];
        onChange(currentValue.filter(item => item !== value));
      },
      [disabled, modelValue, multiple, onChange]
    );

    const clearSelection = useCallback(() => {
      if (!hasValue || disabled) {
        return;
      }

      if (multiple) {
        onChange([]);
      } else {
        onChange(null);
      }

      onClear?.();
    }, [disabled, hasValue, multiple, onChange, onClear]);

    const scrollHighlightedIntoView = useCallback((index: number) => {
      if (!contentRef.current || index < 0) {
        return;
      }

      const optionElements = contentRef.current.querySelectorAll<HTMLElement>(
        `.${CSS_CLASSES.BB_DROPDOWN_OPTION}`
      );
      const element = optionElements[index];

      if (!element) {
        return;
      }

      const { offsetTop, offsetHeight } = element;
      const { scrollTop, clientHeight } = contentRef.current;

      const isAbove = offsetTop < scrollTop;
      const isBelow = offsetTop + offsetHeight > scrollTop + clientHeight;

      if (isAbove) {
        contentRef.current.scrollTo({ top: offsetTop, behavior: 'smooth' });
      } else if (isBelow) {
        contentRef.current.scrollTo({
          top: offsetTop - clientHeight + offsetHeight,
          behavior: 'smooth',
        });
      }
    }, []);

    const handleTriggerKeydown = useCallback(
      (event: KeyboardEvent<HTMLDivElement>) => {
        if (disabled) {
          return;
        }

        switch (event.key) {
          case 'ArrowDown': {
            event.preventDefault();
            if (!isOpen) {
              void open();
            } else {
              const next = getNextIndex(1, highlightedIndex);
              setHighlightedIndex(next);
              nextTick(() => scrollHighlightedIntoView(next));
            }
            break;
          }
          case 'ArrowUp': {
            event.preventDefault();
            if (isOpen) {
              const next = getNextIndex(-1, highlightedIndex);
              setHighlightedIndex(next);
              nextTick(() => scrollHighlightedIntoView(next));
            } else {
              void open();
            }
            break;
          }
          case 'Enter': {
            event.preventDefault();
            if (!isOpen) {
              void open();
            } else if (highlightedIndex >= 0) {
              const option = options[highlightedIndex];
              if (option) {
                onOptionClick(option);
              }
            }
            break;
          }
          case 'Escape': {
            if (isOpen) {
              event.preventDefault();
              close();
            }
            break;
          }
          case 'Tab': {
            close();
            break;
          }
          default:
            break;
        }
      },
      [
        close,
        disabled,
        getNextIndex,
        highlightedIndex,
        isOpen,
        onOptionClick,
        open,
        options,
        scrollHighlightedIntoView,
      ]
    );

    const handleContentScroll = useCallback(
      (event: UIEvent<HTMLDivElement>) => {
        const element = event.currentTarget;
        const threshold = 32;

        if (element.scrollHeight - element.scrollTop - element.clientHeight <= threshold) {
          onScrollBottom?.();
        }
      },
      [onScrollBottom]
    );

    const handleOutsideClick = useCallback(
      (event: globalThis.MouseEvent) => {
        const target = event.target as HTMLElement;
        const containsTarget =
          rootRef.current?.contains(target) || panelRef.current?.contains(target) || false;

        if (!containsTarget) {
          close();
        }
      },
      [close]
    );

    useImperativeHandle(
      ref,
      () => ({
        open,
        close,
        toggle,
        updatePosition,
        saveScrollPosition,
        restoreScrollPosition,
        saveScrollSnapshot,
        restoreScrollFromSnapshot,
        isOpen,
      }),
      [
        close,
        isOpen,
        open,
        restoreScrollFromSnapshot,
        restoreScrollPosition,
        saveScrollPosition,
        saveScrollSnapshot,
        toggle,
        updatePosition,
      ]
    );

    useEffect(() => {
      setPortalTarget(resolvePortalTarget(teleportTo));
    }, [teleportTo]);

    useEffect(() => {
      if (!multiple) {
        highlightInitial();
      }
    }, [modelValue, multiple]);

    useEffect(() => {
      if (!isOpen) {
        return;
      }

      if (loading) {
        lastScrollSnapshotRef.current = saveScrollSnapshot();
        return;
      }

      nextTick(() => {
        restoreScrollFromSnapshot(lastScrollSnapshotRef.current);
        nextTick(updatePosition);
      });
    }, [isOpen, loading, restoreScrollFromSnapshot, saveScrollSnapshot, updatePosition]);

    useEffect(() => {
      if (!isOpen) {
        document.removeEventListener('mousedown', handleOutsideClick, true);
        window.removeEventListener('resize', handleWindowChange);
        cleanupScrollableAncestors();
        return;
      }

      document.addEventListener('mousedown', handleOutsideClick, true);
      window.addEventListener('resize', handleWindowChange);
      nextTick(() => {
        attachScrollableAncestors();
        updatePosition();
      });

      return () => {
        document.removeEventListener('mousedown', handleOutsideClick, true);
        window.removeEventListener('resize', handleWindowChange);
        cleanupScrollableAncestors();
      };
    }, [
      attachScrollableAncestors,
      cleanupScrollableAncestors,
      handleOutsideClick,
      handleWindowChange,
      isOpen,
      updatePosition,
    ]);

    useEffect(() => {
      return () => {
        document.removeEventListener('mousedown', handleOutsideClick, true);
        window.removeEventListener('resize', handleWindowChange);
        cleanupScrollableAncestors();
      };
    }, [cleanupScrollableAncestors, handleOutsideClick, handleWindowChange]);

    const triggerSlotProps = useMemo(
      () => ({
        state: {
          isOpen,
          hasValue,
          selectedOptions,
          multiple,
          disabled,
        },
        actions: {
          open,
          close,
          toggle,
          clear: clearSelection,
        },
      }),
      [clearSelection, close, disabled, hasValue, isOpen, multiple, open, selectedOptions, toggle]
    );

    const panelSlotProps = useMemo(
      () => ({
        state: {
          isOpen,
          selectedOptions,
          highlightedIndex,
        },
        actions: {
          open,
          close,
          toggle,
          updatePosition,
        },
      }),
      [close, highlightedIndex, isOpen, open, selectedOptions, toggle, updatePosition]
    );

    const defaultTrigger = (
      <>
        <div className={CSS_CLASSES.BB_DROPDOWN_VALUE}>
          {multiple ? (
            multipleSummary ? (
              <span className={CSS_CLASSES.BB_DROPDOWN_SINGLE}>{multipleSummary}</span>
            ) : (
              <span className={CSS_CLASSES.BB_DROPDOWN_PLACEHOLDER}>{resolvedPlaceholder}</span>
            )
          ) : displayValue ? (
            <span className={CSS_CLASSES.BB_DROPDOWN_SINGLE}>{displayValue}</span>
          ) : (
            <span className={CSS_CLASSES.BB_DROPDOWN_PLACEHOLDER}>{resolvedPlaceholder}</span>
          )}
        </div>

        {showClear ? (
          <button
            type="button"
            className={CSS_CLASSES.BB_DROPDOWN_CLEAR}
            onClick={event => {
              event.stopPropagation();
              clearSelection();
            }}
          >
            <Icon name="close" width={12} height={12} />
          </button>
        ) : null}

        <span
          className={[
            CSS_CLASSES.BB_DROPDOWN_ARROW,
            isOpen ? CSS_CLASSES.BB_DROPDOWN_ARROW_OPEN : '',
          ]
            .filter(Boolean)
            .join(' ')}
        >
          <Icon name="chevronDown" width={12} height={12} />
        </span>
      </>
    );

    const defaultPanelContent = (
      <div
        ref={contentRef}
        className={CSS_CLASSES.BB_DROPDOWN_CONTENT}
        style={contentStyle}
        onScroll={handleContentScroll}
      >
        {beforeOptions}

        {errorText && !loading && options.length === 0 ? (
          <div
            className={`${CSS_CLASSES.BB_DROPDOWN_MESSAGE} ${CSS_CLASSES.BB_DROPDOWN_MESSAGE_ERROR}`}
          >
            {renderError ?? errorText}
          </div>
        ) : null}

        {options.length > 0 ? (
          <ul className={CSS_CLASSES.BB_DROPDOWN_LIST}>
            {options.map((option, index) => {
              const selected = isOptionSelected(option.value);
              const showGroupHeader =
                Boolean(option.group) &&
                (index === 0 || options[index - 1]?.group !== option.group);
              return (
                <li key={`${option.group || 'opt'}-${String(option.value)}`} role="none">
                  {showGroupHeader ? (
                    <div className={CSS_CLASSES.BB_DROPDOWN_GROUP}>{option.group}</div>
                  ) : null}
                  <div
                    className={[
                      CSS_CLASSES.BB_DROPDOWN_OPTION,
                      selected ? CSS_CLASSES.BB_DROPDOWN_OPTION_SELECTED : '',
                      option.disabled ? CSS_CLASSES.BB_DROPDOWN_OPTION_DISABLED : '',
                      highlightedIndex === index ? CSS_CLASSES.BB_DROPDOWN_OPTION_ACTIVE : '',
                    ]
                      .filter(Boolean)
                      .join(' ')}
                    role="option"
                    aria-selected={selected}
                    onClick={() => onOptionClick(option)}
                    onMouseEnter={() => highlight(index)}
                  >
                    {renderOption ? (
                      renderOption(option, selected)
                    ) : (
                      <>
                        <span className={CSS_CLASSES.BB_DROPDOWN_OPTION_LABEL}>{option.label}</span>
                        {selected ? (
                          <span className={CSS_CLASSES.BB_DROPDOWN_OPTION_CHECK}>
                            <Icon name="check" width={14} height={14} />
                          </span>
                        ) : null}
                      </>
                    )}
                  </div>
                </li>
              );
            })}
          </ul>
        ) : loading ? (
          <div className={CSS_CLASSES.BB_DROPDOWN_MESSAGE}>
            {renderLoading ?? resolvedLoadingText}
          </div>
        ) : errorText ? null : (
          <div className={CSS_CLASSES.BB_DROPDOWN_MESSAGE}>{renderEmpty ?? resolvedEmptyText}</div>
        )}

        {loading && options.length > 0 ? (
          <div className={CSS_CLASSES.BB_DROPDOWN_MESSAGE}>
            {renderLoading ?? resolvedLoadingText}
          </div>
        ) : null}

        {afterOptions}
      </div>
    );

    const panelNode =
      isOpen && portalTarget
        ? createPortal(
            <div
              ref={panelRef}
              className={CSS_CLASSES.BB_DROPDOWN_PANEL}
              style={panelStyle}
              role="listbox"
              aria-multiselectable={multiple}
              onMouseDown={event => event.preventDefault()}
            >
              {renderPanel ? renderPanel(panelSlotProps) : children ?? defaultPanelContent}
            </div>,
            portalTarget
          )
        : null;

    const rootClassName = [
      CSS_CLASSES.BB_DROPDOWN,
      isOpen ? CSS_CLASSES.BB_DROPDOWN_OPEN : '',
      disabled ? CSS_CLASSES.BB_DROPDOWN_DISABLED : '',
      invalid ? CSS_CLASSES.BB_DROPDOWN_INVALID : '',
      multiple ? CSS_CLASSES.BB_DROPDOWN_MULTIPLE : '',
      className ?? '',
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={rootRef} className={rootClassName}>
        <div
          ref={triggerRef}
          className={CSS_CLASSES.BB_DROPDOWN_CONTROL}
          role="combobox"
          aria-expanded={isOpen}
          aria-disabled={disabled}
          tabIndex={disabled ? -1 : 0}
          onClick={() => toggle()}
          onKeyDown={handleTriggerKeydown}
        >
          {renderTrigger ? renderTrigger(triggerSlotProps) : defaultTrigger}
        </div>
        {multiple && selectedOptions.length > 0 && !renderTrigger ? (
          <div className={CSS_CLASSES.BB_API_SELECT_SELECTED}>
            {selectedOptions.map(option => (
              <div key={option.value} className={CSS_CLASSES.BB_API_SELECT_TAG}>
                <span className={CSS_CLASSES.BB_API_SELECT_TAG_NAME}>{option.label}</span>
                <span
                  className={CSS_CLASSES.BB_API_SELECT_TAG_REMOVE}
                  onClick={event => {
                    event.stopPropagation();
                    removeOption(option.value);
                  }}
                >
                  <Icon name="close" width={12} height={12} />
                </span>
              </div>
            ))}
          </div>
        ) : null}
        {panelNode}
      </div>
    );
  }
);

// src/vue/components/CustomDropdown.vue
<template>
  <div
    ref="rootRef"
    :class="[
      CSS_CLASSES.BB_DROPDOWN,
      {
        [CSS_CLASSES.BB_DROPDOWN_OPEN]: isOpen,
        [CSS_CLASSES.BB_DROPDOWN_DISABLED]: disabled,
        [CSS_CLASSES.BB_DROPDOWN_INVALID]: invalid,
        [CSS_CLASSES.BB_DROPDOWN_MULTIPLE]: multiple,
      },
    ]"
  >
    <div
      ref="triggerRef"
      :class="CSS_CLASSES.BB_DROPDOWN_CONTROL"
      role="combobox"
      :aria-expanded="isOpen"
      :aria-disabled="disabled"
      :tabindex="disabled ? -1 : 0"
      @click="handleTriggerClick"
      @keydown="handleTriggerKeydown"
    >
      <slot name="trigger" v-bind="triggerSlotProps">
        <div :class="CSS_CLASSES.BB_DROPDOWN_VALUE">
          <template v-if="multiple">
            <span v-if="multipleSummary" :class="CSS_CLASSES.BB_DROPDOWN_SINGLE">
              {{ multipleSummary }}
            </span>
            <span v-else :class="CSS_CLASSES.BB_DROPDOWN_PLACEHOLDER">
              {{ resolvedPlaceholder }}
            </span>
          </template>

          <template v-else>
            <span v-if="displayValue" :class="CSS_CLASSES.BB_DROPDOWN_SINGLE">
              {{ displayValue }}
            </span>
            <span v-else :class="CSS_CLASSES.BB_DROPDOWN_PLACEHOLDER">
              {{ resolvedPlaceholder }}
            </span>
          </template>
        </div>

        <button
          v-if="showClear"
          type="button"
          :class="CSS_CLASSES.BB_DROPDOWN_CLEAR"
          @click.stop="clearSelection"
        >
          <Icon name="close" :width="12" :height="12" />
        </button>

        <span
          :class="[
            CSS_CLASSES.BB_DROPDOWN_ARROW,
            { [CSS_CLASSES.BB_DROPDOWN_ARROW_OPEN]: isOpen },
          ]"
        >
          <Icon name="chevronDown" :width="12" :height="12" />
        </span>
      </slot>
    </div>

    <div
      v-if="multiple && selectedOptions.length > 0 && !hasCustomTrigger"
      :class="CSS_CLASSES.BB_API_SELECT_SELECTED"
    >
      <div
        v-for="option in selectedOptions"
        :key="`bb-dropdown-tag-${option.value}`"
        :class="CSS_CLASSES.BB_API_SELECT_TAG"
      >
        <span :class="CSS_CLASSES.BB_API_SELECT_TAG_NAME">{{ option.label }}</span>
        <span
          :class="CSS_CLASSES.BB_API_SELECT_TAG_REMOVE"
          @click.stop="removeOption(option.value)"
        >
          <Icon name="close" :width="12" :height="12" />
        </span>
      </div>
    </div>

    <Teleport :to="teleportTo">
      <Transition :name="CSS_CLASSES.BB_DROPDOWN_FADE">
        <div
          v-if="isOpen"
          ref="panelRef"
          :class="CSS_CLASSES.BB_DROPDOWN_PANEL"
          :style="panelStyle"
          role="listbox"
          :aria-multiselectable="multiple"
          @mousedown.prevent
        >
          <slot name="panel" v-bind="panelSlotProps">
            <div
              ref="contentRef"
              :class="CSS_CLASSES.BB_DROPDOWN_CONTENT"
              :style="contentStyle"
              @scroll.passive="handleContentScroll"
            >
              <slot name="before-options" />

              <div v-if="loading" :class="CSS_CLASSES.BB_DROPDOWN_MESSAGE">
                <slot name="loading">
                  {{ resolvedLoadingText }}
                </slot>
              </div>

              <div
                v-else-if="errorText"
                :class="[CSS_CLASSES.BB_DROPDOWN_MESSAGE, CSS_CLASSES.BB_DROPDOWN_MESSAGE_ERROR]"
              >
                <slot name="error">
                  {{ errorText }}
                </slot>
              </div>

              <template v-else-if="options.length > 0">
                <ul :class="CSS_CLASSES.BB_DROPDOWN_LIST">
                  <li
                    v-for="(option, index) in options"
                    :key="`${option.group || 'opt'}-${option.value}`"
                    role="none"
                  >
                    <div
                      v-if="option.group && (index === 0 || options[index - 1]?.group !== option.group)"
                      :class="CSS_CLASSES.BB_DROPDOWN_GROUP"
                    >
                      {{ option.group }}
                    </div>
                    <div
                      :class="[
                        CSS_CLASSES.BB_DROPDOWN_OPTION,
                        {
                          [CSS_CLASSES.BB_DROPDOWN_OPTION_SELECTED]: isOptionSelected(option.value),
                          [CSS_CLASSES.BB_DROPDOWN_OPTION_DISABLED]: option.disabled,
                          [CSS_CLASSES.BB_DROPDOWN_OPTION_ACTIVE]: highlightedIndex === index,
                        },
                      ]"
                      role="option"
                      :aria-selected="isOptionSelected(option.value)"
                      @click="onOptionClick(option)"
                      @mouseenter="highlight(index)"
                    >
                      <slot name="option" :option="option" :selected="isOptionSelected(option.value)">
                        <span :class="CSS_CLASSES.BB_DROPDOWN_OPTION_LABEL">{{ option.label }}</span>
                        <span v-if="isOptionSelected(option.value)" :class="CSS_CLASSES.BB_DROPDOWN_OPTION_CHECK">
                          <Icon name="check" :width="14" :height="14" />
                        </span>
                      </slot>
                    </div>
                  </li>
                </ul>
              </template>

              <div v-else :class="CSS_CLASSES.BB_DROPDOWN_MESSAGE">
                <slot name="empty">
                  {{ resolvedEmptyText }}
                </slot>
              </div>

              <slot name="after-options" />
            </div>
          </slot>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { CSS_CLASSES } from '../../utils/constants';
import Icon from '../../shared/icons/Icon.vue';
import { useUiStrings } from '../composables/useUiStrings';
import { computed, nextTick, onBeforeUnmount, onMounted, ref, useSlots, watch } from 'vue';

const uiStrings = useUiStrings();

interface IDropdownOption {
  value: string | number;
  label: string;
  disabled?: boolean;
  meta?: Record<string, unknown>;
  group?: string;
}

export type TDropdownValue = string | number | (string | number)[] | null;

const props = withDefaults(
  defineProps<{
    modelValue: TDropdownValue;
    options?: IDropdownOption[];
    placeholder?: string;
    multiple?: boolean;
    disabled?: boolean;
    clearable?: boolean;
    loading?: boolean;
    loadingText?: string;
    emptyText?: string;
    errorText?: string | null;
    invalid?: boolean;
    teleportTo?: string;
    maxHeight?: number;
    closeOnSelect?: boolean;
    chipDisplayLimit?: number;
  }>(),
  {
    options: () => [],
    placeholder: undefined,
    multiple: false,
    disabled: false,
    clearable: false,
    loading: false,
    loadingText: undefined,
    emptyText: undefined,
    errorText: null,
    invalid: false,
    teleportTo: 'body',
    maxHeight: 320,
    chipDisplayLimit: 3,
  }
);

const emit = defineEmits<{
  (e: 'update:modelValue', value: TDropdownValue): void;
  (e: 'open'): void;
  (e: 'close'): void;
  (e: 'scroll-bottom'): void;
  (e: 'clear'): void;
}>();

const slots = useSlots();
const hasCustomTrigger = computed(() => Boolean(slots.trigger));

const rootRef = ref<HTMLElement | null>(null);
const triggerRef = ref<HTMLElement | null>(null);
const panelRef = ref<HTMLElement | null>(null);
const contentRef = ref<HTMLElement | null>(null);

const isOpen = ref(false);
const highlightedIndex = ref(-1);
const panelStyle = ref<Record<string, string>>({});

const options = computed(() => props.options ?? []);

const resolvedPlaceholder = computed(() => props.placeholder ?? uiStrings.value.dropdownPlaceholder);
const resolvedLoadingText = computed(() => props.loadingText ?? uiStrings.value.dropdownLoading);
const resolvedEmptyText = computed(() => props.emptyText ?? uiStrings.value.dropdownEmpty);

type TScrollAncestor = HTMLElement | (Window & typeof globalThis);
let scrollableAncestors: TScrollAncestor[] = [];
let scrollListeners: Array<{ ancestor: TScrollAncestor; handler: () => void }> = [];

const selectedOptions = computed<IDropdownOption[]>(() => {
  if (props.multiple) {
    const value = Array.isArray(props.modelValue) ? props.modelValue : [];
    return options.value.filter(option => value.includes(option.value));
  }

  if (props.modelValue === null || props.modelValue === undefined || props.modelValue === '') {
    return [];
  }

  const option = options.value.find(item => item.value === props.modelValue);
  return option ? [option] : [];
});

const displayValue = computed(() => {
  if (selectedOptions.value.length === 0) {
    return '';
  }
  return selectedOptions.value[0]?.label ?? '';
});

const multipleSummary = computed(() => {
  if (!props.multiple || selectedOptions.value.length === 0) {
    return '';
  }

  const limit = 3;
  const visible = selectedOptions.value.slice(0, limit);
  const rest = selectedOptions.value.length - limit;
  const labels = visible.map(option => option.label);

  if (rest > 0) {
    labels.push(`+${rest}`);
  }

  return labels.join(', ');
});

const hasValue = computed(() => {
  if (props.multiple) {
    return Array.isArray(props.modelValue) && props.modelValue.length > 0;
  }
  return props.modelValue !== null && props.modelValue !== undefined && props.modelValue !== '';
});

const showClear = computed(() => props.clearable && hasValue.value && !props.disabled);

const contentStyle = computed(() => {
  const maxPanelHeight = props.maxHeight ?? 320;
  return {
    maxHeight: `${maxPanelHeight}px`,
  };
});

const open = async () => {
  if (props.disabled || isOpen.value) {
    if (isOpen.value) {
      await nextTick();
      updatePosition();
    }
    return;
  }

  // Сбрасываем прошлый snapshot перед открытием,
  // чтобы не восстановить позицию от предыдущего сеанса
  lastScrollSnapshot.value = null;

  isOpen.value = true;
  emit('open');

  await nextTick();
  updatePosition();
  highlightInitial();
};

const close = () => {
  if (!isOpen.value) {
    return;
  }

  isOpen.value = false;
  highlightedIndex.value = -1;
  cleanupScrollableAncestors();
  emit('close');

  // После закрытия сбрасываем snapshot
  lastScrollSnapshot.value = null;
};

const toggle = () => {
  if (isOpen.value) {
    close();
  } else {
    void open();
  }
};

const saveScrollPosition = (): number => {
  if (!contentRef.value) {
    return 0;
  }
  return contentRef.value.scrollTop;
};

const restoreScrollPosition = (scrollTop: number) => {
  if (!contentRef.value || scrollTop <= 0) {
    return;
  }
  nextTick(() => {
    if (contentRef.value) {
      contentRef.value.scrollTop = scrollTop;
    }
  });
};

type TScrollSnapshot = { top: number; height: number };

const saveScrollSnapshot = (): TScrollSnapshot => {
  const top = contentRef.value?.scrollTop ?? 0;
  const height = contentRef.value?.scrollHeight ?? 0;
  return { top, height };
};

const restoreScrollFromSnapshot = (snapshot: TScrollSnapshot | null | undefined) => {
  if (!contentRef.value || !snapshot) {
    return;
  }
  nextTick(() => {
    if (!contentRef.value) {
      return;
    }
    const prevTop = snapshot.top;
    const prevHeight = snapshot.height;
    const newHeight = contentRef.value.scrollHeight;
    const client = contentRef.value.clientHeight;
    // Если это первый рендер (нечего восстанавливать), остаёмся в начале
    if (prevHeight === 0) {
      contentRef.value.scrollTop = 0;
      return;
    }
    const delta = Math.max(0, newHeight - prevHeight);
    // Считаем расстояние до низа в прошлом состоянии
    const distanceFromBottomPrev = prevHeight - (prevTop + client);
    // Считаем "близко к низу" только если расстояние неотрицательное и мало
    const wasNearBottom = distanceFromBottomPrev >= 0 && distanceFromBottomPrev <= 48;
    const targetTop = wasNearBottom ? prevTop + delta : prevTop;
    contentRef.value.scrollTop = Math.max(0, targetTop);
  });
};

const lastScrollSnapshot = ref<TScrollSnapshot | null>(null);

watch(
  () => props.loading,
  isLoading => {
    if (!isOpen.value) {
      return;
    }
    if (isLoading) {
      lastScrollSnapshot.value = saveScrollSnapshot();
    } else {
      // Восстанавливаем позицию после обновления списка
      nextTick(() => {
        restoreScrollFromSnapshot(lastScrollSnapshot.value);
        // Обновляем позицию панели (мог изменииться размер)
        nextTick(() => updatePosition());
      });
    }
  }
);

const updatePosition = () => {
  if (!isOpen.value || !triggerRef.value || !panelRef.value) {
    return;
  }

  const rect = triggerRef.value.getBoundingClientRect();
  const viewportMargin = 8;
  const spaceBelow = Math.max(0, window.innerHeight - rect.bottom - viewportMargin);
  const spaceAbove = Math.max(0, rect.top - viewportMargin);
  const shouldShowAbove = spaceBelow < spaceAbove;
  const availableSpace = shouldShowAbove ? spaceAbove : spaceBelow;
  const maxPanelHeight = props.maxHeight ?? 320;
  const effectiveMaxHeight = Math.min(
    maxPanelHeight,
    Math.max(160, availableSpace > 0 ? availableSpace : maxPanelHeight)
  );

  const dropdownHeight = Math.min(panelRef.value.scrollHeight, effectiveMaxHeight);

  let top = shouldShowAbove
    ? rect.top - dropdownHeight - viewportMargin
    : rect.bottom + viewportMargin;
  const viewportOffsetTop = window.visualViewport?.offsetTop ?? 0;
  top += viewportOffsetTop;

  const maxTop = window.innerHeight - dropdownHeight - viewportMargin;
  const minTop = viewportMargin;
  top = Math.max(minTop, Math.min(maxTop, top));

  panelStyle.value = {
    left: `${rect.left}px`,
    width: `${rect.width}px`,
    top: `${top}px`,
    maxHeight: `${effectiveMaxHeight}px`,
  };
};

const getNextIndex = (direction: 1 | -1) => {
  if (options.value.length === 0) {
    return -1;
  }

  let nextIndex = highlightedIndex.value;

  for (let i = 0; i < options.value.length; i += 1) {
    nextIndex = (nextIndex + direction + options.value.length) % options.value.length;
    const option = options.value[nextIndex];
    if (!option.disabled) {
      return nextIndex;
    }
  }

  return highlightedIndex.value;
};

const highlight = (index: number) => {
  if (options.value[index]?.disabled) {
    return;
  }
  highlightedIndex.value = index;
};

const highlightInitial = () => {
  if (props.multiple) {
    highlightedIndex.value = getNextIndex(1);
    return;
  }

  const selectedIndex = options.value.findIndex(option => option.value === props.modelValue);

  if (selectedIndex >= 0 && !options.value[selectedIndex]?.disabled) {
    highlightedIndex.value = selectedIndex;
    return;
  }

  highlightedIndex.value = getNextIndex(1);
};

const isOptionSelected = (value: string | number) => {
  if (props.multiple) {
    const currentValue = Array.isArray(props.modelValue) ? props.modelValue : [];
    return currentValue.includes(value);
  }

  return props.modelValue === value;
};

const onOptionClick = (option: IDropdownOption) => {
  if (option.disabled) {
    return;
  }

  if (props.multiple) {
    const currentValue = Array.isArray(props.modelValue) ? [...props.modelValue] : [];

    if (currentValue.includes(option.value)) {
      const nextValue = currentValue.filter(value => value !== option.value);
      emit('update:modelValue', nextValue);
    } else {
      emit('update:modelValue', [...currentValue, option.value]);
    }
  } else {
    emit('update:modelValue', option.value);
    close();
  }
};

const removeOption = (value: string | number) => {
  if (!props.multiple || props.disabled) {
    return;
  }

  const currentValue = Array.isArray(props.modelValue) ? props.modelValue : [];
  emit(
    'update:modelValue',
    currentValue.filter(item => item !== value)
  );
};

const clearSelection = () => {
  if (!hasValue.value || props.disabled) {
    return;
  }

  if (props.multiple) {
    emit('update:modelValue', []);
  } else {
    emit('update:modelValue', null);
  }

  emit('clear');
};

const handleTriggerClick = () => {
  toggle();
};

const handleTriggerKeydown = (event: KeyboardEvent) => {
  if (props.disabled) {
    return;
  }

  switch (event.key) {
    case 'ArrowDown': {
      event.preventDefault();
      if (!isOpen.value) {
        void open();
      } else {
        highlight(getNextIndex(1));
        scrollHighlightedIntoView();
      }
      break;
    }
    case 'ArrowUp': {
      event.preventDefault();
      if (isOpen.value) {
        highlight(getNextIndex(-1));
        scrollHighlightedIntoView();
      } else {
        void open();
      }
      break;
    }
    case 'Enter': {
      event.preventDefault();
      if (!isOpen.value) {
        void open();
      } else if (highlightedIndex.value >= 0) {
        const option = options.value[highlightedIndex.value];
        if (option) {
          onOptionClick(option);
        }
      }
      break;
    }
    case 'Escape': {
      if (isOpen.value) {
        event.preventDefault();
        close();
      }
      break;
    }
    case 'Tab': {
      close();
      break;
    }
    default:
      break;
  }
};

const scrollHighlightedIntoView = () => {
  if (!contentRef.value || highlightedIndex.value < 0) {
    return;
  }

  const optionElements = contentRef.value.querySelectorAll<HTMLElement>(
    `.${CSS_CLASSES.BB_DROPDOWN_OPTION}`
  );
  const element = optionElements[highlightedIndex.value];

  if (!element) {
    return;
  }

  const { offsetTop, offsetHeight } = element;
  const { scrollTop, clientHeight } = contentRef.value;

  const isAbove = offsetTop < scrollTop;
  const isBelow = offsetTop + offsetHeight > scrollTop + clientHeight;

  if (isAbove) {
    contentRef.value.scrollTo({ top: offsetTop, behavior: 'smooth' });
  } else if (isBelow) {
    contentRef.value.scrollTo({
      top: offsetTop - clientHeight + offsetHeight,
      behavior: 'smooth',
    });
  }
};

const handleContentScroll = (event: Event) => {
  const element = event.target as HTMLElement;
  const threshold = 32;

  if (element.scrollHeight - element.scrollTop - element.clientHeight <= threshold) {
    emit('scroll-bottom');
  }
};

const handleOutsideClick = (event: MouseEvent) => {
  const target = event.target as HTMLElement;
  const containsTarget =
    rootRef.value?.contains(target) || panelRef.value?.contains(target) || false;

  if (!containsTarget) {
    close();
  }
};

const handleWindowChange = () => {
  if (isOpen.value) {
    updatePosition();
  }
};

const isElementScrollable = (element: HTMLElement) => {
  const style = window.getComputedStyle(element);
  const overflowY = style.overflowY;
  const overflow = style.overflow;
  const isScrollable =
    overflowY === 'scroll' || overflowY === 'auto' || overflow === 'scroll' || overflow === 'auto';

  if (!isScrollable) {
    return false;
  }

  return element.scrollHeight > element.clientHeight;
};

const findScrollableAncestors = (element: HTMLElement | null) => {
  const ancestors: HTMLElement[] = [];
  if (!element) {
    return ancestors;
  }

  let current = element.parentElement;
  while (current && current !== document.body) {
    if (isElementScrollable(current)) {
      ancestors.push(current);
    }
    current = current.parentElement;
  }

  return ancestors;
};

const cleanupScrollableAncestors = () => {
  scrollListeners.forEach(({ ancestor, handler }) => {
    ancestor.removeEventListener('scroll', handler);
  });
  scrollListeners = [];
  scrollableAncestors = [];
};

const attachScrollableAncestors = () => {
  cleanupScrollableAncestors();
  const triggerElement = triggerRef.value;
  if (!triggerElement) {
    return;
  }

  const ancestors = findScrollableAncestors(triggerElement);
  scrollableAncestors = [window, ...ancestors];

  scrollableAncestors.forEach(ancestor => {
    const handler = handleWindowChange;
    ancestor.addEventListener('scroll', handler, { passive: true });
    scrollListeners.push({ ancestor, handler });
  });
};

const triggerSlotProps = computed(() => ({
  state: {
    isOpen: isOpen.value,
    hasValue: hasValue.value,
    selectedOptions: selectedOptions.value,
    multiple: props.multiple,
    disabled: props.disabled,
  },
  actions: {
    open,
    close,
    toggle,
    clear: clearSelection,
  },
}));

const panelSlotProps = computed(() => ({
  state: {
    isOpen: isOpen.value,
    selectedOptions: selectedOptions.value,
    highlightedIndex: highlightedIndex.value,
  },
  actions: {
    open,
    close,
    toggle,
    updatePosition,
  },
}));

watch(
  () => props.modelValue as TDropdownValue,
  () => {
    if (!props.multiple) {
      highlightInitial();
    }
  }
);

watch(isOpen, (value: boolean) => {
  if (value) {
    document.addEventListener('mousedown', handleOutsideClick, true);
    window.addEventListener('resize', handleWindowChange);
    void nextTick(() => {
      attachScrollableAncestors();
      updatePosition();
    });
  } else {
    document.removeEventListener('mousedown', handleOutsideClick, true);
    window.removeEventListener('resize', handleWindowChange);
    cleanupScrollableAncestors();
  }
});

onMounted(() => {
  if (props.invalid) {
    void nextTick(() => {
      if (isOpen.value) {
        updatePosition();
      }
    });
  }
});

onBeforeUnmount(() => {
  document.removeEventListener('mousedown', handleOutsideClick, true);
  window.removeEventListener('resize', handleWindowChange);
  cleanupScrollableAncestors();
});

defineExpose({
  open,
  close,
  toggle,
  updatePosition,
  saveScrollPosition,
  restoreScrollPosition,
  saveScrollSnapshot,
  restoreScrollFromSnapshot,
  isOpen,
});
</script>
