// src/react/components/RepeaterControl.tsx
import { useEffect, useMemo } from 'react';

import type {
  ICustomFieldFormScope,
  ICustomFieldRendererRegistry,
} from '../../core/ports/CustomFieldRenderer';
import type { IRepeaterItemFieldConfig } from '../../core/types/form';
import type { ApiSelectUseCase } from '../../core/use-cases/ApiSelectUseCase';
import type { IRepeaterRef } from '../../shared/services/ValidationErrorHandler';
import { CSS_CLASSES, UI_STRINGS } from '../../utils/constants';
import { Icon } from './icons/Icon';
import { useRepeaterControl } from '../hooks/useRepeaterControl';
import { RepeaterItemFields } from './RepeaterItemFields';

export interface IRepeaterControlProps {
  modelValue?: unknown[];
  fieldName: string;
  label: string;
  fields: IRepeaterItemFieldConfig[];
  rules?: Array<{ type: string; message?: string; value?: unknown }>;
  errors?: Record<string, string[]>;
  addButtonText?: string;
  removeButtonText?: string;
  itemTitle?: string;
  countLabelVariants?: {
    one: string;
    few: string;
    many: string;
    zero?: string;
  };
  min?: number;
  max?: number;
  defaultItemValue?: Record<string, unknown>;
  apiSelectUseCase?: ApiSelectUseCase;
  isApiSelectAvailable?: (field: IRepeaterItemFieldConfig) => boolean;
  getApiSelectRestrictionMessage?: () => string;
  customFieldRendererRegistry?: ICustomFieldRendererRegistry;
  isCustomFieldAvailable?: (field: IRepeaterItemFieldConfig) => boolean;
  getCustomFieldRestrictionMessage?: () => string;
  nestingDepth?: number;
  maxNestingDepth?: number;
  parentFieldPath?: string;
  blockFormData?: Record<string, unknown>;
  setBlockField?: (name: string, value: unknown) => void;
  onChange: (value: unknown[]) => void;
  onRendererReady?: (fieldName: string, renderer: IRepeaterRef) => void;
}

export function RepeaterControl({
  modelValue,
  fieldName,
  label,
  fields,
  rules,
  errors,
  addButtonText = UI_STRINGS.repeaterAdd,
  removeButtonText = UI_STRINGS.repeaterRemove,
  itemTitle = UI_STRINGS.repeaterItem,
  countLabelVariants,
  min,
  max,
  defaultItemValue,
  apiSelectUseCase,
  isApiSelectAvailable = () => false,
  getApiSelectRestrictionMessage = () => 'API Select поля недоступны.',
  customFieldRendererRegistry,
  isCustomFieldAvailable = () => false,
  getCustomFieldRestrictionMessage = () => 'Кастомные поля недоступны.',
  nestingDepth = 0,
  maxNestingDepth = 2,
  parentFieldPath = '',
  blockFormData = {},
  setBlockField,
  onChange,
  onRendererReady,
}: IRepeaterControlProps) {
  const repeater = useRepeaterControl({
    fieldName,
    modelValue,
    fields,
    rules,
    errors,
    min,
    max,
    defaultItemValue,
    countLabelVariants,
    parentFieldPath,
    nestingDepth,
    maxNestingDepth,
    onChange,
  });

  const apiSelectRestrictionMessage = useMemo(() => {
    const message = getApiSelectRestrictionMessage();
    return typeof message === 'string' && message.trim().length > 0
      ? message
      : 'API Select поля недоступны.';
  }, [getApiSelectRestrictionMessage]);

  const customFieldRestrictionMessage = useMemo(() => {
    const message = getCustomFieldRestrictionMessage();
    return typeof message === 'string' && message.trim().length > 0
      ? message
      : 'Кастомные поля недоступны.';
  }, [getCustomFieldRestrictionMessage]);

  useEffect(() => {
    onRendererReady?.(fieldName, {
      expandItem: repeater.expandItem,
      isItemCollapsed: repeater.isItemCollapsed,
    });
  }, [fieldName, onRendererReady, repeater.expandItem, repeater.isItemCollapsed]);

  return (
    <div className={CSS_CLASSES.REPEATER_CONTROL} data-field-name={fieldName}>
      <div className={CSS_CLASSES.REPEATER_CONTROL_HEADER}>
        <label className={CSS_CLASSES.REPEATER_CONTROL_LABEL}>
          {label}
          {repeater.isRequired ? <span className={CSS_CLASSES.REQUIRED}>*</span> : null}
        </label>
        {repeater.itemCount > 0 ? (
          <span className={CSS_CLASSES.REPEATER_CONTROL_COUNT}>
            {repeater.getCountText(repeater.itemCount)}
          </span>
        ) : null}
      </div>

      <div className={CSS_CLASSES.REPEATER_CONTROL_ITEMS}>
        {repeater.items.map((item, index) => (
          <div
            key={item._id}
            className={[
              CSS_CLASSES.REPEATER_CONTROL_ITEM,
              repeater.collapsedItems[item._id] ? CSS_CLASSES.REPEATER_CONTROL_ITEM_COLLAPSED : '',
            ]
              .filter(Boolean)
              .join(' ')}
          >
            <div className={CSS_CLASSES.REPEATER_CONTROL_ITEM_HEADER}>
              <span className={CSS_CLASSES.REPEATER_CONTROL_ITEM_TITLE}>
                {itemTitle} #{index + 1}
              </span>
              <div className={CSS_CLASSES.REPEATER_CONTROL_ITEM_ACTIONS}>
                {index > 0 ? (
                  <button
                    type="button"
                    className={`${CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN} ${CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN_MOVE}`}
                    title="Переместить вверх"
                    onClick={() => repeater.moveItem(index, index - 1)}
                  >
                    <Icon name="arrowUp" />
                  </button>
                ) : null}
                {index < repeater.items.length - 1 ? (
                  <button
                    type="button"
                    className={`${CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN} ${CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN_MOVE}`}
                    title="Переместить вниз"
                    onClick={() => repeater.moveItem(index, index + 1)}
                  >
                    <Icon name="arrowDown" />
                  </button>
                ) : null}
                <button
                  type="button"
                  className={`${CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN} ${CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN_REMOVE}`}
                  disabled={!repeater.canRemove}
                  title={removeButtonText}
                  onClick={() => repeater.removeItem(index)}
                >
                  <Icon name="delete" />
                </button>
                <span
                  className={CSS_CLASSES.REPEATER_CONTROL_ITEM_ACTIONS_SEPARATOR}
                  aria-hidden="true"
                />
                <button
                  type="button"
                  className={`${CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN} ${CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN_COLLAPSE}`}
                  title={repeater.collapsedItems[item._id] ? 'Развернуть' : 'Свернуть'}
                  onClick={() => repeater.toggleCollapse(item._id)}
                >
                  <Icon name="chevronDown" />
                </button>
              </div>
            </div>

            {!repeater.collapsedItems[item._id] ? (
              <div className={CSS_CLASSES.REPEATER_CONTROL_ITEM_FIELDS}>
                <RepeaterItemFields
                  itemIndex={index}
                  item={item}
                  fieldGroups={repeater.getGroupedFieldsForItem(index)}
                  repeaterFieldName={fieldName}
                  formErrors={repeater.formErrors}
                  apiSelectUseCase={apiSelectUseCase}
                  isApiSelectAvailable={isApiSelectAvailable}
                  apiSelectRestrictionMessage={apiSelectRestrictionMessage}
                  getApiSelectRestrictionMessage={getApiSelectRestrictionMessage}
                  customFieldRendererRegistry={customFieldRendererRegistry}
                  isCustomFieldAvailable={isCustomFieldAvailable}
                  customFieldRestrictionMessage={customFieldRestrictionMessage}
                  getCustomFieldRestrictionMessage={getCustomFieldRestrictionMessage}
                  nestingDepth={nestingDepth}
                  maxNestingDepth={maxNestingDepth}
                  blockFormData={blockFormData}
                  setBlockField={setBlockField}
                  NestedRepeaterControl={RepeaterControl}
                  getFieldId={repeater.getFieldId}
                  isFieldRequired={repeater.isFieldRequired}
                  getFullFieldPath={repeater.getFullFieldPath}
                  hasFieldError={repeater.hasFieldError}
                  getFieldErrors={repeater.getFieldErrors}
                  getNestedErrors={repeater.getNestedErrors}
                  canNestRepeater={repeater.canNestRepeater}
                  getRepeaterBasePath={repeater.getRepeaterBasePath}
                  isRepeaterFieldVisible={repeater.isRepeaterFieldVisible}
                  updateItemField={repeater.updateItemField}
                />
              </div>
            ) : null}
          </div>
        ))}
      </div>

      <button
        type="button"
        className={`${CSS_CLASSES.REPEATER_CONTROL_ADD_BTN} ${CSS_CLASSES.BTN} ${CSS_CLASSES.BTN_SUCCESS} ${CSS_CLASSES.BTN_BLOCK}`}
        disabled={!repeater.canAdd}
        onClick={repeater.addItem}
      >
        + {addButtonText}
      </button>

      {repeater.effectiveMin || max ? (
        <div className={CSS_CLASSES.REPEATER_CONTROL_HINT}>
          {repeater.effectiveMin && repeater.itemCount < repeater.effectiveMin ? (
            <span className={CSS_CLASSES.REPEATER_CONTROL_HINT_ERROR}>
              {repeater.repeaterMinText} {repeater.effectiveMin}
            </span>
          ) : max && repeater.itemCount >= max ? (
            <span className={CSS_CLASSES.REPEATER_CONTROL_HINT_WARNING}>
              {repeater.repeaterMaxText} {max}
            </span>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}

// src/vue/components/RepeaterControl.vue
<template>
  <div :class="CSS_CLASSES.REPEATER_CONTROL" :data-field-name="fieldName">
    <div :class="CSS_CLASSES.REPEATER_CONTROL_HEADER">
      <label :class="CSS_CLASSES.REPEATER_CONTROL_LABEL">
        {{ label }}
        <span v-if="isRequired" :class="CSS_CLASSES.REQUIRED">*</span>
      </label>
      <span v-if="itemCount > 0" :class="CSS_CLASSES.REPEATER_CONTROL_COUNT">
        {{ getCountText(itemCount) }}
      </span>
    </div>

    <div :class="CSS_CLASSES.REPEATER_CONTROL_ITEMS">
      <div
        v-for="(item, index) in items"
        :key="item._id"
        :class="[
          CSS_CLASSES.REPEATER_CONTROL_ITEM,
          { [CSS_CLASSES.REPEATER_CONTROL_ITEM_COLLAPSED]: collapsedItems[item._id] },
        ]"
      >
        <div :class="CSS_CLASSES.REPEATER_CONTROL_ITEM_HEADER">
          <span :class="CSS_CLASSES.REPEATER_CONTROL_ITEM_TITLE"> {{ itemTitle }} #{{ index + 1 }} </span>
            <div :class="CSS_CLASSES.REPEATER_CONTROL_ITEM_ACTIONS">
            <button
              v-if="index > 0"
              type="button"
              :class="[CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN, CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN_MOVE]"
              title="Переместить вверх"
              @click="moveItem(index, index - 1)"
            >
              <Icon name="arrowUp" />
            </button>
            <button
              v-if="index < items.length - 1"
              type="button"
              :class="[CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN, CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN_MOVE]"
              title="Переместить вниз"
              @click="moveItem(index, index + 1)"
            >
              <Icon name="arrowDown" />
            </button>
            <button
              type="button"
              :class="[CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN, CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN_REMOVE]"
              :disabled="!canRemove"
              :title="removeButtonText"
              @click="removeItem(index)"
            >
              <Icon name="delete" />
            </button>
            <span
              :class="CSS_CLASSES.REPEATER_CONTROL_ITEM_ACTIONS_SEPARATOR"
              aria-hidden="true"
            />
            <button
              type="button"
              :class="[CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN, CSS_CLASSES.REPEATER_CONTROL_ITEM_BTN_COLLAPSE]"
              :title="collapsedItems[item._id] ? 'Развернуть' : 'Свернуть'"
              @click="toggleCollapse(item._id)"
            >
              <Icon name="chevronDown" />
            </button>
          </div>
        </div>

        <div v-if="!collapsedItems[item._id]" :class="CSS_CLASSES.REPEATER_CONTROL_ITEM_FIELDS">
          <!-- eslint-disable-next-line vue/no-v-for-template-key -->
          <template v-for="fieldGroup in getGroupedFieldsForItem(index)" :key="fieldGroup.key">
            <ToggleControl
              v-if="fieldGroup.type === 'toggle-group'"
              :model-value="item[fieldGroup.toggleField.field] || false"
              :field-name="fieldGroup.toggleField.field"
              @update:model-value="updateItemField(index, fieldGroup.toggleField.field, $event)"
            >
              <template #label>{{ fieldGroup.toggleField.label }}</template>
              <template #body>
                <FormField
                  v-for="dependentField in fieldGroup.dependentFields"
                  :key="dependentField.field"
                  :field="dependentField"
                  :field-id="getFieldId(item._id, dependentField.field)"
                  :field-path="getFullFieldPath(index, dependentField.field)"
                  :model-value="item[dependentField.field]"
                  :required="isFieldRequired(dependentField)"
                  :error="
                    hasFieldError(index, dependentField.field)
                      ? getFieldErrors(index, dependentField.field)[0]
                      : ''
                  "
              :container-class="
                hasFieldError(index, dependentField.field)
                  ? `${CSS_CLASSES.FORM_GROUP} ${CSS_CLASSES.ERROR}`
                  : CSS_CLASSES.FORM_GROUP
              "
              :form-data="blockFormDataValue"
              :item-data="item"
              @update:model-value="updateItemField(index, dependentField.field, $event)"
                >
                  <template
                    #default="{ field: slotField, modelValue: slotModelValue, error: slotError }"
                  >
                    <template v-if="slotField.type === 'api-select'">
                      <ApiSelectField
                        v-if="isApiSelectFieldAllowed(slotField) && apiSelectUseCaseValue"
                        :model-value="slotModelValue"
                        :config="toFormFieldConfig(slotField)"
                        :validation-error="slotError"
                        :api-select-use-case="apiSelectUseCaseValue"
                        @update:model-value="updateItemField(index, slotField.field, $event)"
                      />
                      <div v-else :class="CSS_CLASSES.BB_WARNING_BOX">⚠️ {{ apiSelectRestrictionMessage }}</div>
                    </template>

                    <template v-else-if="slotField.type === 'custom'">
                      <label :for="getFieldId(item._id, slotField.field)" :class="CSS_CLASSES.FORM_LABEL">
                        {{ slotField.label }}
                        <span v-if="isFieldRequired(slotField)" :class="CSS_CLASSES.REQUIRED">*</span>
                      </label>
                      <CustomField
                        v-if="
                          isCustomFieldAllowed(slotField) &&
                          customFieldRendererRegistryValue?.get(slotField.customFieldConfig?.rendererId)
                        "
                        :field="toFormFieldConfig(slotField)"
                        :model-value="slotModelValue"
                        :form-errors="formErrors"
                        :custom-field-renderer-registry="customFieldRendererRegistryValue"
                        :is-field-required="isFieldRequired"
                        :form-scope="buildFormScopeForItem(index)"
                        @update:model-value="updateItemField(index, slotField.field, $event)"
                      />
                      <div v-else :class="CSS_CLASSES.BB_WARNING_BOX">⚠️ {{ customFieldRestrictionMessage }}</div>
                    </template>

                    <FileImportField
                      v-else-if="slotField.type === 'file-import' && slotField.fileImportConfig"
                      :label="slotField.label"
                      :error="slotError"
                      :file-import-config="slotField.fileImportConfig"
                      :form-scope="buildFormScopeForItem(index)"
                    />

                    <ImageUploadField
                      v-else-if="slotField.type === 'image' || slotField.type === 'file'"
                      :model-value="slotModelValue"
                      :label="''"
                      :required="isFieldRequired(slotField)"
                      :error="slotError"
                      :variant="slotField.type === 'file' ? 'file' : 'image'"
                      :multiple="slotField.multiple ?? false"
                      :file-upload-config="slotField.fileUploadConfig"
                      :data-repeater-field="fieldName"
                      :data-repeater-index="index"
                      :data-repeater-item-field="slotField.field"
                      @update:model-value="updateItemField(index, slotField.field, $event)"
                    />

                    <RepeaterControl
                      v-else-if="slotField.type === 'repeater' && canNestRepeater(slotField)"
                      :model-value="slotModelValue || []"
                      :field-name="slotField.field"
                      :label="slotField.label"
                      :fields="slotField.repeaterConfig?.fields || []"
                      :rules="slotField.rules || []"
                      :errors="getNestedErrors(index, slotField.field)"
                      :add-button-text="slotField.repeaterConfig?.addButtonText"
                      :remove-button-text="slotField.repeaterConfig?.removeButtonText"
                      :item-title="slotField.repeaterConfig?.itemTitle"
                      :count-label-variants="slotField.repeaterConfig?.countLabelVariants"
                      :min="slotField.repeaterConfig?.min"
                      :max="slotField.repeaterConfig?.max"
                      :default-item-value="slotField.repeaterConfig?.defaultItemValue"
                      :api-select-use-case="apiSelectUseCaseValue"
                      :is-api-select-available="isApiSelectAvailable"
                      :get-api-select-restriction-message="getApiSelectRestrictionMessage"
                      :custom-field-renderer-registry="customFieldRendererRegistryValue"
                      :is-custom-field-available="isCustomFieldAvailable"
                      :get-custom-field-restriction-message="getCustomFieldRestrictionMessage"
                      :block-form-data="blockFormDataValue"
                      :set-block-field="setBlockFieldValue"
                      :nesting-depth="nestingDepth + 1"
                      :max-nesting-depth="slotField.repeaterConfig?.maxNestingDepth ?? maxNestingDepth"
                      :parent-field-path="
                        getRepeaterBasePath()
                          ? `${getRepeaterBasePath()}[${index}].${slotField.field}`
                          : `${props.fieldName}[${index}].${slotField.field}`
                      "
                      @update:model-value="updateItemField(index, slotField.field, $event)"
                    />
                  </template>
                </FormField>
              </template>
            </ToggleControl>

            <FormField
              v-else-if="fieldGroup.type === 'single'"
              v-show="isRepeaterFieldVisible(fieldGroup.field, item, index)"
              :field="fieldGroup.field"
              :field-id="getFieldId(item._id, fieldGroup.field.field)"
              :field-path="getFullFieldPath(index, fieldGroup.field.field)"
              :model-value="item[fieldGroup.field.field]"
              :required="isFieldRequired(fieldGroup.field)"
              :error="
                hasFieldError(index, fieldGroup.field.field)
                  ? getFieldErrors(index, fieldGroup.field.field)[0]
                  : ''
              "
              :container-class="
                hasFieldError(index, fieldGroup.field.field)
                  ? `${CSS_CLASSES.FORM_GROUP} ${CSS_CLASSES.ERROR}`
                  : CSS_CLASSES.FORM_GROUP
              "
              :form-data="blockFormDataValue"
              :item-data="item"
              @update:model-value="updateItemField(index, fieldGroup.field.field, $event)"
            >
              <template
                #default="{ field: slotField, modelValue: slotModelValue, error: slotError }"
              >
                <template v-if="slotField.type === 'api-select'">
                  <ApiSelectField
                    v-if="isApiSelectFieldAllowed(slotField) && apiSelectUseCaseValue"
                    :model-value="slotModelValue"
                    :config="toFormFieldConfig(slotField)"
                    :validation-error="slotError"
                    :api-select-use-case="apiSelectUseCaseValue"
                    @update:model-value="updateItemField(index, slotField.field, $event)"
                  />
                  <div v-else :class="CSS_CLASSES.BB_WARNING_BOX">⚠️ {{ apiSelectRestrictionMessage }}</div>
                </template>

                <template v-else-if="slotField.type === 'custom'">
                  <label :for="getFieldId(item._id, slotField.field)" :class="CSS_CLASSES.FORM_LABEL">
                    {{ slotField.label }}
                    <span v-if="isFieldRequired(slotField)" :class="CSS_CLASSES.REQUIRED">*</span>
                  </label>
                  <CustomField
                    v-if="
                      isCustomFieldAllowed(slotField) &&
                      customFieldRendererRegistryValue?.get(slotField.customFieldConfig?.rendererId)
                    "
                    :field="toFormFieldConfig(slotField)"
                    :model-value="slotModelValue"
                    :form-errors="formErrors"
                    :custom-field-renderer-registry="customFieldRendererRegistryValue"
                    :is-field-required="isFieldRequired"
                    :form-scope="buildFormScopeForItem(index)"
                    @update:model-value="updateItemField(index, slotField.field, $event)"
                  />
                  <div v-else :class="CSS_CLASSES.BB_WARNING_BOX">⚠️ {{ customFieldRestrictionMessage }}</div>
                </template>

                <FileImportField
                  v-else-if="slotField.type === 'file-import' && slotField.fileImportConfig"
                  :label="slotField.label"
                  :error="slotError"
                  :file-import-config="slotField.fileImportConfig"
                  :form-scope="buildFormScopeForItem(index)"
                />

                <ImageUploadField
                  v-else-if="slotField.type === 'image' || slotField.type === 'file'"
                  :model-value="slotModelValue"
                  :label="''"
                  :required="isFieldRequired(slotField)"
                  :error="slotError"
                  :variant="slotField.type === 'file' ? 'file' : 'image'"
                  :multiple="slotField.multiple ?? false"
                  :file-upload-config="slotField.fileUploadConfig"
                  :data-repeater-field="fieldName"
                  :data-repeater-index="index"
                  :data-repeater-item-field="slotField.field"
                  @update:model-value="updateItemField(index, slotField.field, $event)"
                />

                <RepeaterControl
                  v-else-if="slotField.type === 'repeater' && canNestRepeater(slotField)"
                  :model-value="slotModelValue || []"
                  :field-name="slotField.field"
                  :label="slotField.label"
                  :fields="slotField.repeaterConfig?.fields || []"
                  :rules="slotField.rules || []"
                  :errors="getNestedErrors(index, slotField.field)"
                  :add-button-text="slotField.repeaterConfig?.addButtonText"
                  :remove-button-text="slotField.repeaterConfig?.removeButtonText"
                  :item-title="slotField.repeaterConfig?.itemTitle"
                  :count-label-variants="slotField.repeaterConfig?.countLabelVariants"
                  :min="slotField.repeaterConfig?.min"
                  :max="slotField.repeaterConfig?.max"
                  :default-item-value="slotField.repeaterConfig?.defaultItemValue"
                  :api-select-use-case="apiSelectUseCaseValue"
                  :is-api-select-available="isApiSelectAvailable"
                  :get-api-select-restriction-message="getApiSelectRestrictionMessage"
                  :custom-field-renderer-registry="customFieldRendererRegistryValue"
                  :is-custom-field-available="isCustomFieldAvailable"
                  :get-custom-field-restriction-message="getCustomFieldRestrictionMessage"
                  :block-form-data="blockFormDataValue"
                  :set-block-field="setBlockFieldValue"
                  :nesting-depth="nestingDepth + 1"
                  :max-nesting-depth="slotField.repeaterConfig?.maxNestingDepth ?? maxNestingDepth"
                  :parent-field-path="
                    getRepeaterBasePath()
                      ? `${getRepeaterBasePath()}[${index}].${slotField.field}`
                      : `${props.fieldName}[${index}].${slotField.field}`
                  "
                  @update:model-value="updateItemField(index, slotField.field, $event)"
                />
              </template>
            </FormField>
          </template>
        </div>
      </div>
    </div>

    <button
      type="button"
      :class="[
        CSS_CLASSES.REPEATER_CONTROL_ADD_BTN,
        CSS_CLASSES.BTN,
        CSS_CLASSES.BTN_SUCCESS,
        CSS_CLASSES.BTN_BLOCK,
      ]"
      :disabled="!canAdd"
      @click="addItem"
    >
      + {{ addButtonText }}
    </button>

    <div v-if="effectiveMin || max" :class="CSS_CLASSES.REPEATER_CONTROL_HINT">
      <span
        v-if="effectiveMin && itemCount < effectiveMin"
        :class="CSS_CLASSES.REPEATER_CONTROL_HINT_ERROR"
      >
        {{ repeaterMinText }} {{ effectiveMin }}
      </span>
      <span v-else-if="max && itemCount >= max" :class="CSS_CLASSES.REPEATER_CONTROL_HINT_WARNING">
        {{ repeaterMaxText }} {{ max }}
      </span>
    </div>
  </div>
</template>

<script>
import { computed, onMounted, ref, watch } from 'vue';

import { CSS_CLASSES, UI_STRINGS } from '../../utils/constants';
import Icon from '../../shared/icons/Icon.vue';
import { groupFormFields } from '../../utils/formFieldGrouping';
import { isFieldRequired, isFieldVisible } from '../../utils/formFieldHelpers';
import { getRepeaterCountText } from '../../utils/repeaterCountText';
import { resolveFormFieldDefaultValue } from '../../utils/formFieldDefaults';
import {
  assignRepeaterItemId,
  isAutoRepeaterItemIdField,
  isReadonlyRepeaterItemField,
} from '../../utils/repeaterItemId';
import { createRepeaterFormScope } from '../../utils/formScopeHelpers';
import ApiSelectField from './ApiSelectField.vue';
import CustomField from './CustomField.vue';
import FileImportField from './FileImportField.vue';
import { FormField } from './form-fields';
import ImageUploadField from './ImageUploadField.vue';
import ToggleControl from './ToggleControl.vue';

export default {
  name: 'RepeaterControl',
  components: {
    FormField,
    ApiSelectField,
    CustomField,
    FileImportField,
    ImageUploadField,
    ToggleControl,
    Icon,
  },

  props: {
    fieldName: {
      type: String,
      required: true,
    },

    label: {
      type: String,
      required: true,
    },

    modelValue: {
      type: Array,
      default: () => [],
    },

    fields: {
      type: Array,
      required: true,
    },

    rules: {
      type: Array,
      default: () => [],
    },

    errors: {
      type: Object,
      default: () => ({}),
    },

    addButtonText: {
      type: String,
      default: UI_STRINGS.repeaterAdd,
    },

    removeButtonText: {
      type: String,
      default: UI_STRINGS.repeaterRemove,
    },

    itemTitle: {
      type: String,
      default: UI_STRINGS.repeaterItem,
    },

    countLabelVariants: {
      type: Object,
      default: null,
    },

    min: {
      type: Number,
      default: undefined, // undefined значит - определяется автоматически
    },

    max: {
      type: Number,
      default: undefined,
    },

    defaultItemValue: {
      type: Object,
      default: () => ({}),
    },

    apiSelectUseCase: {
      type: Object,
      default: null,
    },

    isApiSelectAvailable: {
      type: Function,
      default: () => false,
    },

    getApiSelectRestrictionMessage: {
      type: Function,
      default: () => 'API Select поля недоступны.',
    },

    customFieldRendererRegistry: {
      type: Object,
      default: null,
    },

    isCustomFieldAvailable: {
      type: Function,
      default: () => false,
    },

    getCustomFieldRestrictionMessage: {
      type: Function,
      default: () => 'Кастомные поля недоступны.',
    },

    nestingDepth: {
      type: Number,
      default: 0,
    },

    maxNestingDepth: {
      type: Number,
      default: 2,
    },

    parentFieldPath: {
      type: String,
      default: '',
    },

    blockFormData: {
      type: Object,
      default: () => ({}),
    },

    setBlockField: {
      type: Function,
      default: null,
    },
  },

  emits: ['update:modelValue'],
  setup(props, { emit }) {
    const items = ref([]);
    const collapsedItems = ref({});
    let idCounter = 0;

    const apiSelectRestrictionMessage = computed(() => {
      const message = props.getApiSelectRestrictionMessage();
      return typeof message === 'string' && message.trim().length > 0
        ? message
        : 'API Select поля недоступны.';
    });

    const customFieldRestrictionMessage = computed(() => {
      const message = props.getCustomFieldRestrictionMessage();
      return typeof message === 'string' && message.trim().length > 0
        ? message
        : 'Кастомные поля недоступны.';
    });

    const isRequired = computed(() => {
      return props.rules?.some(rule => rule.type === 'required') ?? false;
    });

    const effectiveMin = computed(() => {
      if (!isRequired.value) {
        return 0;
      }
      if (props.min !== undefined) {
        return props.min;
      }
      return 1;
    });

    const initializeItems = () => {
      if (props.modelValue && props.modelValue.length > 0) {
        items.value = props.modelValue.map(item => {
          const withId = assignRepeaterItemId({ ...item }, props.fields);
          return {
            _id: `item-${idCounter++}`,
            ...withId,
          };
        });
      } else if (effectiveMin.value > 0) {
        for (let i = 0; i < effectiveMin.value; i++) {
          items.value.push(createNewItem());
        }
        emitUpdate();
      }
    };

    const createNewItem = () => {
      const newItem = { _id: `item-${idCounter++}` };

      props.fields.forEach(field => {
        if (isAutoRepeaterItemIdField(field)) {
          return;
        }

        if (props.defaultItemValue && props.defaultItemValue[field.field] !== undefined) {
          newItem[field.field] = props.defaultItemValue[field.field];
        } else if (field.defaultValue !== undefined) {
          newItem[field.field] = field.defaultValue;
        } else {
          newItem[field.field] = resolveFormFieldDefaultValue(field);
        }
      });

      return assignRepeaterItemId(newItem, props.fields, { forceNew: true });
    };

    const itemCount = computed(() => items.value.length);

    const canAdd = computed(() => {
      return !props.max || itemCount.value < props.max;
    });

    const canRemove = computed(() => {
      return itemCount.value > effectiveMin.value;
    });

    const addItem = () => {
      if (!canAdd.value) {
        return;
      }

      items.value.push(createNewItem());
      emitUpdate();
    };

    const removeItem = index => {
      if (!canRemove.value) {
        return;
      }

      const item = items.value[index];
      items.value.splice(index, 1);

      if (collapsedItems.value[item._id]) {
        delete collapsedItems.value[item._id];
      }

      emitUpdate();
    };

    const moveItem = (fromIndex, toIndex) => {
      const item = items.value[fromIndex];
      items.value.splice(fromIndex, 1);
      items.value.splice(toIndex, 0, item);
      emitUpdate();
    };

    const toggleCollapse = itemId => {
      if (collapsedItems.value[itemId]) {
        delete collapsedItems.value[itemId];
      } else {
        collapsedItems.value[itemId] = true;
      }
    };

    const updateItemField = (index, fieldName, value) => {
      if (isReadonlyRepeaterItemField(fieldName, props.fields)) {
        return;
      }

      items.value[index][fieldName] = value;
      emitUpdate();
    };

    const toFormFieldConfig = field => {
      return {
        field: field.field,
        label: field.label,
        type: field.type,
        placeholder: field.placeholder,
        defaultValue: field.defaultValue,
        options: field.options,
        optionsFrom: field.optionsFrom,
        rules: field.rules,
        apiSelectConfig: field.apiSelectConfig,
        customFieldConfig: field.customFieldConfig,
        fileUploadConfig: field.fileUploadConfig,
        fileImportConfig: field.fileImportConfig,
        blockAnchorConfig: field.blockAnchorConfig,
        repeaterConfig: field.repeaterConfig,
        dependsOn: field.dependsOn,
        persist: field.persist,
        multiple: field.multiple,
      };
    };

    const isApiSelectFieldAllowed = field => {
      return props.isApiSelectAvailable ? props.isApiSelectAvailable(field) : false;
    };

    const isCustomFieldAllowed = field => {
      return props.isCustomFieldAvailable ? props.isCustomFieldAvailable(field) : false;
    };

    const apiSelectUseCaseValue = computed(() => props.apiSelectUseCase);
    const customFieldRendererRegistryValue = computed(() => props.customFieldRendererRegistry);
    const blockFormDataValue = computed(() => props.blockFormData || {});
    const setBlockFieldValue = (name, value) => {
      if (typeof props.setBlockField === 'function') {
        props.setBlockField(name, value);
      }
    };

    const buildFormScopeForItem = index => {
      const item = items.value[index];
      if (!item) {
        return undefined;
      }

      return createRepeaterFormScope(
        blockFormDataValue.value,
        setBlockFieldValue,
        props.fieldName,
        index,
        item,
        (field, value) => updateItemField(index, field, value)
      );
    };
    const formErrors = computed(() => props.errors);

    const emitUpdate = () => {
      const cleanItems = items.value.map(item => {
        const { _id, ...rest } = item;
        return rest;
      });
      emit('update:modelValue', cleanItems);
    };

    const getFieldId = (itemId, fieldName) => {
      const scope = props.parentFieldPath || props.fieldName || 'repeater';
      return `repeater-${scope}-${itemId}-${fieldName}`;
    };

    const getFullFieldPath = (index, fieldName) => {
      if (props.parentFieldPath) {
        return `${props.parentFieldPath}[${index}].${fieldName}`;
      }
      return `${props.fieldName}[${index}].${fieldName}`;
    };

    const getRepeaterBasePath = () => {
      if (props.parentFieldPath) {
        return props.parentFieldPath;
      }
      return props.fieldName;
    };

    const getFieldErrors = (index, fieldName) => {
      if (!props.errors || Object.keys(props.errors).length === 0) {
        return [];
      }

      const errorKey = getFullFieldPath(index, fieldName);
      const directError = props.errors[errorKey];
      if (directError && Array.isArray(directError) && directError.length > 0) {
        return directError;
      }

      return [];
    };

    const getNestedFieldName = (index, fieldName) => {
      return fieldName;
    };

    const getNestedErrors = (index, fieldName) => {
      const basePath = getFullFieldPath(index, fieldName);
      const nestedErrors = {};

      Object.keys(props.errors).forEach(key => {
        if (key.startsWith(`${basePath}[`) || key === basePath) {
          nestedErrors[key] = props.errors[key];
        }
      });

      return nestedErrors;
    };

    const canNestRepeater = field => {
      const maxDepth = field.repeaterConfig?.maxNestingDepth ?? props.maxNestingDepth;
      return props.nestingDepth < maxDepth;
    };

    const hasFieldError = (index, fieldName) => {
      return getFieldErrors(index, fieldName).length > 0;
    };

    const isRepeaterFieldVisible = (field, item) => isFieldVisible(field, props.blockFormData, item);

    const getGroupedFieldsForItem = index => {
      const item = items.value[index];
      if (!item) {
        return [];
      }

      return groupFormFields(props.fields, { keyPrefix: String(index) });
    };

    const getCountText = count => {
      return getRepeaterCountText(count, props.countLabelVariants || undefined);
    };

    const repeaterMinText = computed(() => {
      return UI_STRINGS?.repeaterMin || 'Минимум:';
    });

    const repeaterMaxText = computed(() => {
      return UI_STRINGS?.repeaterMax || 'Максимум:';
    });

    watch(
      () => props.modelValue,
      newValue => {
        if (
          JSON.stringify(newValue) !== JSON.stringify(items.value.map(({ _id, ...rest }) => rest))
        ) {
          initializeItems();
        }
      },
      { deep: true }
    );

    onMounted(() => {
      initializeItems();
    });

    const expandItem = index => {
      const item = items.value[index];
      if (item && collapsedItems.value[item._id]) {
        delete collapsedItems.value[item._id];
      }
    };

    const isItemCollapsed = index => {
      const item = items.value[index];
      return item ? !!collapsedItems.value[item._id] : false;
    };

    return {
      items,
      collapsedItems,
      itemCount,
      canAdd,
      canRemove,
      effectiveMin,
      isRequired,
      addItem,
      removeItem,
      moveItem,
      toggleCollapse,
      getFieldId,
      isFieldRequired,
      getCountText,
      getFieldErrors,
      hasFieldError,
      expandItem,
      isItemCollapsed,
      updateItemField,
      repeaterMinText,
      repeaterMaxText,
      apiSelectRestrictionMessage,
      customFieldRestrictionMessage,
      toFormFieldConfig,
      isApiSelectFieldAllowed,
      isCustomFieldAllowed,
      apiSelectUseCaseValue,
      customFieldRendererRegistryValue,
      formErrors,
      getFullFieldPath,
      getNestedFieldName,
      getNestedErrors,
      canNestRepeater,
      getRepeaterBasePath,
      isRepeaterFieldVisible,
      getGroupedFieldsForItem,
      CSS_CLASSES,
      buildFormScopeForItem,
      blockFormDataValue,
      setBlockFieldValue,
    };
  },
};
</script>
