// src/react/components/ToggleControl.tsx
import { CSS_CLASSES } from '../../utils/constants';
import type { ReactNode } from 'react';

interface IToggleControlProps {
  modelValue: boolean;
  onChange: (value: boolean) => void;
  label?: ReactNode;
  children?: ReactNode;
}

export function ToggleControl({ modelValue, onChange, label, children }: IToggleControlProps) {
  const handleToggleClick = () => {
    onChange(!modelValue);
  };

  return (
    <div className={CSS_CLASSES.TOGGLE_CONTROL}>
      <div className={CSS_CLASSES.TOGGLE_CONTROL_HEADER}>
        <div
          className={[
            CSS_CLASSES.TOGGLE_CONTROL_LABEL,
            modelValue ? CSS_CLASSES.TOGGLE_CONTROL_LABEL_ACTIVE : '',
          ]
            .filter(Boolean)
            .join(' ')}
          onClick={handleToggleClick}
        >
          {label}
        </div>
        <div
          className={[
            CSS_CLASSES.TOGGLE_CONTROL_BUTTON,
            modelValue ? CSS_CLASSES.TOGGLE_CONTROL_BUTTON_ACTIVE : '',
          ]
            .filter(Boolean)
            .join(' ')}
          onClick={handleToggleClick}
        >
          <div className={CSS_CLASSES.TOGGLE_CONTROL_BUTTON_INNER}>
            <div className={CSS_CLASSES.TOGGLE_CONTROL_BUTTON_CIRCLE} />
          </div>
        </div>
      </div>
      {modelValue ? <div className={CSS_CLASSES.TOGGLE_CONTROL_BODY}>{children}</div> : null}
    </div>
  );
}

// src/vue/components/ToggleControl.vue
<template>
  <div :class="CSS_CLASSES.TOGGLE_CONTROL">
    <div :class="CSS_CLASSES.TOGGLE_CONTROL_HEADER">
      <div
        :class="[
          CSS_CLASSES.TOGGLE_CONTROL_LABEL,
          { [CSS_CLASSES.TOGGLE_CONTROL_LABEL_ACTIVE]: modelValue },
        ]"
        @click="handleToggleClick"
      >
        <slot name="label">{{ label }}</slot>
      </div>
      <div
        :class="[
          CSS_CLASSES.TOGGLE_CONTROL_BUTTON,
          { [CSS_CLASSES.TOGGLE_CONTROL_BUTTON_ACTIVE]: modelValue },
        ]"
        @click="handleToggleClick"
      >
        <div :class="CSS_CLASSES.TOGGLE_CONTROL_BUTTON_INNER">
          <div :class="CSS_CLASSES.TOGGLE_CONTROL_BUTTON_CIRCLE" />
        </div>
      </div>
    </div>
    <div v-if="modelValue" :class="CSS_CLASSES.TOGGLE_CONTROL_BODY">
      <slot name="body" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { CSS_CLASSES } from '../../utils/constants';
interface Props {
  modelValue: boolean;
  label?: string;
  fieldName?: string;
}

const props = withDefaults(defineProps<Props>(), {
  label: '',
  fieldName: '',
});

const emit = defineEmits<{
  'update:modelValue': [value: boolean];
}>();

const handleToggleClick = (): void => {
  (emit as any)('update:modelValue', !props.modelValue);
};
</script>
