// examples/react/src/components/blocks/ImageBlock.tsx
interface IImageBlockProps {
  image: string | { src?: string }
  alt?: string
  borderRadius?: number
}

function getImageUrl(image: IImageBlockProps['image']) {
  if (typeof image === 'string') {
    return image
  }
  if (typeof image === 'object' && image !== null) {
    return image.src || ''
  }
  return ''
}

export default function ImageBlock({ image, alt = '', borderRadius = 0 }: IImageBlockProps) {
  return (
    <div className="image-block" style={{ textAlign: 'center', margin: '20px 0' }}>
      <div className="container">
        <img
          src={getImageUrl(image)}
          alt={alt}
          style={{
            borderRadius: `${borderRadius}px`,
            maxWidth: '100%',
            height: 'auto',
            objectFit: 'cover',
            boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
          }}
        />
      </div>
    </div>
  )
}

// examples/nuxt3/components/blocks/ImageBlock.vue
<template>
  <div class="image-block">
    <div class="container">
      <img
        :src="imageUrl"
        :alt="alt"
        :style="imageStyle"
        @error="handleImageError"
        @load="handleImageLoad"
      />
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  image: {
    type: [String, Object],
    required: true
  },
  alt: {
    type: String,
    default: ''
  },
  borderRadius: {
    type: Number,
    default: 0
  }
})

// Преобразуем image в URL для img тега
// base64 - всегда строка
// серверное загрузка - объект с обязательным src
const imageUrl = computed(() => {
  if (typeof props.image === 'string') return props.image;
  if (typeof props.image === 'object' && props.image !== null) {
    return props.image.src || '';
  }
  return '';
});

const imageStyle = computed(() => ({
  borderRadius: `${props.borderRadius}px`,
  maxWidth: '100%',
  height: 'auto',
  objectFit: 'cover',
  boxShadow: '0 4px 8px rgba(0,0,0,0.1)'
}))

const handleImageError = () => {
  // Обработка ошибки загрузки изображения
}

const handleImageLoad = () => {
  // Изображение загружено
}
</script>

<style scoped>
.image-block {
  text-align: center;
  margin: 20px 0;
}

.image-block img {
  transition: transform 0.3s ease;
}

.image-block img:hover {
  transform: scale(1.02);
}
</style>
