// src/react/components/ApiSelectField.tsx
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type MouseEvent,
} from 'react';

import type { IApiRequestParams, IApiSelectItem, IFormFieldConfig } from '../../core/types/form';
import type { ApiSelectUseCase } from '../../core/use-cases/ApiSelectUseCase';
import {
  cloneApiSelectStoredValue,
  extractApiSelectItemsFromValue,
  hasApiSelectValue,
  isSameApiSelectModelValue,
  removeApiSelectItemById,
  toApiSelectDropdownValue,
  toApiSelectStoredValue,
} from '../../utils/apiSelectValueHelpers';
import { CSS_CLASSES } from '../../utils/constants';
import {
  CustomDropdown,
  type ICustomDropdownRef,
  type IDropdownOption,
  type TDropdownValue,
} from './CustomDropdown';

interface IApiSelectFieldProps {
  modelValue?: unknown;
  config: IFormFieldConfig;
  validationError?: string;
  apiSelectUseCase: ApiSelectUseCase;
  onChange: (value: unknown) => void;
}

function nextTick(callback: () => void): void {
  queueMicrotask(() => {
    requestAnimationFrame(callback);
  });
}

export function ApiSelectField({
  modelValue,
  config,
  validationError,
  apiSelectUseCase,
  onChange,
}: IApiSelectFieldProps) {
  const dropdownRef = useRef<ICustomDropdownRef>(null);
  const searchInputRef = useRef<HTMLInputElement>(null);
  const debounceTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const knownItemsRef = useRef(new Map<string | number, IApiSelectItem>());
  const previousModelValueRef = useRef<unknown>(modelValue ?? null);

  const [searchQuery, setSearchQuery] = useState('');
  const [items, setItems] = useState<IApiSelectItem[]>([]);
  const [selectedItems, setSelectedItems] = useState<IApiSelectItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [hasMore, setHasMore] = useState(false);

  const apiConfig = config.apiSelectConfig;

  const isRequired = useMemo(
    () => config.rules?.some(rule => rule.type === 'required') ?? false,
    [config.rules]
  );

  const isMultiple = apiConfig?.multiple ?? false;

  const normalizedDropdownValue = useMemo<TDropdownValue>(
    () => toApiSelectDropdownValue(modelValue, isMultiple),
    [modelValue, isMultiple]
  );

  const placeholder = apiConfig?.placeholder ?? 'Начните вводить для поиска...';
  const loadingText = apiConfig?.loadingText ?? 'Загрузка...';
  const noResultsText = apiConfig?.noResultsText ?? 'Ничего не найдено';
  const errorText = apiConfig?.errorText ?? 'Ошибка загрузки данных';
  const debounceMs = apiConfig?.debounceMs ?? 300;
  const minSearchLength = apiConfig?.minSearchLength ?? 0;

  const hasValue = useMemo(() => hasApiSelectValue(modelValue, isMultiple), [modelValue, isMultiple]);

  const resolveItemById = useCallback(
    (id: string | number) =>
      knownItemsRef.current.get(id) ??
      items.find(item => item.id === id) ??
      selectedItems.find(item => item.id === id),
    [items, selectedItems]
  );

  const hydrateSelectedItemsFromValue = useCallback((value: unknown) => {
    const nextSelection = extractApiSelectItemsFromValue(value);

    nextSelection.forEach(item => {
      knownItemsRef.current.set(item.id, item);
    });

    setSelectedItems(previousSelection => {
      if (
        previousSelection.length === nextSelection.length &&
        previousSelection.every(
          (item, index) =>
            item.id === nextSelection[index]?.id && item.name === nextSelection[index]?.name
        )
      ) {
        return previousSelection;
      }

      return nextSelection;
    });
  }, []);

  const syncSearchQueryWithSelection = useCallback(
    (value: unknown) => {
      if (isMultiple) {
        setSearchQuery('');
        return;
      }

      const selectedItem = extractApiSelectItemsFromValue(value)[0];
      setSearchQuery(selectedItem?.name ?? '');
    },
    [isMultiple]
  );

  const fetchData = useCallback(
    async (reset = false, explicitPage?: number) => {
      if (!apiConfig) {
        setError('Конфигурация API не указана');
        return;
      }

      if (searchQuery.length < minSearchLength && searchQuery.length > 0) {
        return;
      }

      const page = reset ? 1 : (explicitPage ?? currentPage);
      if (reset) {
        setCurrentPage(1);
      } else if (explicitPage !== undefined) {
        setCurrentPage(explicitPage);
      }

      const savedSnapshot =
        (!reset && dropdownRef.current?.isOpen
          ? dropdownRef.current?.saveScrollSnapshot()
          : null) ?? null;

      setLoading(true);
      setError(null);

      try {
        const params: IApiRequestParams = {
          search: searchQuery || undefined,
          page,
          limit: apiConfig.limit || 20,
        };

        const response = await apiSelectUseCase.fetchItems(apiConfig, params);

        setItems(currentItems => {
          const nextItems = reset ? response.data : [...currentItems, ...response.data];
          response.data.forEach(item => {
            knownItemsRef.current.set(item.id, item);
          });
          return nextItems;
        });

        hydrateSelectedItemsFromValue(modelValue);
        setHasMore(response.hasMore ?? false);
      } catch (error_: unknown) {
        const message =
          error_ instanceof Error ? error_.message : String(error_ ?? errorText);
        setError(message || errorText);
        setItems([]);
      } finally {
        setLoading(false);

        if (dropdownRef.current?.isOpen) {
          nextTick(() => {
            if (!reset && savedSnapshot) {
              dropdownRef.current?.restoreScrollFromSnapshot(savedSnapshot);
            }
            nextTick(() => {
              dropdownRef.current?.updatePosition();
            });
          });
        }
      }
    },
    [
      apiConfig,
      apiSelectUseCase,
      currentPage,
      errorText,
      hydrateSelectedItemsFromValue,
      minSearchLength,
      modelValue,
      searchQuery,
    ]
  );

  const dropdownOptions = useMemo<IDropdownOption[]>(() => {
    const map = new Map<string | number, IApiSelectItem>();
    items.forEach(item => {
      map.set(item.id, item);
    });
    selectedItems.forEach(item => {
      if (!map.has(item.id)) {
        map.set(item.id, item);
      }
    });

    return Array.from(map.values()).map(item => ({
      value: item.id,
      label: item.name,
    }));
  }, [items, selectedItems]);

  const handleDropdownOpen = useCallback(async () => {
    setIsDropdownOpen(true);

    await new Promise<void>(resolve => nextTick(resolve));
    dropdownRef.current?.updatePosition();

    setCurrentPage(1);
    await fetchData(true);
    await new Promise<void>(resolve => nextTick(resolve));
    dropdownRef.current?.updatePosition();
  }, [fetchData]);

  const handleDropdownClose = useCallback(() => {
    setIsDropdownOpen(false);
    syncSearchQueryWithSelection(modelValue);
  }, [modelValue, syncSearchQueryWithSelection]);

  const onValueUpdate = useCallback(
    (value: TDropdownValue) => {
      const storedValue = toApiSelectStoredValue(value, isMultiple, resolveItemById);
      onChange(storedValue);
      hydrateSelectedItemsFromValue(storedValue);
      syncSearchQueryWithSelection(storedValue);
      previousModelValueRef.current = cloneApiSelectStoredValue(storedValue);
    },
    [
      hydrateSelectedItemsFromValue,
      isMultiple,
      onChange,
      resolveItemById,
      syncSearchQueryWithSelection,
    ]
  );

  const handleClear = useCallback(
    (clear: () => void) => {
      clear();
      void fetchData(true);
    },
    [fetchData]
  );

  const removeItem = useCallback(
    (id: string | number) => {
      if (!isMultiple) {
        return;
      }

      const newValue = removeApiSelectItemById(modelValue, id);
      onChange(newValue);
      hydrateSelectedItemsFromValue(newValue);
      previousModelValueRef.current = cloneApiSelectStoredValue(newValue);
      syncSearchQueryWithSelection(newValue);
    },
    [hydrateSelectedItemsFromValue, isMultiple, modelValue, onChange, syncSearchQueryWithSelection]
  );

  const loadMore = useCallback(
    (event: MouseEvent<HTMLDivElement>) => {
      event.stopPropagation();

      if (loading) {
        return;
      }

      const isFirstLoad = items.length === 0;
      if (isFirstLoad) {
        void fetchData(true).then(() => {
          dropdownRef.current?.updatePosition();
        });
        return;
      }

      if (!hasMore) {
        return;
      }

      void fetchData(false, currentPage + 1).then(() => {
        dropdownRef.current?.updatePosition();
      });
    },
    [currentPage, fetchData, hasMore, items.length, loading]
  );

  const onSearchInput = useCallback(() => {
    if (debounceTimerRef.current) {
      clearTimeout(debounceTimerRef.current);
    }

    debounceTimerRef.current = setTimeout(() => {
      setCurrentPage(1);
      void fetchData(true).then(() => {
        if (!dropdownRef.current?.isOpen) {
          void dropdownRef.current?.open();
        } else {
          dropdownRef.current?.updatePosition();
        }
      });
    }, debounceMs);
  }, [debounceMs, fetchData]);

  const effectivePlaceholder = useCallback(
    (selectedOptions: { label: string }[]) => {
      if (!isMultiple && selectedOptions.length > 0 && !isDropdownOpen) {
        return '';
      }
      return placeholder;
    },
    [isDropdownOpen, isMultiple, placeholder]
  );

  const isDropdownOpenRef = useRef(isDropdownOpen);
  isDropdownOpenRef.current = isDropdownOpen;

  useEffect(() => {
    if (!isSameApiSelectModelValue(previousModelValueRef.current, modelValue, isMultiple)) {
      previousModelValueRef.current = cloneApiSelectStoredValue(modelValue);
    }

    hydrateSelectedItemsFromValue(modelValue);

    if (!isDropdownOpenRef.current) {
      syncSearchQueryWithSelection(modelValue);
    }
  }, [hydrateSelectedItemsFromValue, isMultiple, modelValue, syncSearchQueryWithSelection]);

  useEffect(() => {
    return () => {
      if (debounceTimerRef.current) {
        clearTimeout(debounceTimerRef.current);
      }
    };
  }, []);

  return (
    <div className="bb-api-select">
      {config.label ? (
        <label className={CSS_CLASSES.BB_API_SELECT_LABEL}>
          {config.label}
          {isRequired ? (
            <span className={CSS_CLASSES.BB_API_SELECT_REQUIRED}>*</span>
          ) : null}
        </label>
      ) : null}

      <CustomDropdown
        ref={dropdownRef}
        className="bb-api-select__dropdown-control"
        modelValue={normalizedDropdownValue}
        options={dropdownOptions}
        multiple={isMultiple}
        placeholder={placeholder}
        loading={loading}
        loadingText={loadingText}
        emptyText={noResultsText}
        errorText={error}
        clearable={hasValue}
        invalid={Boolean(validationError)}
        chipDisplayLimit={0}
        onChange={onValueUpdate}
        onOpen={() => {
          void handleDropdownOpen();
        }}
        onClose={handleDropdownClose}
        onScrollBottom={() => {
          // Отключаем автозагрузку при скролле
        }}
        renderTrigger={({ state, actions }) => (
          <div
            className={`${CSS_CLASSES.BB_API_SELECT_SEARCH}${state.isOpen ? ` ${CSS_CLASSES.BB_API_SELECT_SEARCH_OPEN}` : ''}`}
          >
            <input
              ref={searchInputRef}
              type="text"
              className={CSS_CLASSES.BB_API_SELECT_INPUT}
              placeholder={effectivePlaceholder(state.selectedOptions)}
              value={searchQuery}
              onFocus={() => {
                void actions.open();
              }}
              onClick={event => {
                event.stopPropagation();
                void actions.open();
              }}
              onChange={event => {
                setSearchQuery(event.target.value);
                onSearchInput();
              }}
            />

            {loading ? (
              <span className={CSS_CLASSES.BB_API_SELECT_LOADER}>⏳</span>
            ) : hasValue ? (
              <span
                className={CSS_CLASSES.BB_API_SELECT_CLEAR}
                onClick={event => {
                  event.stopPropagation();
                  handleClear(actions.clear);
                }}
              >
                ✕
              </span>
            ) : null}

            <button
              type="button"
              className={`${CSS_CLASSES.BB_API_SELECT_TOGGLE}${state.isOpen ? ` ${CSS_CLASSES.BB_API_SELECT_TOGGLE_OPEN}` : ''}`}
              onClick={event => {
                event.stopPropagation();
                actions.toggle();
              }}
            >
              ▼
            </button>
          </div>
        )}
        afterOptions={
          !error && (hasMore || items.length === 0) ? (
            <div
              className={CSS_CLASSES.BB_API_SELECT_LOAD_MORE}
              onClick={loadMore}
              style={loading ? { opacity: 0.6, pointerEvents: 'none' } : undefined}
            >
              {loading && items.length > 0 ? loadingText : 'Загрузить ещё...'}
            </div>
          ) : null
        }
      />

      {isMultiple && selectedItems.length > 0 ? (
        <div className={CSS_CLASSES.BB_API_SELECT_SELECTED}>
          {selectedItems.map(item => (
            <div key={item.id} className={CSS_CLASSES.BB_API_SELECT_TAG}>
              <span className={CSS_CLASSES.BB_API_SELECT_TAG_NAME}>{item.name}</span>
              <span
                className={CSS_CLASSES.BB_API_SELECT_TAG_REMOVE}
                onClick={() => removeItem(item.id)}
              >
                ✕
              </span>
            </div>
          ))}
        </div>
      ) : null}
    </div>
  );
}

// src/ui/components/ApiSelectField.vue
<template>
  <div class="bb-api-select">
    <label v-if="config.label" class="bb-api-select__label">
      {{ config.label }}
      <span v-if="isRequired" class="bb-api-select__required">*</span>
    </label>

    <CustomDropdown
      ref="dropdownRef"
      class="bb-api-select__dropdown-control"
      :model-value="props.modelValue"
      :options="dropdownOptions"
      :multiple="isMultiple"
      :placeholder="placeholder"
      :loading="loading"
      :loading-text="loadingText"
      :empty-text="noResultsText"
      :error-text="error"
      :clearable="hasValue"
      :invalid="!!validationError"
      :close-on-select="!isMultiple"
      :chip-display-limit="0"
      @open="handleDropdownOpen"
      @close="handleDropdownClose"
      @update:model-value="onValueUpdate"
      @scroll-bottom="handleScrollBottom"
    >
      <template #trigger="{ state, actions }">
        <div class="bb-api-select__search" :class="{ 'bb-api-select__search--open': state.isOpen }">
          <input
            ref="searchInput"
            v-model="searchQuery"
            type="text"
            class="bb-api-select__input"
            :placeholder="effectivePlaceholder(state.selectedOptions)"
            @focus="onSearchFocus(actions.open)"
            @click.stop="onSearchClick(actions.open)"
            @input="onSearchInput"
          />

          <span v-if="loading" class="bb-api-select__loader">⏳</span>
          <span
            v-else-if="hasValue"
            class="bb-api-select__clear"
            @click.stop="() => handleClear(actions.clear)"
          >
            ✕
          </span>

          <button
            type="button"
            class="bb-api-select__toggle"
            :class="{ 'bb-api-select__toggle--open': state.isOpen }"
            @click.stop="actions.toggle"
          >
            ▼
          </button>
        </div>
      </template>

      <template #after-options>
        <div
          v-if="!loading && !error && (hasMore || items.length === 0)"
          class="bb-api-select__load-more"
          @click.stop="loadMore"
        >
          Загрузить ещё...
        </div>
      </template>
    </CustomDropdown>

    <div v-if="isMultiple && selectedItems.length > 0" class="bb-api-select__selected">
      <div v-for="item in selectedItems" :key="item.id" class="bb-api-select__tag">
        <span class="bb-api-select__tag-name">{{ item.name }}</span>
        <span class="bb-api-select__tag-remove" @click="removeItem(item.id)">✕</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { defineAsyncComponent } from 'vue';

import type { IApiRequestParams, IApiSelectItem, IFormFieldConfig } from '../../core/types/form';
import type { ApiSelectUseCase } from '../../core/use-cases/ApiSelectUseCase';

const CustomDropdown = defineAsyncComponent(
  () => import('./CustomDropdown.vue') as unknown as Promise<any>
);

type TDropdownValue = string | number | (string | number)[] | null;
type TCustomDropdownExpose = {
  open: () => void;
  close: () => void;
  toggle: () => void;
  updatePosition: () => void;
  saveScrollPosition: () => number;
  restoreScrollPosition: (scrollTop: number) => void;
  saveScrollSnapshot: () => { top: number; height: number };
  restoreScrollFromSnapshot: (snapshot: { top: number; height: number } | null) => void;
  isOpen: { value: boolean };
};

interface IProps {
  config: IFormFieldConfig;
  modelValue: string | number | (string | number)[] | null;
  validationError?: string;
  apiSelectUseCase: ApiSelectUseCase;
}

const props = defineProps<IProps>();
const emit = defineEmits<{
  (e: 'update:modelValue', value: string | number | (string | number)[] | null): void;
}>();

const searchInput = ref<HTMLInputElement | null>(null);
const dropdownRef = ref<TCustomDropdownExpose | null>(null);

const searchQuery = ref('');
const items = ref<IApiSelectItem[]>([]);
const selectedItems = ref<IApiSelectItem[]>([]);
const loading = ref(false);
const error = ref<string | null>(null);
const isDropdownOpen = ref(false);
const currentPage = ref(1);
const hasMore = ref(false);

let debounceTimer: ReturnType<typeof setTimeout> | null = null;
const knownItems = new Map<string | number, IApiSelectItem>();
const previousModelValue = ref<TDropdownValue>(props.modelValue);

const apiSelectUseCase = props.apiSelectUseCase;

const apiConfig = computed(() => props.config.apiSelectConfig);

const isRequired = computed(() => {
  return props.config.rules?.some(rule => rule.type === 'required') ?? false;
});

const isMultiple = computed(() => apiConfig.value?.multiple ?? false);

const placeholder = computed(() => apiConfig.value?.placeholder ?? 'Начните вводить для поиска...');

const loadingText = computed(() => apiConfig.value?.loadingText ?? 'Загрузка...');

const noResultsText = computed(() => apiConfig.value?.noResultsText ?? 'Ничего не найдено');

const errorText = computed(() => apiConfig.value?.errorText ?? 'Ошибка загрузки данных');

const debounceMs = computed(() => apiConfig.value?.debounceMs ?? 300);

const minSearchLength = computed(() => apiConfig.value?.minSearchLength ?? 0);

const hasValue = computed(() => {
  if (isMultiple.value) {
    return Array.isArray(props.modelValue) && props.modelValue.length > 0;
  }
  return props.modelValue !== null && props.modelValue !== undefined && props.modelValue !== '';
});

const dropdownOptions = computed(() => {
  const map = new Map<string | number, IApiSelectItem>();
  items.value.forEach(item => {
    map.set(item.id, item);
  });
  selectedItems.value.forEach(item => {
    if (!map.has(item.id)) {
      map.set(item.id, item);
    }
  });

  return Array.from(map.values()).map(item => ({
    value: item.id,
    label: item.name,
  }));
});

const updateKnownSelections = (value: string | number | (string | number)[] | null) => {
  const previousSelection = selectedItems.value;

  if (isMultiple.value) {
    const ids = new Set(Array.isArray(value) ? value : []);
    selectedItems.value = Array.from(ids)
      .map(id => knownItems.get(id) ?? previousSelection.find(item => item.id === id))
      .filter(Boolean);
  } else if (!Array.isArray(value) && value !== null && value !== undefined && value !== '') {
    const candidate =
      knownItems.get(value) ?? previousSelection.find(item => item.id === value) ?? null;
    selectedItems.value = candidate ? [candidate] : [];
  } else {
    selectedItems.value = [];
  }
};

const fetchData = async (reset = false) => {
  if (!apiConfig.value) {
    error.value = 'Конфигурация API не указана';
    return;
  }

  if (searchQuery.value.length < minSearchLength.value && searchQuery.value.length > 0) {
    return;
  }

  if (reset) {
    currentPage.value = 1;
  }

  const savedSnapshot =
    (!reset && isDropdownOpen.value ? dropdownRef.value?.saveScrollSnapshot() : null) ?? null;

  loading.value = true;
  error.value = null;

  try {
    const params: IApiRequestParams = {
      search: searchQuery.value || undefined,
      page: currentPage.value,
      limit: apiConfig.value.limit || 20,
    };

    const response = await apiSelectUseCase.fetchItems(apiConfig.value, params);

    items.value = reset ? response.data : [...items.value, ...response.data];
    response.data.forEach(item => {
      knownItems.set(item.id, item);
    });
    updateKnownSelections(props.modelValue);

    hasMore.value = response.hasMore ?? false;
    if (isDropdownOpen.value) {
      await nextTick();
      dropdownRef.value?.updatePosition();
      dropdownRef.value?.restoreScrollFromSnapshot(savedSnapshot);
      await nextTick();
      dropdownRef.value?.updatePosition();
    }
  } catch (error_: any) {
    error.value = error_.message || errorText.value;
    items.value = [];
  } finally {
    loading.value = false;
    if (isDropdownOpen.value) {
      nextTick(() => {
        dropdownRef.value?.updatePosition();
      });
    }
  }
};

const onSearchInput = () => {
  if (debounceTimer) {
    clearTimeout(debounceTimer);
  }
  debounceTimer = setTimeout(() => {
    currentPage.value = 1;
    fetchData(true).then(() => {
      if (!isDropdownOpen.value) {
        dropdownRef.value?.open();
      } else {
        dropdownRef.value?.updatePosition();
      }
    });
  }, debounceMs.value);
};

const syncSearchQueryWithSelection = (value: string | number | (string | number)[] | null) => {
  if (isMultiple.value) {
    searchQuery.value = '';
    return;
  }

  if (value === null || value === undefined || value === '') {
    searchQuery.value = '';
    return;
  }

  const selectedItem =
    selectedItems.value.find(item => item.id === value) ||
    items.value.find(item => item.id === value);

  searchQuery.value = selectedItem?.name ?? '';
};

const handleDropdownOpen = async () => {
  isDropdownOpen.value = true;

  await nextTick();
  dropdownRef.value?.updatePosition();

  // Всегда обновляем первую страницу при открытии
  currentPage.value = 1;
  await fetchData(true);
  await nextTick();
  dropdownRef.value?.updatePosition();
};

const handleDropdownClose = () => {
  isDropdownOpen.value = false;
  syncSearchQueryWithSelection(props.modelValue);
};

const removeItem = (id: string | number) => {
  if (!isMultiple.value) {
    return;
  }

  const currentValue = (props.modelValue as (string | number)[]) || [];
  const newValue = currentValue.filter(itemId => itemId !== id);
  emit('update:modelValue', newValue);
  selectedItems.value = selectedItems.value.filter(item => item.id !== id);
  previousModelValue.value = cloneModelValue(newValue);
  syncSearchQueryWithSelection(newValue);
};

const loadMore = () => {
  if (loading.value) {
    return;
  }
  // Если списка еще нет — стартуем с reset
  const isFirstLoad = items.value.length === 0;
  if (isFirstLoad) {
    currentPage.value = 1;
    fetchData(true).then(() => {
      dropdownRef.value?.updatePosition();
    });
    return;
  }
  if (!hasMore.value) {
    return;
  }
  currentPage.value += 1;
  fetchData(false).then(() => {
    dropdownRef.value?.updatePosition();
  });
};

const handleScrollBottom = () => {
  // Отключаем автозагрузку при скролле
};

const onValueUpdate = (value: TDropdownValue) => {
  emit('update:modelValue', value);
  updateKnownSelections(value);
  syncSearchQueryWithSelection(value);
  previousModelValue.value = cloneModelValue(value);
};

const handleClear = (clear: () => void) => {
  clear();
  fetchData(true);
};

const effectivePlaceholder = (selectedOptions: { label: string }[]) => {
  if (!isMultiple.value && selectedOptions.length > 0 && !isDropdownOpen.value) {
    return '';
  }
  return placeholder.value;
};

const onSearchFocus = (openDropdownSlot: () => Promise<void> | void) => {
  openDropdownSlot();
};

const onSearchClick = (openDropdownSlot: () => Promise<void> | void) => {
  openDropdownSlot();
};

const cloneModelValue = (value: TDropdownValue): TDropdownValue => {
  if (Array.isArray(value)) {
    return [...value];
  }
  return value;
};

const isSameModelValue = (first: TDropdownValue, second: TDropdownValue): boolean => {
  if (Array.isArray(first) && Array.isArray(second)) {
    if (first.length !== second.length) {
      return false;
    }
    return first.every((item, index) => item === second[index]);
  }

  if (!Array.isArray(first) && !Array.isArray(second)) {
    return first === second;
  }

  return false;
};

const syncWithModelValue = (value: TDropdownValue) => {
  updateKnownSelections(value);
  if (!isDropdownOpen.value) {
    syncSearchQueryWithSelection(value);
  }
};

watch<TDropdownValue>(
  () => props.modelValue as TDropdownValue,
  value => {
    if (!isSameModelValue(previousModelValue.value, value)) {
      previousModelValue.value = cloneModelValue(value);
    }
    syncWithModelValue(value);
  },
  { immediate: true }
);

onMounted(async () => {
  await nextTick();

  if (hasValue.value && apiConfig.value) {
    try {
      loading.value = true;
      const response = await apiSelectUseCase.fetchItems(apiConfig.value, {
        limit: apiConfig.value.limit ?? 20,
      });

      if (isMultiple.value) {
        const ids = props.modelValue as (string | number)[];
        selectedItems.value = response.data.filter((item: IApiSelectItem) => ids.includes(item.id));
      } else {
        const selectedItem = response.data.find(
          (item: IApiSelectItem) => item.id === props.modelValue
        );
        if (selectedItem) {
          selectedItems.value = [selectedItem];
          searchQuery.value = selectedItem.name;
        }
      }

      response.data.forEach(item => {
        knownItems.set(item.id, item);
      });
      updateKnownSelections(props.modelValue);
    } catch {
    } finally {
      loading.value = false;
    }

    selectedItems.value.forEach(item => {
      knownItems.set(item.id, item);
    });
  }

  previousModelValue.value = cloneModelValue(props.modelValue);
  syncWithModelValue(props.modelValue);
});

onBeforeUnmount(() => {
  if (debounceTimer) {
    clearTimeout(debounceTimer);
  }
});
</script>
