// src/react/components/ImageUploadField.tsx
import { useEffect, useId, useMemo, useRef, useState } from 'react';

import type { IImageUploadConfig } from '../../core/types/form';
import { CSS_CLASSES } from '../../utils/constants';

interface IImageUploadFieldProps {
  modelValue?: unknown;
  label?: string;
  required?: boolean;
  placeholder?: string;
  error?: string;
  imageUploadConfig?: IImageUploadConfig;
  fieldNamePath?: string;
  dataRepeaterField?: string;
  dataRepeaterIndex?: number | string;
  dataRepeaterItemField?: string;
  onChange: (value: unknown) => void;
}

async function uploadFileToServer(file: File, config: IImageUploadConfig): Promise<unknown> {
  const uploadUrl = config.uploadUrl;
  if (!uploadUrl) {
    throw new Error('uploadUrl не указан в конфигурации');
  }

  const uploadHeaders = config.uploadHeaders || {};
  const fileParamName = config.fileParamName || 'file';

  const formData = new FormData();
  formData.append(fileParamName, file);

  const response = await fetch(uploadUrl, {
    method: 'POST',
    headers: uploadHeaders,
    body: formData,
  });

  if (!response.ok) {
    throw new Error(`Ошибка загрузки: ${response.statusText}`);
  }

  const responseData = await response.json();

  if (config.responseMapper) {
    return config.responseMapper(responseData);
  }

  return responseData;
}

export function ImageUploadField({
  modelValue,
  label = '',
  required = false,
  placeholder = '',
  error = '',
  imageUploadConfig,
  fieldNamePath: fieldNamePathProp,
  dataRepeaterField,
  dataRepeaterIndex,
  dataRepeaterItemField,
  onChange,
}: IImageUploadFieldProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [fileError, setFileError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const inputId = useId();

  const fieldNamePath = useMemo(() => {
    if (fieldNamePathProp) {
      return fieldNamePathProp;
    }

    const parsedIndex =
      dataRepeaterIndex === undefined || dataRepeaterIndex === null
        ? undefined
        : typeof dataRepeaterIndex === 'number'
          ? dataRepeaterIndex
          : Number.parseInt(String(dataRepeaterIndex), 10);

    if (
      dataRepeaterField &&
      parsedIndex !== undefined &&
      !Number.isNaN(parsedIndex) &&
      dataRepeaterItemField
    ) {
      return `${dataRepeaterField}[${parsedIndex}].${dataRepeaterItemField}`;
    }

    return '';
  }, [fieldNamePathProp, dataRepeaterField, dataRepeaterIndex, dataRepeaterItemField]);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) {
      return;
    }

    if (dataRepeaterField) {
      container.dataset.repeaterField = dataRepeaterField;
    } else {
      delete container.dataset.repeaterField;
    }

    if (dataRepeaterIndex !== undefined && dataRepeaterIndex !== null) {
      container.dataset.repeaterIndex = String(dataRepeaterIndex);
    } else {
      delete container.dataset.repeaterIndex;
    }

    if (dataRepeaterItemField) {
      container.dataset.repeaterItemField = dataRepeaterItemField;
    } else {
      delete container.dataset.repeaterItemField;
    }
  }, [dataRepeaterField, dataRepeaterIndex, dataRepeaterItemField]);

  const displayValue = useMemo(() => {
    const value = modelValue;
    if (!value) {
      return '';
    }

    if (typeof value === 'string') {
      return value;
    }

    if (typeof value === 'object' && value !== null && 'src' in value) {
      return String((value as { src?: string }).src || '');
    }

    return '';
  }, [modelValue]);

  const handleFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) {
      return;
    }

    const config = imageUploadConfig || {};
    const maxFileSize = config.maxFileSize || 10 * 1024 * 1024;

    if (!file.type.startsWith('image/')) {
      setFileError('Пожалуйста, выберите файл изображения');
      return;
    }

    if (file.size > maxFileSize) {
      setFileError(`Размер файла не должен превышать ${Math.round(maxFileSize / 1024 / 1024)}MB`);
      return;
    }

    setFileError('');
    setIsLoading(true);

    try {
      if (config.uploadUrl) {
        const uploadedUrl = await uploadFileToServer(file, config);
        onChange(uploadedUrl);
      } else {
        const reader = new FileReader();
        reader.addEventListener('load', loadEvent => {
          const result = loadEvent.target?.result as string;
          onChange(result);
        });
        reader.addEventListener('error', () => {
          setFileError('Ошибка при чтении файла');
        });
        reader.readAsDataURL(file);
      }
    } catch (uploadError) {
      if (uploadError instanceof TypeError && uploadError.message === 'Failed to fetch') {
        setFileError('Не удалось подключиться к серверу загрузки. Проверьте, что API доступен.');
      } else {
        setFileError(
          uploadError instanceof Error ? uploadError.message : 'Ошибка при загрузке файла'
        );
      }
      if (config.onUploadError && uploadError instanceof Error) {
        config.onUploadError(uploadError);
      }
    } finally {
      setIsLoading(false);
    }
  };

  const clearImage = () => {
    onChange('');
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
    setFileError('');
  };

  return (
    <div
      ref={containerRef}
      className={`bb-image-upload-field${error ? ` ${CSS_CLASSES.ERROR}` : ''}`}
      data-field-name={fieldNamePath || undefined}
    >
      {label ? (
        <label htmlFor={inputId} className="bb-image-upload-field__label">
          {label}
          {required ? <span className="bb-image-upload-field__required">*</span> : null}
        </label>
      ) : null}

      {displayValue ? (
        <div className="bb-image-upload-field__preview">
          <img
            src={displayValue}
            alt={label || 'Изображение'}
            className="bb-image-upload-field__preview-img"
          />
          <button
            type="button"
            className="bb-image-upload-field__preview-clear"
            title="Удалить изображение"
            onClick={clearImage}
          >
            ×
          </button>
        </div>
      ) : null}

      <div className="bb-image-upload-field__file">
        <input
          id={inputId}
          ref={fileInputRef}
          type="file"
          accept="image/*"
          className="bb-image-upload-field__file-input"
          onChange={handleFileChange}
        />
        <label
          htmlFor={inputId}
          className={`bb-image-upload-field__file-label${
            isLoading ? ' bb-image-upload-field__file-label--loading' : ''
          }`}
        >
          {isLoading ? (
            <span>⏳ Загрузка...</span>
          ) : (
            <span>{displayValue ? 'Изменить файл' : placeholder || 'Выберите изображение'}</span>
          )}
        </label>
        {fileError ? <span className="bb-image-upload-field__error">{fileError}</span> : null}
      </div>
    </div>
  );
}

// src/ui/components/ImageUploadField.vue
<template>
  <div
    ref="containerRef"
    class="bb-image-upload-field"
    :class="{ [CSS_CLASSES.ERROR]: error }"
    :data-field-name="fieldNamePath"
  >
    <label v-if="label" :for="inputId" class="bb-image-upload-field__label">
      {{ label }}
      <span v-if="required" class="bb-image-upload-field__required">*</span>
    </label>

    <div v-if="displayValue" class="bb-image-upload-field__preview">
      <img
        :src="displayValue"
        :alt="label || 'Изображение'"
        class="bb-image-upload-field__preview-img"
      />
      <button
        type="button"
        class="bb-image-upload-field__preview-clear"
        title="Удалить изображение"
        @click="clearImage"
      >
        ×
      </button>
    </div>

    <div class="bb-image-upload-field__file">
      <input
        :id="inputId"
        ref="fileInputRef"
        type="file"
        accept="image/*"
        class="bb-image-upload-field__file-input"
        @change="handleFileChange"
      />
      <label
        :for="inputId"
        class="bb-image-upload-field__file-label"
        :class="{ 'bb-image-upload-field__file-label--loading': isLoading }"
      >
        <span v-if="isLoading">⏳ Загрузка...</span>
        <span v-else>{{ displayValue ? 'Изменить файл' : 'Выберите изображение' }}</span>
      </label>
      <span v-if="fileError" class="bb-image-upload-field__error">{{ fileError }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue';

import type { IImageUploadConfig } from '../../core/types/form';
import { CSS_CLASSES } from '../../utils/constants';

interface Props {
  modelValue?: any;
  label?: string;
  required?: boolean;
  placeholder?: string;
  error?: string;
  imageUploadConfig?: IImageUploadConfig;
  dataRepeaterField?: string;
  dataRepeaterIndex?: number | string;
  dataRepeaterItemField?: string;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '',
  label: '',
  required: false,
  placeholder: '',
  error: '',
  imageUploadConfig: undefined,
  dataRepeaterField: undefined,
  dataRepeaterIndex: undefined,
  dataRepeaterItemField: undefined,
});

const dataRepeaterField = computed(() => {
  const value = props.dataRepeaterField;
  return typeof value === 'string' ? value : undefined;
});

const dataRepeaterIndex = computed(() => {
  const value = props.dataRepeaterIndex;
  if (value === undefined || value === null) {
    return undefined;
  }
  if (typeof value === 'number') {
    return value;
  }
  const parsed = Number.parseInt(String(value), 10);
  return Number.isNaN(parsed) ? undefined : parsed;
});

const dataRepeaterItemField = computed(() => {
  const value = props.dataRepeaterItemField;
  return typeof value === 'string' ? value : undefined;
});

const fieldNamePath = computed(() => {
  if (
    dataRepeaterField.value &&
    dataRepeaterIndex.value !== undefined &&
    dataRepeaterItemField.value
  ) {
    return `${dataRepeaterField.value}[${dataRepeaterIndex.value}].${dataRepeaterItemField.value}`;
  }
  return '';
});

const emit = defineEmits<{
  'update:modelValue': [value: any];
}>();

const containerRef = ref<HTMLElement | null>(null);
const fileInputRef = ref<HTMLInputElement | null>(null);
const fileError = ref('');
const isLoading = ref(false);
const inputId = computed(() => `image-upload-${Math.random().toString(36).slice(7)}`);

const updateDataAttributes = () => {
  if (!containerRef.value) {
    return;
  }

  const field = dataRepeaterField.value;
  const index = dataRepeaterIndex.value;
  const itemField = dataRepeaterItemField.value;

  if (field) {
    containerRef.value.dataset.repeaterField = field;
  } else {
    delete containerRef.value.dataset.repeaterField;
  }

  if (index !== undefined && index !== null) {
    containerRef.value.dataset.repeaterIndex = String(index);
  } else {
    delete containerRef.value.dataset.repeaterIndex;
  }

  if (itemField) {
    containerRef.value.dataset.repeaterItemField = itemField;
  } else {
    delete containerRef.value.dataset.repeaterItemField;
  }
};

watch(
  [containerRef, dataRepeaterField, dataRepeaterIndex, dataRepeaterItemField],
  () => {
    updateDataAttributes();
  },
  { immediate: true, flush: 'post' }
);

onMounted(() => {
  nextTick(() => {
    updateDataAttributes();
  });
});

const displayValue = computed(() => {
  const value = props.modelValue;
  if (!value) {
    return '';
  }

  if (typeof value === 'string') {
    return value;
  }
  if (typeof value === 'object') {
    return value.src || '';
  }

  return '';
});

const handleFileChange = async (event: Event) => {
  const target = event.target as HTMLInputElement;
  const file = target.files?.[0];

  if (!file) {
    return;
  }

  const config = props.imageUploadConfig || {};
  const _accept = config.accept || 'image/*';
  const maxFileSize = config.maxFileSize || 10 * 1024 * 1024; // 10MB по умолчанию

  if (!file.type.startsWith('image/')) {
    fileError.value = 'Пожалуйста, выберите файл изображения';
    return;
  }

  if (file.size > maxFileSize) {
    fileError.value = `Размер файла не должен превышать ${Math.round(maxFileSize / 1024 / 1024)}MB`;
    return;
  }

  fileError.value = '';
  isLoading.value = true;

  try {
    if (config.uploadUrl) {
      const uploadedUrl = await uploadFileToServer(file, config);
      emit('update:modelValue', uploadedUrl);
    } else {
      const reader = new FileReader();
      reader.addEventListener('load', e => {
        const result = e.target?.result as string;
        emit('update:modelValue', result);
      });
      reader.addEventListener('error', () => {
        fileError.value = 'Ошибка при чтении файла';
      });
      reader.readAsDataURL(file);
    }
  } catch (error) {
    fileError.value = error instanceof Error ? error.message : 'Ошибка при загрузке файла';
    if (config.onUploadError && error instanceof Error) {
      config.onUploadError(error);
    }
  } finally {
    isLoading.value = false;
  }
};

const uploadFileToServer = async (file: File, config: IImageUploadConfig): Promise<any> => {
  const uploadUrl = config.uploadUrl;
  if (!uploadUrl) {
    throw new Error('uploadUrl не указан в конфигурации');
  }
  const uploadHeaders = config.uploadHeaders || {};
  const fileParamName = config.fileParamName || 'file';

  const formData = new FormData();
  formData.append(fileParamName, file);

  const response = await fetch(uploadUrl, {
    method: 'POST',
    headers: uploadHeaders,
    body: formData,
  });

  if (!response.ok) {
    throw new Error(`Ошибка загрузки: ${response.statusText}`);
  }

  const responseData = await response.json();

  if (config.responseMapper) {
    return config.responseMapper(responseData);
  }

  return responseData;
};

const clearImage = () => {
  emit('update:modelValue', '');
  if (fileInputRef.value) {
    fileInputRef.value.value = '';
  }
  fileError.value = '';
};
</script>
