// examples/react/src/components/blocks/TextBlock.tsx
import { useMemo } from 'react'

function resolveUploadUrl(value: unknown): string {
  if (!value) {
    return ''
  }
  if (typeof value === 'string') {
    return value
  }
  if (typeof value === 'object') {
    const record = value as Record<string, unknown>
    return String(record.src || record.url || '')
  }
  return ''
}

function resolveUploadUrls(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.map(resolveUploadUrl).filter(Boolean)
  }
  const single = resolveUploadUrl(value)
  return single ? [single] : []
}

const TOPIC_LABELS: Record<string, string> = {
  dev: 'Разработка',
  design: 'Дизайн',
  marketing: 'Маркетинг',
  analytics: 'Аналитика',
}

interface ITextBlockProps {
  content: string
  fontSize?: number
  color?: string
  textAlign?: React.CSSProperties['textAlign']
  image?: unknown
  images?: unknown[]
  file?: unknown
  files?: unknown[]
  topics?: Array<string | number>
}

export default function TextBlock({
  content,
  fontSize = 16,
  color = '#333333',
  textAlign = 'left',
  image = '',
  images = [],
  file = '',
  files = [],
  topics = [],
}: ITextBlockProps) {
  const imageUrl = resolveUploadUrl(image)
  const imageUrls = resolveUploadUrls(images)
  const fileUrl = resolveUploadUrl(file)
  const fileUrls = resolveUploadUrls(files)
  const topicLabels = useMemo(
    () =>
      (Array.isArray(topics) ? topics : [])
        .map(value => TOPIC_LABELS[String(value)] || String(value))
        .filter(Boolean),
    [topics]
  )

  return (
    <div className="text-block">
      <div
        className="container"
        style={{
          textAlign,
          fontSize: `${fontSize}px`,
          color,
          padding: '10px',
          border: '1px solid #e9ecef',
          borderRadius: '4px',
          background: '#f8f9fa',
        }}
      >
        <p style={{ margin: '0 0 12px' }}>{content}</p>

        {topicLabels.length > 0 ? (
          <div style={{ marginTop: 16, textAlign: 'left' }}>
            <p style={{ margin: '0 0 8px', fontSize: 13, fontWeight: 600, color: '#6c757d' }}>
              Темы (select, multiple)
            </p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
              {topicLabels.map(label => (
                <span
                  key={label}
                  style={{
                    display: 'inline-block',
                    padding: '4px 10px',
                    borderRadius: 999,
                    background: '#e7f1ff',
                    color: '#0b5ed7',
                    fontSize: 13,
                  }}
                >
                  {label}
                </span>
              ))}
            </div>
          </div>
        ) : null}

        {imageUrl ? (
          <div style={{ marginTop: 16, textAlign: 'left' }}>
            <p style={{ margin: '0 0 8px', fontSize: 13, fontWeight: 600, color: '#6c757d' }}>
              Изображение
            </p>
            <img
              src={imageUrl}
              alt=""
              style={{ display: 'block', maxWidth: '100%', height: 'auto', borderRadius: 4 }}
            />
          </div>
        ) : null}

        {imageUrls.length > 0 ? (
          <div style={{ marginTop: 16, textAlign: 'left' }}>
            <p style={{ margin: '0 0 8px', fontSize: 13, fontWeight: 600, color: '#6c757d' }}>
              Изображения
            </p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
              {imageUrls.map((url, index) => (
                <img
                  key={`image-${index}`}
                  src={url}
                  alt=""
                  style={{
                    width: 120,
                    height: 120,
                    objectFit: 'cover',
                    borderRadius: 4,
                  }}
                />
              ))}
            </div>
          </div>
        ) : null}

        {fileUrl ? (
          <div style={{ marginTop: 16, textAlign: 'left' }}>
            <p style={{ margin: '0 0 8px', fontSize: 13, fontWeight: 600, color: '#6c757d' }}>
              Файл
            </p>
            <a
              href={fileUrl}
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: 'var(--bb-color-primary, #0066cc)', fontSize: 14 }}
            >
              Скачать файл
            </a>
          </div>
        ) : null}

        {fileUrls.length > 0 ? (
          <div style={{ marginTop: 16, textAlign: 'left' }}>
            <p style={{ margin: '0 0 8px', fontSize: 13, fontWeight: 600, color: '#6c757d' }}>
              Файлы
            </p>
            <ul style={{ margin: 0, paddingLeft: 18 }}>
              {fileUrls.map((url, index) => (
                <li key={`file-${index}`}>
                  <a
                    href={url}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{ color: 'var(--bb-color-primary, #0066cc)', fontSize: 14 }}
                  >
                    Файл {index + 1}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        ) : null}
      </div>
    </div>
  )
}

// examples/vue3/src/components/TextBlock.vue
<template>
  <div class="text-block">
    <div class="container" :style="blockStyle">
      <p class="text-block__content">{{ content }}</p>

      <div v-if="topicLabels.length" class="text-block__media">
        <p class="text-block__media-label">Темы (select, multiple)</p>
        <div class="text-block__topics">
          <span
            v-for="label in topicLabels"
            :key="label"
            class="text-block__topic"
          >
            {{ label }}
          </span>
        </div>
      </div>

      <div v-if="imageUrl" class="text-block__media">
        <p class="text-block__media-label">Изображение</p>
        <img :src="imageUrl" alt="" class="text-block__image" />
      </div>

      <div v-if="imageUrls.length" class="text-block__media">
        <p class="text-block__media-label">Изображения</p>
        <div class="text-block__gallery">
          <img
            v-for="(url, index) in imageUrls"
            :key="`image-${index}`"
            :src="url"
            alt=""
            class="text-block__image"
          />
        </div>
      </div>

      <div v-if="fileUrl" class="text-block__media">
        <p class="text-block__media-label">Файл</p>
        <a
          :href="fileUrl"
          class="text-block__file-link"
          target="_blank"
          rel="noopener noreferrer"
        >
          Скачать файл
        </a>
      </div>

      <div v-if="fileUrls.length" class="text-block__media">
        <p class="text-block__media-label">Файлы</p>
        <ul class="text-block__file-list">
          <li v-for="(url, index) in fileUrls" :key="`file-${index}`">
            <a
              :href="url"
              class="text-block__file-link"
              target="_blank"
              rel="noopener noreferrer"
            >
              Файл {{ index + 1 }}
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const TOPIC_LABELS = {
  dev: 'Разработка',
  design: 'Дизайн',
  marketing: 'Маркетинг',
  analytics: 'Аналитика'
}

function resolveUploadUrl(value) {
  if (!value) {
    return ''
  }
  if (typeof value === 'string') {
    return value
  }
  if (typeof value === 'object') {
    return value.src || value.url || ''
  }
  return ''
}

function resolveUploadUrls(value) {
  if (Array.isArray(value)) {
    return value.map(resolveUploadUrl).filter(Boolean)
  }
  const single = resolveUploadUrl(value)
  return single ? [single] : []
}

const props = defineProps({
  content: {
    type: String,
    required: true
  },
  fontSize: {
    type: Number,
    default: 16
  },
  color: {
    type: String,
    default: '#333333'
  },
  textAlign: {
    type: String,
    default: 'left'
  },
  image: {
    type: [String, Object],
    default: ''
  },
  images: {
    type: Array,
    default: () => []
  },
  file: {
    type: [String, Object],
    default: ''
  },
  files: {
    type: Array,
    default: () => []
  },
  topics: {
    type: Array,
    default: () => []
  }
})

const blockStyle = computed(() => ({
  textAlign: props.textAlign,
  fontSize: `${props.fontSize}px`,
  color: props.color,
  padding: '10px',
  border: '1px solid #e9ecef',
  borderRadius: '4px',
  background: '#f8f9fa'
}))

const imageUrl = computed(() => resolveUploadUrl(props.image))
const imageUrls = computed(() => resolveUploadUrls(props.images))
const fileUrl = computed(() => resolveUploadUrl(props.file))
const fileUrls = computed(() => resolveUploadUrls(props.files))
const topicLabels = computed(() => {
  if (!Array.isArray(props.topics)) {
    return []
  }

  return props.topics.map(value => TOPIC_LABELS[value] || value).filter(Boolean)
})
</script>

<style scoped>
.text-block {
  transition: all 0.2s ease;
}

.text-block:hover {
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.text-block__content {
  margin: 0 0 12px;
}

.text-block__media {
  margin-top: 16px;
  text-align: left;
}

.text-block__media-label {
  margin: 0 0 8px;
  font-size: 13px;
  font-weight: 600;
  color: #6c757d;
}

.text-block__image {
  display: block;
  max-width: 100%;
  height: auto;
  border-radius: 4px;
}

.text-block__gallery {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.text-block__gallery .text-block__image {
  width: 120px;
  height: 120px;
  object-fit: cover;
}

.text-block__file-list {
  margin: 0;
  padding-left: 18px;
}

.text-block__file-link {
  color: var(--bb-color-primary);
  font-size: 14px;
}

.text-block__topics {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.text-block__topic {
  display: inline-block;
  padding: 4px 10px;
  border-radius: 999px;
  background: #e7f1ff;
  color: #0b5ed7;
  font-size: 13px;
}
</style>
