// src/vue/components/BlockAnchorField.vue
<template>
  <label v-if="showLabel" :for="fieldId" :class="CSS_CLASSES.FORM_LABEL">
    {{ label }}
    <span v-if="required" :class="CSS_CLASSES.REQUIRED">*</span>
  </label>

  <CustomDropdown
    :model-value="selectedBlockValue"
    :options="blockOptions"
    :placeholder="dropdownPlaceholder"
    :clearable="true"
    :invalid="showError"
    @update:model-value="handleBlockSelect"
  />

  <input
    v-if="allowCustomUrl"
    :id="fieldId"
    type="text"
    :class="[CSS_CLASSES.FORM_CONTROL, CSS_CLASSES.BLOCK_ANCHOR_CUSTOM]"
    :value="customUrlValue"
    :placeholder="customUrlPlaceholder"
    @input="handleCustomUrlInput"
  />
</template>

<script setup lang="ts">
import type { IBlockAnchorConfig } from '../../core/types/form';
import { CSS_CLASSES } from '../../utils/constants';
import {
  buildBlockAnchorOptions,
  isBlockAnchorHash,
} from '../../utils/blockAnchorHelpers';
import { computed, inject } from 'vue';

import { BLOCK_ANCHOR_CONTEXT_KEY } from '../composables/blockAnchorContext';
import CustomDropdown from './CustomDropdown.vue';

interface Props {
  fieldId: string;
  modelValue?: string;
  label?: string;
  required?: boolean;
  error?: string;
  showLabel?: boolean;
  blockAnchorConfig?: IBlockAnchorConfig;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '',
  label: '',
  required: false,
  error: '',
  showLabel: true,
  blockAnchorConfig: undefined,
});

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const contextRef = inject(BLOCK_ANCHOR_CONTEXT_KEY);

const anchorContext = computed(() => contextRef?.value ?? { blocks: [], editingBlockId: null, blockTypeLabels: {} });

const allowCustomUrl = computed(() => props.blockAnchorConfig?.allowCustomUrl === true);

const blockOptions = computed(() =>
  buildBlockAnchorOptions(anchorContext.value, props.blockAnchorConfig).map(option => ({
    value: option.value,
    label: option.label,
    disabled: false,
  }))
);

const knownBlockIds = computed(
  () => new Set(anchorContext.value.blocks.map(block => block.id))
);

const selectedBlockValue = computed(() => {
  const value = String(props.modelValue ?? '');
  if (!value || !isBlockAnchorHash(value, knownBlockIds.value)) {
    return null;
  }
  return value;
});

const customUrlValue = computed(() => {
  const value = String(props.modelValue ?? '');
  if (!value || isBlockAnchorHash(value, knownBlockIds.value)) {
    return '';
  }
  return value;
});

const dropdownPlaceholder = computed(
  () => props.blockAnchorConfig?.placeholder || 'Выберите блок на странице'
);

const customUrlPlaceholder = computed(() => 'или введите URL');

const showError = computed(() => Boolean(props.error));

const handleBlockSelect = (value: string | number | (string | number)[] | null) => {
  if (value === null || value === '') {
    emit('update:modelValue', allowCustomUrl.value ? customUrlValue.value : '');
    return;
  }

  emit('update:modelValue', String(value));
};

const handleCustomUrlInput = (event: Event) => {
  const nextValue = (event.target as HTMLInputElement).value;
  emit('update:modelValue', nextValue);
};
</script>

// src/react/components/BlockAnchorField.tsx
import type { IBlockAnchorConfig } from '../../core/types/form';
import { CSS_CLASSES } from '../../utils/constants';
import {
  buildBlockAnchorOptions,
  isBlockAnchorHash,
} from '../../utils/blockAnchorHelpers';
import { useMemo } from 'react';

import { useBlockAnchorContext } from '../context/blockAnchorContext';
import { CustomDropdown } from './CustomDropdown';

interface IBlockAnchorFieldProps {
  fieldId: string;
  modelValue?: string;
  label?: string;
  required?: boolean;
  error?: string;
  showLabel?: boolean;
  blockAnchorConfig?: IBlockAnchorConfig;
  onChange: (value: string) => void;
}

export function BlockAnchorField({
  fieldId,
  modelValue = '',
  label = '',
  required = false,
  error = '',
  showLabel = true,
  blockAnchorConfig,
  onChange,
}: IBlockAnchorFieldProps) {
  const anchorContext = useBlockAnchorContext();
  const allowCustomUrl = blockAnchorConfig?.allowCustomUrl === true;

  const blockOptions = useMemo(
    () =>
      buildBlockAnchorOptions(anchorContext, blockAnchorConfig).map((option: { value: string; label: string }) => ({
        value: option.value,
        label: option.label,
        disabled: false,
      })),
    [anchorContext, blockAnchorConfig]
  );

  const knownBlockIds = useMemo(
    () => new Set(anchorContext.blocks.map(block => block.id)),
    [anchorContext.blocks]
  );

  const value = String(modelValue ?? '');
  const selectedBlockValue = isBlockAnchorHash(value, knownBlockIds) ? value : null;
  const customUrlValue = !value || isBlockAnchorHash(value, knownBlockIds) ? '' : value;

  const dropdownPlaceholder = blockAnchorConfig?.placeholder || 'Выберите блок на странице';

  return (
    <>
      {showLabel ? (
        <label htmlFor={fieldId} className={CSS_CLASSES.FORM_LABEL}>
          {label}
          {required ? <span className={CSS_CLASSES.REQUIRED}>*</span> : null}
        </label>
      ) : null}

      <CustomDropdown
        modelValue={selectedBlockValue}
        options={blockOptions}
        placeholder={dropdownPlaceholder}
        clearable
        invalid={Boolean(error)}
        onChange={nextValue => {
          if (nextValue === null || nextValue === '') {
            onChange(allowCustomUrl ? customUrlValue : '');
            return;
          }
          onChange(String(nextValue));
        }}
      />

      {allowCustomUrl ? (
        <input
          id={fieldId}
          type="text"
          className={`${CSS_CLASSES.FORM_CONTROL} ${CSS_CLASSES.BLOCK_ANCHOR_CUSTOM}`}
          value={customUrlValue}
          placeholder="или введите URL"
          onChange={event => onChange(event.target.value)}
        />
      ) : null}
    </>
  );
}
