// src/ui/components/CustomField.vue
<template>
  <div ref="containerRef" class="custom-field-container"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch, nextTick } from 'vue';
import type { ICustomFieldRendererRegistry } from '../../core/ports/CustomFieldRenderer';

interface Props {
  field: any;
  modelValue?: any;
  formErrors?: Record<string, string[]>;
  customFieldRendererRegistry?: ICustomFieldRendererRegistry;
  isFieldRequired?: (field: any) => boolean;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: undefined,
  formErrors: () => ({}),
  customFieldRendererRegistry: undefined,
  isFieldRequired: () => false
});

const emit = defineEmits<{
  'update:modelValue': [value: any];
}>();

const containerRef = ref<HTMLElement | null>(null);
let rendererInstance: any = null;

const initializeRenderer = async () => {
  if (!containerRef.value || !props.customFieldRendererRegistry) return;

  const renderer = props.customFieldRendererRegistry.get(props.field.customFieldConfig?.rendererId);
  if (!renderer) return;

  if (rendererInstance?.destroy) {
    rendererInstance.destroy();
    rendererInstance = null;
  }

  const context = {
    fieldName: props.field.field,
    label: props.field.label,
    value: props.modelValue || props.field.defaultValue,
    required: props.isFieldRequired(props.field),
    options: props.field.customFieldConfig?.options,
    onChange: (newValue: any) => {
      nextTick(() => {
        emit('update:modelValue', newValue);
      });
    },
    onError: (error: string | null) => {
    }
  };

  try {
    rendererInstance = await renderer.render(containerRef.value, context);
  } catch (error) {
    console.error('Ошибка инициализации кастомного поля:', error);
  }
};

watch(() => props.modelValue, (newValue, oldValue) => {
  if (rendererInstance?.setValue && newValue !== undefined && newValue !== oldValue) {
    try {
      const currentValue = rendererInstance.getValue ? rendererInstance.getValue() : undefined;
      if (currentValue !== newValue) {
        rendererInstance.setValue(newValue);
      }
    } catch (error) {
    }
  }
}, { flush: 'post' }); // Используем post flush, чтобы обновлять после рендера

onMounted(async () => {
  await nextTick();
  await initializeRenderer();
});

onBeforeUnmount(() => {
  if (rendererInstance?.destroy) {
    rendererInstance.destroy();
    rendererInstance = null;
  }
});
</script>

<style scoped>
.custom-field-container {
  width: 100%;
}
</style>

// src/react/components/CustomField.tsx
import { useEffect, useRef, useState } from 'react';

import type { ICustomFieldRendererRegistry } from '../../core/ports/CustomFieldRenderer';
import type { IFormFieldConfig } from '../../core/types/form';
import { CSS_CLASSES } from '../../utils/constants';
import { getFieldError } from '../../utils/formFieldHelpers';

interface ICustomFieldRendererInstance {
  destroy?: () => void;
  setValue?: (value: unknown) => void;
  getValue?: () => unknown;
  setError?: (error: string | null) => void;
}

interface ICustomFieldProps {
  field: IFormFieldConfig;
  modelValue?: unknown;
  formErrors?: Record<string, string[]>;
  customFieldRendererRegistry?: ICustomFieldRendererRegistry;
  isFieldRequired?: (field: IFormFieldConfig) => boolean;
  onChange: (value: unknown) => void;
}

export function CustomField({
  field,
  modelValue,
  formErrors = {},
  customFieldRendererRegistry,
  isFieldRequired,
  onChange,
}: ICustomFieldProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const rendererInstanceRef = useRef<ICustomFieldRendererInstance | null>(null);
  const onChangeRef = useRef(onChange);
  const isFieldRequiredRef = useRef(isFieldRequired);
  const fieldRef = useRef(field);
  const formErrorsRef = useRef(formErrors);
  const [initError, setInitError] = useState<string | null>(null);

  const rendererId = field.customFieldConfig?.rendererId || '';
  const fieldName = field.field;

  useEffect(() => {
    onChangeRef.current = onChange;
  }, [onChange]);

  useEffect(() => {
    isFieldRequiredRef.current = isFieldRequired;
  }, [isFieldRequired]);

  useEffect(() => {
    fieldRef.current = field;
  }, [field]);

  useEffect(() => {
    formErrorsRef.current = formErrors;
  }, [formErrors]);

  useEffect(() => {
    const container = containerRef.current;
    if (!container || !customFieldRendererRegistry || !rendererId) {
      return;
    }

    const renderer = customFieldRendererRegistry.get(rendererId);
    if (!renderer) {
      setInitError(`Рендерер "${rendererId}" не зарегистрирован`);
      return;
    }

    let cancelled = false;
    setInitError(null);

    const initializeRenderer = async () => {
      const currentField = fieldRef.current;
      const fieldError = getFieldError(currentField, formErrorsRef.current);

      const context = {
        fieldName: currentField.field,
        label: currentField.label,
        value: modelValue ?? currentField.defaultValue,
        required: isFieldRequiredRef.current?.(currentField) ?? false,
        options: currentField.customFieldConfig?.options,
        error: fieldError || undefined,
        onChange: (newValue: unknown) => {
          onChangeRef.current(newValue);
        },
        onError: (error: string | null) => {
          setInitError(error);
        },
      };

      try {
        const instance = await renderer.render(container, context);
        if (cancelled) {
          instance?.destroy?.();
          return;
        }

        if (rendererInstanceRef.current?.destroy) {
          rendererInstanceRef.current.destroy();
        }
        rendererInstanceRef.current = instance;
      } catch (error) {
        const message =
          error instanceof Error ? error.message : 'Ошибка инициализации кастомного поля';
        setInitError(message);
        console.error(`[CustomField] ${fieldName}:`, error);
      }
    };

    void initializeRenderer();

    return () => {
      cancelled = true;
      const instance = rendererInstanceRef.current;
      rendererInstanceRef.current = null;
      if (instance?.destroy) {
        queueMicrotask(() => {
          instance.destroy?.();
        });
      }
    };
  }, [fieldName, rendererId, customFieldRendererRegistry]);

  useEffect(() => {
    const instance = rendererInstanceRef.current;
    const fieldError = getFieldError(field, formErrors);
    if (instance?.setError) {
      instance.setError(fieldError || null);
    }
  }, [field, formErrors]);

  useEffect(() => {
    const instance = rendererInstanceRef.current;
    if (instance?.setValue && modelValue !== undefined) {
      try {
        const currentValue = instance.getValue ? instance.getValue() : undefined;
        if (currentValue !== modelValue) {
          instance.setValue(modelValue);
        }
      } catch (error) {
        console.warn(`[CustomField] setValue failed for "${fieldName}":`, error);
      }
    }
  }, [fieldName, modelValue]);

  if (initError) {
    return (
      <div className="custom-field-container">
        <div className={CSS_CLASSES.BB_ERROR_BOX}>❌ {initError}</div>
      </div>
    );
  }

  return <div ref={containerRef} className="custom-field-container" />;
}
