// src/vue/components/ImageUploadField.vue
<template>
  <div
    v-if="isFileVariant"
    ref="containerRef"
    :class="[
      CSS_CLASSES.FILE_UPLOAD_FIELD,
      { [CSS_CLASSES.ERROR]: error },
      isMultiple ? CSS_CLASSES.FILE_UPLOAD_FIELD_MULTIPLE : '',
    ]"
    :data-field-name="fieldNamePath"
    data-upload-variant="file"
    :data-upload-multiple="isMultiple ? 'true' : 'false'"
  >
    <label v-if="label" :for="inputId" :class="CSS_CLASSES.FILE_UPLOAD_FIELD_LABEL">
      {{ label }}
      <span v-if="required" :class="CSS_CLASSES.FILE_UPLOAD_FIELD_REQUIRED">*</span>
    </label>

    <ul v-if="isMultiple && items.length" :class="CSS_CLASSES.FILE_UPLOAD_FIELD_LIST">
      <li
        v-for="(itemUrl, index) in items"
        :key="`${itemUrl}-${index}`"
        :class="CSS_CLASSES.FILE_UPLOAD_FIELD_ROW"
      >
        <span :class="CSS_CLASSES.FILE_UPLOAD_FIELD_BADGE">{{ getExtensionBadge(itemUrl) }}</span>
        <a
          :href="itemUrl"
          target="_blank"
          rel="noopener noreferrer"
          :class="CSS_CLASSES.FILE_UPLOAD_FIELD_NAME"
        >
          {{ getFileName(itemUrl) }}
        </a>
        <button
          type="button"
          :class="CSS_CLASSES.FILE_UPLOAD_FIELD_REMOVE"
          title="Удалить"
          @click="removeItem(index)"
        >
          Удалить
        </button>
      </li>
    </ul>

    <div
      v-else-if="!isMultiple && singleDisplayValue"
      :class="CSS_CLASSES.FILE_UPLOAD_FIELD_ROW"
    >
      <span :class="CSS_CLASSES.FILE_UPLOAD_FIELD_BADGE">
        {{ getExtensionBadge(singleDisplayValue) }}
      </span>
      <a
        :href="singleDisplayValue"
        target="_blank"
        rel="noopener noreferrer"
        :class="CSS_CLASSES.FILE_UPLOAD_FIELD_NAME"
      >
        {{ getFileName(singleDisplayValue) }}
      </a>
      <button
        type="button"
        :class="CSS_CLASSES.FILE_UPLOAD_FIELD_REMOVE"
        title="Удалить файл"
        @click="clearValue"
      >
        Удалить
      </button>
    </div>

    <div :class="CSS_CLASSES.FILE_UPLOAD_FIELD_PICKER">
      <input
        :id="inputId"
        ref="fileInputRef"
        type="file"
        :accept="accept"
        :multiple="isMultiple"
        :class="CSS_CLASSES.FILE_UPLOAD_FIELD_INPUT"
        @change="handleFileChange"
      />
      <label
        v-if="!isMultiple || canAddMore"
        :for="inputId"
        :class="[
          CSS_CLASSES.BTN,
          CSS_CLASSES.BTN_OUTLINE,
          { [CSS_CLASSES.BTN_LOADING]: isLoading },
        ]"
      >
        <template v-if="isLoading">
          <Icon name="loader" :width="14" :height="14" class="bb-icon--spin" />
          Загрузка...
        </template>
        <template v-else-if="isMultiple">+ {{ addButtonLabel }}</template>
        <template v-else>{{ singleDisplayValue ? changeButtonLabel : chooseButtonLabel }}</template>
      </label>
      <span v-if="fileError" :class="CSS_CLASSES.FILE_UPLOAD_FIELD_ERROR">{{ fileError }}</span>
    </div>
  </div>

  <div
    v-else
    ref="containerRef"
    :class="[
      CSS_CLASSES.IMAGE_UPLOAD_FIELD,
      { [CSS_CLASSES.ERROR]: error },
      isMultiple ? CSS_CLASSES.IMAGE_UPLOAD_FIELD_MULTIPLE : '',
    ]"
    :data-field-name="fieldNamePath"
    data-upload-variant="image"
    :data-upload-multiple="isMultiple ? 'true' : 'false'"
  >
    <label v-if="label" :for="inputId" :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_LABEL">
      {{ label }}
      <span v-if="required" :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_REQUIRED">*</span>
    </label>

    <div v-if="isMultiple" :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_GALLERY">
      <div
        v-for="(itemUrl, index) in items"
        :key="`${itemUrl}-${index}`"
        :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_GALLERY_ITEM"
      >
        <img
          :src="itemUrl"
          :alt="label || 'Изображение'"
          :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_PREVIEW_IMG"
        />
        <button
          type="button"
          :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_PREVIEW_CLEAR"
          title="Удалить"
          @click="removeItem(index)"
        >
          <Icon name="close" :width="14" :height="14" />
        </button>
      </div>

      <label
        v-if="canAddMore"
        :for="inputId"
        :class="[
          CSS_CLASSES.IMAGE_UPLOAD_FIELD_GALLERY_ADD,
          { [CSS_CLASSES.IMAGE_UPLOAD_FIELD_FILE_LABEL_LOADING]: isLoading },
        ]"
      >
        <span v-if="isLoading">
          <Icon name="loader" :width="14" :height="14" class="bb-icon--spin" />
          Загрузка...
        </span>
        <span v-else>+ {{ addButtonLabel }}</span>
      </label>
    </div>

    <template v-if="!isMultiple">
      <div v-if="singleDisplayValue" :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_PREVIEW">
        <img
          :src="singleDisplayValue"
          :alt="label || 'Изображение'"
          :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_PREVIEW_IMG"
        />
        <button
          type="button"
          :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_PREVIEW_CLEAR"
          title="Удалить изображение"
          @click="clearValue"
        >
          <Icon name="close" :width="14" :height="14" />
        </button>
      </div>
    </template>

    <div :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_FILE">
      <input
        :id="inputId"
        ref="fileInputRef"
        type="file"
        :accept="accept"
        :multiple="isMultiple"
        :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_FILE_INPUT"
        @change="handleFileChange"
      />
      <label
        v-if="!isMultiple"
        :for="inputId"
        :class="[
          CSS_CLASSES.IMAGE_UPLOAD_FIELD_FILE_LABEL,
          { [CSS_CLASSES.IMAGE_UPLOAD_FIELD_FILE_LABEL_LOADING]: isLoading },
        ]"
      >
        <span v-if="isLoading">
          <Icon name="loader" :width="14" :height="14" class="bb-icon--spin" />
          Загрузка...
        </span>
        <span v-else>{{ singleDisplayValue ? changeButtonLabel : chooseButtonLabel }}</span>
      </label>
      <span v-if="fileError" :class="CSS_CLASSES.IMAGE_UPLOAD_FIELD_ERROR">{{ fileError }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue';

import type { IFileUploadConfig } from '../../core/types/form';
import { CSS_CLASSES } from '../../utils/constants';
import Icon from '../../shared/icons/Icon.vue';
import {
  canAddUploadItems,
  getDefaultAccept,
  getFileExtensionBadge,
  getFileNameFromUrl,
  getMaxUploadCountErrorMessage,
  getUploadUrl,
  normalizeUploadItems,
  partitionFilesForUpload,
  processUploadFile,
  resolveUploadConfig,
  serializeUploadValue,
  type TUploadFieldVariant,
} from '../../utils/uploadFieldUtils';

interface Props {
  modelValue?: unknown;
  label?: string;
  required?: boolean;
  placeholder?: string;
  error?: string;
  variant?: TUploadFieldVariant;
  multiple?: boolean;
  fileUploadConfig?: IFileUploadConfig;
  dataRepeaterField?: string;
  dataRepeaterIndex?: number | string;
  dataRepeaterItemField?: string;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '',
  label: '',
  required: false,
  placeholder: '',
  error: '',
  variant: 'image',
  multiple: false,
  fileUploadConfig: undefined,
  dataRepeaterField: undefined,
  dataRepeaterIndex: undefined,
  dataRepeaterItemField: undefined,
});

const emit = defineEmits<{
  'update:modelValue': [value: unknown];
}>();

const containerRef = ref<HTMLElement | null>(null);
const fileInputRef = ref<HTMLInputElement | null>(null);
const fileError = ref('');
const isLoading = ref(false);
const inputId = computed(
  () => `${props.variant === 'file' ? 'file' : 'image'}-upload-${Math.random().toString(36).slice(7)}`
);

const uploadConfig = computed(() => resolveUploadConfig({ fileUploadConfig: props.fileUploadConfig }));

const isMultiple = computed(() => props.multiple);
const isFileVariant = computed(() => props.variant === 'file');
const accept = computed(() => getDefaultAccept(props.variant, uploadConfig.value));
const items = computed(() => normalizeUploadItems(props.modelValue, isMultiple.value));
const singleDisplayValue = computed(() => items.value[0] || '');
const canAddMore = computed(() => canAddUploadItems(items.value, uploadConfig.value, isMultiple.value));

const chooseButtonLabel = computed(() => {
  if (props.placeholder) {
    return props.placeholder;
  }
  return isFileVariant.value ? 'Выберите файл' : 'Выберите изображение';
});

const changeButtonLabel = computed(() =>
  isFileVariant.value ? 'Заменить файл' : 'Изменить изображение'
);
const addButtonLabel = computed(() => (isFileVariant.value ? 'Добавить файл' : 'Добавить'));

const dataRepeaterField = computed(() => {
  const value = props.dataRepeaterField;
  return typeof value === 'string' ? value : undefined;
});

const dataRepeaterIndex = computed(() => {
  const value = props.dataRepeaterIndex;
  if (value === undefined || value === null) {
    return undefined;
  }
  if (typeof value === 'number') {
    return value;
  }
  const parsed = Number.parseInt(String(value), 10);
  return Number.isNaN(parsed) ? undefined : parsed;
});

const dataRepeaterItemField = computed(() => {
  const value = props.dataRepeaterItemField;
  return typeof value === 'string' ? value : undefined;
});

const fieldNamePath = computed(() => {
  if (
    dataRepeaterField.value &&
    dataRepeaterIndex.value !== undefined &&
    dataRepeaterItemField.value
  ) {
    return `${dataRepeaterField.value}[${dataRepeaterIndex.value}].${dataRepeaterItemField.value}`;
  }
  return '';
});

const updateDataAttributes = () => {
  if (!containerRef.value) {
    return;
  }

  const field = dataRepeaterField.value;
  const index = dataRepeaterIndex.value;
  const itemField = dataRepeaterItemField.value;

  if (field) {
    containerRef.value.dataset.repeaterField = field;
  } else {
    delete containerRef.value.dataset.repeaterField;
  }

  if (index !== undefined && index !== null) {
    containerRef.value.dataset.repeaterIndex = String(index);
  } else {
    delete containerRef.value.dataset.repeaterIndex;
  }

  if (itemField) {
    containerRef.value.dataset.repeaterItemField = itemField;
  } else {
    delete containerRef.value.dataset.repeaterItemField;
  }
};

watch(
  [containerRef, dataRepeaterField, dataRepeaterIndex, dataRepeaterItemField],
  () => {
    updateDataAttributes();
  },
  { immediate: true, flush: 'post' }
);

onMounted(() => {
  nextTick(() => {
    updateDataAttributes();
  });
});

const getFileName = (url: string) => getFileNameFromUrl(url);
const getExtensionBadge = (url: string) => getFileExtensionBadge(url);

const emitValue = (nextItems: string[]) => {
  emit('update:modelValue', serializeUploadValue(nextItems, isMultiple.value));
};

const clearValue = () => {
  emitValue([]);
  if (fileInputRef.value) {
    fileInputRef.value.value = '';
  }
  fileError.value = '';
};

const removeItem = (index: number) => {
  const nextItems = items.value.filter((_, itemIndex) => itemIndex !== index);
  emitValue(nextItems);
};

const handleFileChange = async (event: Event) => {
  const target = event.target as HTMLInputElement;
  const selectedFiles = Array.from(target.files || []);
  if (!selectedFiles.length) {
    return;
  }

  const { filesToUpload, maxCountExceeded, maxCount } = partitionFilesForUpload(
    selectedFiles,
    items.value.length,
    uploadConfig.value,
    isMultiple.value
  );

  if (!filesToUpload.length) {
    if (maxCountExceeded) {
      fileError.value = getMaxUploadCountErrorMessage(maxCount);
    }
    if (fileInputRef.value) {
      fileInputRef.value.value = '';
    }
    return;
  }

  fileError.value = '';
  isLoading.value = true;

  try {
    const uploadedItems: string[] = [];

    for (const file of filesToUpload) {
      const result = await processUploadFile(file, uploadConfig.value, props.variant);
      const url = getUploadUrl(result);
      if (url) {
        uploadedItems.push(url);
      }
    }

    if (!uploadedItems.length) {
      return;
    }

    if (isMultiple.value) {
      emitValue([...items.value, ...uploadedItems]);
    } else {
      emitValue([uploadedItems[0]]);
    }

    if (maxCountExceeded) {
      fileError.value = getMaxUploadCountErrorMessage(maxCount);
    }
  } catch (error) {
    if (error instanceof TypeError && error.message === 'Failed to fetch') {
      fileError.value = 'Не удалось подключиться к серверу загрузки. Проверьте, что API доступен.';
    } else {
      fileError.value = error instanceof Error ? error.message : 'Ошибка при загрузке файла';
    }
    if (uploadConfig.value.onUploadError && error instanceof Error) {
      uploadConfig.value.onUploadError(error);
    }
  } finally {
    isLoading.value = false;
    if (fileInputRef.value) {
      fileInputRef.value.value = '';
    }
  }
};
</script>

// src/react/components/ImageUploadField.tsx
import { useEffect, useId, useMemo, useRef, useState } from 'react';

import type { IFileUploadConfig } from '../../core/types/form';
import { CSS_CLASSES } from '../../utils/constants';
import { Icon } from './icons/Icon';
import {
  canAddUploadItems,
  getDefaultAccept,
  getFileExtensionBadge,
  getFileNameFromUrl,
  getMaxUploadCountErrorMessage,
  getUploadUrl,
  normalizeUploadItems,
  partitionFilesForUpload,
  processUploadFile,
  resolveUploadConfig,
  serializeUploadValue,
  type TUploadFieldVariant,
} from '../../utils/uploadFieldUtils';

interface IImageUploadFieldProps {
  modelValue?: unknown;
  label?: string;
  required?: boolean;
  placeholder?: string;
  error?: string;
  variant?: TUploadFieldVariant;
  multiple?: boolean;
  fileUploadConfig?: IFileUploadConfig;
  fieldNamePath?: string;
  dataRepeaterField?: string;
  dataRepeaterIndex?: number | string;
  dataRepeaterItemField?: string;
  onChange: (value: unknown) => void;
}

export function ImageUploadField({
  modelValue,
  label = '',
  required = false,
  placeholder = '',
  error = '',
  variant = 'image',
  multiple = false,
  fileUploadConfig,
  fieldNamePath: fieldNamePathProp,
  dataRepeaterField,
  dataRepeaterIndex,
  dataRepeaterItemField,
  onChange,
}: IImageUploadFieldProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [fileError, setFileError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const inputId = useId();

  const uploadConfig = useMemo(() => resolveUploadConfig({ fileUploadConfig }), [fileUploadConfig]);

  const isMultiple = multiple;
  const isFileVariant = variant === 'file';
  const accept = getDefaultAccept(variant, uploadConfig);
  const items = useMemo(() => normalizeUploadItems(modelValue, isMultiple), [modelValue, isMultiple]);
  const singleDisplayValue = items[0] || '';
  const canAddMore = canAddUploadItems(items, uploadConfig, isMultiple);

  const chooseButtonLabel = placeholder || (isFileVariant ? 'Выберите файл' : 'Выберите изображение');
  const changeButtonLabel = isFileVariant ? 'Заменить файл' : 'Изменить изображение';
  const addButtonLabel = isFileVariant ? 'Добавить файл' : 'Добавить';

  const fieldNamePath = useMemo(() => {
    if (fieldNamePathProp) {
      return fieldNamePathProp;
    }

    const parsedIndex =
      dataRepeaterIndex === undefined || dataRepeaterIndex === null
        ? undefined
        : typeof dataRepeaterIndex === 'number'
          ? dataRepeaterIndex
          : Number.parseInt(String(dataRepeaterIndex), 10);

    if (
      dataRepeaterField &&
      parsedIndex !== undefined &&
      !Number.isNaN(parsedIndex) &&
      dataRepeaterItemField
    ) {
      return `${dataRepeaterField}[${parsedIndex}].${dataRepeaterItemField}`;
    }

    return '';
  }, [fieldNamePathProp, dataRepeaterField, dataRepeaterIndex, dataRepeaterItemField]);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) {
      return;
    }

    if (dataRepeaterField) {
      container.dataset.repeaterField = dataRepeaterField;
    } else {
      delete container.dataset.repeaterField;
    }

    if (dataRepeaterIndex !== undefined && dataRepeaterIndex !== null) {
      container.dataset.repeaterIndex = String(dataRepeaterIndex);
    } else {
      delete container.dataset.repeaterIndex;
    }

    if (dataRepeaterItemField) {
      container.dataset.repeaterItemField = dataRepeaterItemField;
    } else {
      delete container.dataset.repeaterItemField;
    }
  }, [dataRepeaterField, dataRepeaterIndex, dataRepeaterItemField]);

  const emitValue = (nextItems: string[]) => {
    onChange(serializeUploadValue(nextItems, isMultiple));
  };

  const clearValue = () => {
    emitValue([]);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
    setFileError('');
  };

  const removeItem = (index: number) => {
    emitValue(items.filter((_, itemIndex) => itemIndex !== index));
  };

  const handleFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFiles = Array.from(event.target.files || []);
    if (!selectedFiles.length) {
      return;
    }

    const { filesToUpload, maxCountExceeded, maxCount } = partitionFilesForUpload(
      selectedFiles,
      items.length,
      uploadConfig,
      isMultiple
    );

    if (!filesToUpload.length) {
      if (maxCountExceeded) {
        setFileError(getMaxUploadCountErrorMessage(maxCount));
      }
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
      return;
    }

    setFileError('');
    setIsLoading(true);

    try {
      const uploadedItems: string[] = [];

      for (const file of filesToUpload) {
        const result = await processUploadFile(file, uploadConfig, variant);
        const url = getUploadUrl(result);
        if (url) {
          uploadedItems.push(url);
        }
      }

      if (!uploadedItems.length) {
        return;
      }

      if (isMultiple) {
        emitValue([...items, ...uploadedItems]);
      } else {
        emitValue([uploadedItems[0]]);
      }

      if (maxCountExceeded) {
        setFileError(getMaxUploadCountErrorMessage(maxCount));
      }
    } catch (uploadError) {
      if (uploadError instanceof TypeError && uploadError.message === 'Failed to fetch') {
        setFileError('Не удалось подключиться к серверу загрузки. Проверьте, что API доступен.');
      } else {
        setFileError(
          uploadError instanceof Error ? uploadError.message : 'Ошибка при загрузке файла'
        );
      }
      if (uploadConfig.onUploadError && uploadError instanceof Error) {
        uploadConfig.onUploadError(uploadError);
      }
    } finally {
      setIsLoading(false);
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    }
  };

  if (isFileVariant) {
    return (
      <div
        ref={containerRef}
        className={[
          CSS_CLASSES.FILE_UPLOAD_FIELD,
          error ? CSS_CLASSES.ERROR : '',
          isMultiple ? CSS_CLASSES.FILE_UPLOAD_FIELD_MULTIPLE : '',
        ]
          .filter(Boolean)
          .join(' ')}
        data-field-name={fieldNamePath || undefined}
        data-upload-variant="file"
        data-upload-multiple={isMultiple ? 'true' : 'false'}
      >
        {label ? (
          <label htmlFor={inputId} className={CSS_CLASSES.FILE_UPLOAD_FIELD_LABEL}>
            {label}
            {required ? <span className={CSS_CLASSES.FILE_UPLOAD_FIELD_REQUIRED}>*</span> : null}
          </label>
        ) : null}

        {isMultiple && items.length ? (
          <ul className={CSS_CLASSES.FILE_UPLOAD_FIELD_LIST}>
            {items.map((itemUrl, index) => (
              <li key={`${itemUrl}-${index}`} className={CSS_CLASSES.FILE_UPLOAD_FIELD_ROW}>
                <span className={CSS_CLASSES.FILE_UPLOAD_FIELD_BADGE}>
                  {getFileExtensionBadge(itemUrl)}
                </span>
                <a
                  href={itemUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className={CSS_CLASSES.FILE_UPLOAD_FIELD_NAME}
                >
                  {getFileNameFromUrl(itemUrl)}
                </a>
                <button
                  type="button"
                  className={CSS_CLASSES.FILE_UPLOAD_FIELD_REMOVE}
                  title="Удалить"
                  onClick={() => removeItem(index)}
                >
                  Удалить
                </button>
              </li>
            ))}
          </ul>
        ) : null}

        {!isMultiple && singleDisplayValue ? (
          <div className={CSS_CLASSES.FILE_UPLOAD_FIELD_ROW}>
            <span className={CSS_CLASSES.FILE_UPLOAD_FIELD_BADGE}>
              {getFileExtensionBadge(singleDisplayValue)}
            </span>
            <a
              href={singleDisplayValue}
              target="_blank"
              rel="noopener noreferrer"
              className={CSS_CLASSES.FILE_UPLOAD_FIELD_NAME}
            >
              {getFileNameFromUrl(singleDisplayValue)}
            </a>
            <button
              type="button"
              className={CSS_CLASSES.FILE_UPLOAD_FIELD_REMOVE}
              title="Удалить файл"
              onClick={clearValue}
            >
              Удалить
            </button>
          </div>
        ) : null}

        <div className={CSS_CLASSES.FILE_UPLOAD_FIELD_PICKER}>
          <input
            id={inputId}
            ref={fileInputRef}
            type="file"
            accept={accept}
            multiple={isMultiple}
            className={CSS_CLASSES.FILE_UPLOAD_FIELD_INPUT}
            onChange={handleFileChange}
          />
          {!isMultiple || canAddMore ? (
            <label
              htmlFor={inputId}
              className={[
                CSS_CLASSES.BTN,
                CSS_CLASSES.BTN_OUTLINE,
                isLoading ? CSS_CLASSES.BTN_LOADING : '',
              ]
                .filter(Boolean)
                .join(' ')}
            >
              {isLoading ? (
                <span>
                  <Icon name="loader" width={14} height={14} className="bb-icon--spin" /> Загрузка...
                </span>
              ) : isMultiple ? (
                `+ ${addButtonLabel}`
              ) : singleDisplayValue ? (
                changeButtonLabel
              ) : (
                chooseButtonLabel
              )}
            </label>
          ) : null}
          {fileError ? <span className={CSS_CLASSES.FILE_UPLOAD_FIELD_ERROR}>{fileError}</span> : null}
        </div>
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      className={[
        CSS_CLASSES.IMAGE_UPLOAD_FIELD,
        error ? CSS_CLASSES.ERROR : '',
        isMultiple ? CSS_CLASSES.IMAGE_UPLOAD_FIELD_MULTIPLE : '',
      ]
        .filter(Boolean)
        .join(' ')}
      data-field-name={fieldNamePath || undefined}
      data-upload-variant="image"
      data-upload-multiple={isMultiple ? 'true' : 'false'}
    >
      {label ? (
        <label htmlFor={inputId} className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_LABEL}>
          {label}
          {required ? <span className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_REQUIRED}>*</span> : null}
        </label>
      ) : null}

      {isMultiple ? (
        <div className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_GALLERY}>
          {items.map((itemUrl, index) => (
            <div key={`${itemUrl}-${index}`} className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_GALLERY_ITEM}>
              <img
                src={itemUrl}
                alt={label || 'Изображение'}
                className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_PREVIEW_IMG}
              />
              <button
                type="button"
                className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_PREVIEW_CLEAR}
                title="Удалить"
                onClick={() => removeItem(index)}
              >
                <Icon name="close" width={14} height={14} />
              </button>
            </div>
          ))}

          {canAddMore ? (
            <label
              htmlFor={inputId}
              className={[
                CSS_CLASSES.IMAGE_UPLOAD_FIELD_GALLERY_ADD,
                isLoading ? CSS_CLASSES.IMAGE_UPLOAD_FIELD_FILE_LABEL_LOADING : '',
              ]
                .filter(Boolean)
                .join(' ')}
            >
              {isLoading ? (
                <span>
                  <Icon name="loader" width={14} height={14} className="bb-icon--spin" /> Загрузка...
                </span>
              ) : (
                <span>+ {addButtonLabel}</span>
              )}
            </label>
          ) : null}
        </div>
      ) : null}

      {!isMultiple && singleDisplayValue ? (
        <div className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_PREVIEW}>
          <img
            src={singleDisplayValue}
            alt={label || 'Изображение'}
            className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_PREVIEW_IMG}
          />
          <button
            type="button"
            className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_PREVIEW_CLEAR}
            title="Удалить изображение"
            onClick={clearValue}
          >
            <Icon name="close" width={14} height={14} />
          </button>
        </div>
      ) : null}

      <div className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_FILE}>
        <input
          id={inputId}
          ref={fileInputRef}
          type="file"
          accept={accept}
          multiple={isMultiple}
          className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_FILE_INPUT}
          onChange={handleFileChange}
        />
        {!isMultiple ? (
          <label
            htmlFor={inputId}
            className={[
              CSS_CLASSES.IMAGE_UPLOAD_FIELD_FILE_LABEL,
              isLoading ? CSS_CLASSES.IMAGE_UPLOAD_FIELD_FILE_LABEL_LOADING : '',
            ]
              .filter(Boolean)
              .join(' ')}
          >
            {isLoading ? (
              <span>
                <Icon name="loader" width={14} height={14} className="bb-icon--spin" /> Загрузка...
              </span>
            ) : (
              <span>{singleDisplayValue ? changeButtonLabel : chooseButtonLabel}</span>
            )}
          </label>
        ) : null}
        {fileError ? <span className={CSS_CLASSES.IMAGE_UPLOAD_FIELD_ERROR}>{fileError}</span> : null}
      </div>
    </div>
  );
}
