// src/vue/components/SpacingControl.vue
<template>
  <div :class="CSS_CLASSES.SPACING_CONTROL">
    <div :class="CSS_CLASSES.SPACING_CONTROL_HEADER">
      <label :class="CSS_CLASSES.SPACING_CONTROL_LABEL">
        {{ label }}
        <span v-if="required" :class="CSS_CLASSES.REQUIRED">*</span>
      </label>
    </div>

    <div :class="CSS_CLASSES.SPACING_CONTROL_BREAKPOINTS">
      <button
        v-for="bp in allBreakpoints"
        :key="bp.name"
        type="button"
        :class="[
          CSS_CLASSES.SPACING_CONTROL_BREAKPOINT_BTN,
          { [CSS_CLASSES.SPACING_CONTROL_BREAKPOINT_BTN_ACTIVE]: currentBreakpoint === bp.name },
        ]"
        @click="currentBreakpoint = bp.name"
      >
        {{ bp.label }}
      </button>
    </div>

    <div :class="CSS_CLASSES.SPACING_CONTROL_GROUPS">
      <div
        v-for="spacingType in availableSpacingTypes"
        :key="spacingType"
        :class="CSS_CLASSES.SPACING_CONTROL_GROUP"
      >
        <label :for="getFieldId(spacingType)" :class="CSS_CLASSES.SPACING_CONTROL_GROUP_LABEL">
          {{ getSpacingLabel(spacingType) }}
        </label>

        <div :class="CSS_CLASSES.SPACING_CONTROL_SLIDER_WRAPPER">
          <input
            :id="getFieldId(spacingType)"
            type="range"
            :class="CSS_CLASSES.SPACING_CONTROL_SLIDER"
            :min="minValue"
            :max="maxValue"
            :step="stepValue"
            :value="getSpacingValue(spacingType)"
            @input="handleSpacingChange(spacingType, $event)"
          />
          <input
            type="number"
            :class="CSS_CLASSES.SPACING_CONTROL_VALUE_INPUT"
            :min="minValue"
            :max="maxValue"
            :step="stepValue"
            :value="getSpacingValue(spacingType)"
            @input="handleValueInputChange(spacingType, $event)"
          />
          <span :class="CSS_CLASSES.SPACING_CONTROL_UNIT">px</span>
        </div>
      </div>
    </div>

    <div v-if="showPreview" :class="CSS_CLASSES.SPACING_CONTROL_PREVIEW">
      <div :class="CSS_CLASSES.SPACING_CONTROL_PREVIEW_TITLE">CSS переменные:</div>
      <pre :class="CSS_CLASSES.SPACING_CONTROL_PREVIEW_CODE">{{ getCSSVariablesPreview() }}</pre>
    </div>
  </div>
</template>

<script>
import { computed, onMounted, ref, watch } from 'vue';

import { CSS_CLASSES } from '../../utils/constants';

const DEFAULT_BREAKPOINTS = [
  { name: 'desktop', label: 'Десктоп', maxWidth: undefined },
  { name: 'tablet', label: 'Таблет', maxWidth: 1199 },
  { name: 'mobile', label: 'Моб', maxWidth: 767 },
];

const ALL_SPACING_TYPES = ['padding-top', 'padding-bottom', 'margin-top', 'margin-bottom'];

export default {
  name: 'SpacingControl',
  props: {
    label: {
      type: String,
      default: 'Отступы',
    },

    fieldName: {
      type: String,
      required: true,
    },

    modelValue: {
      type: Object,
      default: () => ({}),
    },

    spacingTypes: {
      type: Array,
      default: () => ALL_SPACING_TYPES,
    },

    min: {
      type: Number,
      default: 0,
    },

    max: {
      type: Number,
      default: 200,
    },

    step: {
      type: Number,
      default: 1,
    },

    breakpoints: {
      type: Array,
      default: null,
    },

    required: {
      type: Boolean,
      default: false,
    },

    showPreview: {
      type: Boolean,
      default: true,
    },
  },

  emits: ['update:modelValue'],
  setup(props, { emit }) {
    const spacingData = ref({});

    const allBreakpoints = computed(() => {
      if (props.breakpoints && props.breakpoints.length > 0) {
        return Array.isArray(props.breakpoints) ? [...props.breakpoints] : props.breakpoints;
      }
      return DEFAULT_BREAKPOINTS;
    });

    const currentBreakpoint = ref('');

    const availableSpacingTypes = computed(() => {
      return props.spacingTypes && props.spacingTypes.length > 0
        ? props.spacingTypes
        : ALL_SPACING_TYPES;
    });

    const minValue = computed(() => props.min);
    const maxValue = computed(() => props.max);
    const stepValue = computed(() => props.step);

    const initializeSpacingData = () => {
      const initialData = {};

      allBreakpoints.value.forEach(bp => {
        initialData[bp.name] = {};
        availableSpacingTypes.value.forEach(spacingType => {
          const existingValue = props.modelValue?.[bp.name]?.[spacingType];
          initialData[bp.name][spacingType] = existingValue !== undefined ? existingValue : 0;
        });
      });

      spacingData.value = initialData;
    };

    const getFieldId = spacingType => {
      return `${props.fieldName}-${spacingType}-${currentBreakpoint.value}`;
    };

    const getSpacingLabel = spacingType => {
      const labels = {
        'padding-top': 'Внутренний верх',
        'padding-bottom': 'Внутренний низ',
        'margin-top': 'Внешний верх',
        'margin-bottom': 'Внешний низ',
      };
      return labels[spacingType] || spacingType;
    };

    const getSpacingValue = spacingType => {
      return spacingData.value?.[currentBreakpoint.value]?.[spacingType] || 0;
    };

    const handleSpacingChange = (spacingType, event) => {
      const value = Number.parseInt(event.target.value, 10);
      updateSpacingValue(spacingType, value);
    };

    const handleValueInputChange = (spacingType, event) => {
      let value = Number.parseInt(event.target.value, 10);

      if (Number.isNaN(value)) {
        value = 0;
      }
      if (value < minValue.value) {
        value = minValue.value;
      }
      if (value > maxValue.value) {
        value = maxValue.value;
      }

      updateSpacingValue(spacingType, value);
    };

    const updateSpacingValue = (spacingType, value) => {
      if (!spacingData.value[currentBreakpoint.value]) {
        spacingData.value[currentBreakpoint.value] = {};
      }

      spacingData.value[currentBreakpoint.value][spacingType] = value;
      emit('update:modelValue', spacingData.value);
    };

    const getCSSVariablesPreview = () => {
      const lines = [];

      allBreakpoints.value.forEach(bp => {
        const bpData = spacingData.value[bp.name] || {};
        const hasValues = Object.values(bpData).some(v => v > 0);

        if (!hasValues) {
          return;
        }

        if (bp.maxWidth) {
          lines.push(`@media (max-width: ${bp.maxWidth}px) {`);
        }

        availableSpacingTypes.value.forEach(spacingType => {
          const value = bpData[spacingType];
          if (value > 0) {
            const varName = `--${props.fieldName}-${spacingType}`;
            const line = bp.maxWidth ? `  ${varName}: ${value}px;` : `${varName}: ${value}px;`;
            lines.push(line);
          }
        });

        if (bp.maxWidth) {
          lines.push('}');
        }
      });

      return lines.join('\n') || '/* Нет заданных отступов */';
    };

    onMounted(() => {
      if (!currentBreakpoint.value && allBreakpoints.value.length > 0) {
        currentBreakpoint.value = allBreakpoints.value[0].name;
      }
      initializeSpacingData();
    });

    watch(
      () => props.modelValue,
      newValue => {
        if (newValue && Object.keys(newValue).length > 0) {
          spacingData.value = { ...newValue };
        }
      },
      { deep: true }
    );

    watch(allBreakpoints, newBreakpoints => {
      const currentExists = newBreakpoints.some(bp => bp.name === currentBreakpoint.value);

      if (!currentExists && newBreakpoints.length > 0) {
        currentBreakpoint.value = newBreakpoints[0].name;
      }
    });

    return {
      CSS_CLASSES,
      currentBreakpoint,
      spacingData,
      allBreakpoints,
      availableSpacingTypes,
      minValue,
      maxValue,
      stepValue,
      getFieldId,
      getSpacingLabel,
      getSpacingValue,
      handleSpacingChange,
      handleValueInputChange,
      getCSSVariablesPreview,
    };
  },
};
</script>

// src/react/components/SpacingControl.tsx
import { CSS_CLASSES } from '../../utils/constants';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import type { ISpacingData } from '../../utils/spacingHelpers';

const DEFAULT_BREAKPOINTS = [
  { name: 'desktop', label: 'Десктоп', maxWidth: undefined as number | undefined },
  { name: 'tablet', label: 'Таблет', maxWidth: 1199 },
  { name: 'mobile', label: 'Моб', maxWidth: 767 },
];

const ALL_SPACING_TYPES = ['padding-top', 'padding-bottom', 'margin-top', 'margin-bottom'];

const SPACING_LABELS: Record<string, string> = {
  'padding-top': 'Внутренний верх',
  'padding-bottom': 'Внутренний низ',
  'margin-top': 'Внешний верх',
  'margin-bottom': 'Внешний низ',
};

interface ISpacingBreakpoint {
  name: string;
  label: string;
  maxWidth?: number;
}

interface ISpacingControlProps {
  modelValue?: ISpacingData;
  label?: string;
  fieldName: string;
  spacingTypes?: string[];
  min?: number;
  max?: number;
  step?: number;
  breakpoints?: ISpacingBreakpoint[] | null;
  required?: boolean;
  showPreview?: boolean;
  onChange: (value: ISpacingData) => void;
}

function buildInitialSpacingData(
  breakpoints: ISpacingBreakpoint[],
  spacingTypes: string[],
  modelValue?: ISpacingData
): ISpacingData {
  const initialData: ISpacingData = {};

  breakpoints.forEach(bp => {
    initialData[bp.name] = {};
    spacingTypes.forEach(spacingType => {
      const existingValue = modelValue?.[bp.name]?.[spacingType];
      initialData[bp.name][spacingType] = existingValue !== undefined ? existingValue : 0;
    });
  });

  return initialData;
}

export function SpacingControl({
  modelValue,
  label = 'Отступы',
  fieldName,
  spacingTypes,
  min = 0,
  max = 200,
  step = 1,
  breakpoints,
  required = false,
  showPreview = true,
  onChange,
}: ISpacingControlProps) {
  const allBreakpoints = useMemo(() => {
    if (breakpoints && breakpoints.length > 0) {
      return [...breakpoints];
    }
    return DEFAULT_BREAKPOINTS;
  }, [breakpoints]);

  const availableSpacingTypes = useMemo(() => {
    return spacingTypes && spacingTypes.length > 0 ? spacingTypes : ALL_SPACING_TYPES;
  }, [spacingTypes]);

  const [currentBreakpoint, setCurrentBreakpoint] = useState(() => allBreakpoints[0]?.name ?? '');
  const [spacingData, setSpacingData] = useState<ISpacingData>(() =>
    buildInitialSpacingData(allBreakpoints, availableSpacingTypes, modelValue)
  );
  const onChangeRef = useRef(onChange);

  useEffect(() => {
    onChangeRef.current = onChange;
  }, [onChange]);

  useEffect(() => {
    if (modelValue && Object.keys(modelValue).length > 0) {
      setSpacingData({ ...modelValue });
    }
  }, [modelValue]);

  useEffect(() => {
    const currentExists = allBreakpoints.some(bp => bp.name === currentBreakpoint);
    if (!currentExists && allBreakpoints.length > 0) {
      setCurrentBreakpoint(allBreakpoints[0].name);
    }
  }, [allBreakpoints, currentBreakpoint]);

  const getFieldId = (spacingType: string) => {
    return `${fieldName}-${spacingType}-${currentBreakpoint}`;
  };

  const getSpacingLabel = (spacingType: string) => {
    return SPACING_LABELS[spacingType] || spacingType;
  };

  const getSpacingValue = (spacingType: string) => {
    return spacingData?.[currentBreakpoint]?.[spacingType] || 0;
  };

  const updateSpacingValue = useCallback(
    (spacingType: string, value: number) => {
      setSpacingData(prev => {
        const next = { ...prev };
        if (!next[currentBreakpoint]) {
          next[currentBreakpoint] = {};
        }
        next[currentBreakpoint] = { ...next[currentBreakpoint], [spacingType]: value };
        queueMicrotask(() => {
          onChangeRef.current(next);
        });
        return next;
      });
    },
    [currentBreakpoint]
  );

  const handleSpacingChange = (spacingType: string, event: React.ChangeEvent<HTMLInputElement>) => {
    const value = Number.parseInt(event.target.value, 10);
    updateSpacingValue(spacingType, value);
  };

  const handleValueInputChange = (spacingType: string, event: React.ChangeEvent<HTMLInputElement>) => {
    let value = Number.parseInt(event.target.value, 10);

    if (Number.isNaN(value)) {
      value = 0;
    }
    if (value < min) {
      value = min;
    }
    if (value > max) {
      value = max;
    }

    updateSpacingValue(spacingType, value);
  };

  const getCSSVariablesPreview = () => {
    const lines: string[] = [];

    allBreakpoints.forEach(bp => {
      const bpData = spacingData[bp.name] || {};
      const hasValues = Object.values(bpData).some(v => (v as number) > 0);

      if (!hasValues) {
        return;
      }

      if (bp.maxWidth) {
        lines.push(`@media (max-width: ${bp.maxWidth}px) {`);
      }

      availableSpacingTypes.forEach(spacingType => {
        const value = bpData[spacingType];
        if ((value as number) > 0) {
          const varName = `--${fieldName}-${spacingType}`;
          const line = bp.maxWidth ? `  ${varName}: ${value}px;` : `${varName}: ${value}px;`;
          lines.push(line);
        }
      });

      if (bp.maxWidth) {
        lines.push('}');
      }
    });

    return lines.join('\n') || '/* Нет заданных отступов */';
  };

  return (
    <div className={CSS_CLASSES.SPACING_CONTROL}>
      <div className={CSS_CLASSES.SPACING_CONTROL_HEADER}>
        <label className={CSS_CLASSES.SPACING_CONTROL_LABEL}>
          {label}
          {required ? <span className={CSS_CLASSES.REQUIRED}>*</span> : null}
        </label>
      </div>

      <div className={CSS_CLASSES.SPACING_CONTROL_BREAKPOINTS}>
        {allBreakpoints.map(bp => (
          <button
            key={bp.name}
            type="button"
            className={[
              CSS_CLASSES.SPACING_CONTROL_BREAKPOINT_BTN,
              currentBreakpoint === bp.name ? CSS_CLASSES.SPACING_CONTROL_BREAKPOINT_BTN_ACTIVE : '',
            ]
              .filter(Boolean)
              .join(' ')}
            onClick={() => setCurrentBreakpoint(bp.name)}
          >
            {bp.label}
          </button>
        ))}
      </div>

      <div className={CSS_CLASSES.SPACING_CONTROL_GROUPS}>
        {availableSpacingTypes.map(spacingType => (
          <div key={spacingType} className={CSS_CLASSES.SPACING_CONTROL_GROUP}>
            <label htmlFor={getFieldId(spacingType)} className={CSS_CLASSES.SPACING_CONTROL_GROUP_LABEL}>
              {getSpacingLabel(spacingType)}
            </label>

            <div className={CSS_CLASSES.SPACING_CONTROL_SLIDER_WRAPPER}>
              <input
                id={getFieldId(spacingType)}
                type="range"
                className={CSS_CLASSES.SPACING_CONTROL_SLIDER}
                min={min}
                max={max}
                step={step}
                value={getSpacingValue(spacingType)}
                onChange={event => handleSpacingChange(spacingType, event)}
              />
              <input
                type="number"
                className={CSS_CLASSES.SPACING_CONTROL_VALUE_INPUT}
                min={min}
                max={max}
                step={step}
                value={getSpacingValue(spacingType)}
                onChange={event => handleValueInputChange(spacingType, event)}
              />
              <span className={CSS_CLASSES.SPACING_CONTROL_UNIT}>px</span>
            </div>
          </div>
        ))}
      </div>

      {showPreview ? (
        <div className={CSS_CLASSES.SPACING_CONTROL_PREVIEW}>
          <div className={CSS_CLASSES.SPACING_CONTROL_PREVIEW_TITLE}>CSS переменные:</div>
          <pre className={CSS_CLASSES.SPACING_CONTROL_PREVIEW_CODE}>{getCSSVariablesPreview()}</pre>
        </div>
      ) : null}
    </div>
  );
}
