// examples/react/src/components/blocks/ImageBlock.tsx
interface IImageBlockProps {
  image: string | { src?: string }
  alt?: string
  borderRadius?: number
}

function getImageUrl(image: IImageBlockProps['image']) {
  if (typeof image === 'string') {
    return image
  }
  if (typeof image === 'object' && image !== null) {
    return image.src || ''
  }
  return ''
}

export default function ImageBlock({ image, alt = '', borderRadius = 0 }: IImageBlockProps) {
  return (
    <div className="image-block" style={{ textAlign: 'center', margin: '20px 0' }}>
      <div className="container">
        <img
          src={getImageUrl(image)}
          alt={alt}
          style={{
            borderRadius: `${borderRadius}px`,
            maxWidth: '100%',
            height: 'auto',
            objectFit: 'cover',
            boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
          }}
        />
      </div>
    </div>
  )
}

// examples/vue3-core-api/src/components/blocks/ImageBlock.vue
<template>
  <div class="image-block">
    <img :src="src" :alt="alt" />
  </div>
</template>

<script setup>
defineProps({
  src: String,
  alt: String
})
</script>

<style scoped>
.image-block {
  text-align: center;
  margin-bottom: 1rem;
}

.image-block img {
  max-width: 100%;
  height: auto;
  border-radius: 4px;
}
</style>
