// src/react/components/form-fields/ColorField.tsx
import { CSS_CLASSES } from '../../../utils/constants';

export interface IColorFieldProps {
  fieldId: string;
  modelValue?: string;
  label?: string;
  required?: boolean;
  error?: string;
  showLabel?: boolean;
  onChange: (value: string) => void;
}

export function ColorField({
  fieldId,
  modelValue = '#333333',
  label = '',
  required = false,
  error = '',
  showLabel = true,
  onChange,
}: IColorFieldProps) {
  const inputClass = error
    ? `${CSS_CLASSES.FORM_CONTROL} ${CSS_CLASSES.ERROR}`
    : CSS_CLASSES.FORM_CONTROL;

  return (
    <>
      {showLabel ? (
        <label htmlFor={fieldId} className={CSS_CLASSES.FORM_LABEL}>
          {label}
          {required ? <span className={CSS_CLASSES.REQUIRED}>*</span> : null}
        </label>
      ) : null}
      <input
        id={fieldId}
        type="color"
        value={modelValue}
        className={inputClass}
        onChange={event => onChange(event.target.value)}
      />
    </>
  );
}

// src/vue/components/form-fields/ColorField.vue
<template>
  <label v-if="showLabel" :for="fieldId" :class="CSS_CLASSES.FORM_LABEL">
    {{ label }}
    <span v-if="required" :class="CSS_CLASSES.REQUIRED">*</span>
  </label>
  <input :id="fieldId" :value="modelValue" type="color" :class="inputClass" @input="handleInput" />
</template>

<script setup lang="ts">
import { computed } from 'vue';

import { CSS_CLASSES } from '../../../utils/constants';

interface Props {
  fieldId: string;
  modelValue?: string;
  label?: string;
  required?: boolean;
  error?: string;
  showLabel?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '#333333',
  label: '',
  required: false,
  error: '',
  showLabel: true,
});

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const inputClass = computed(() => {
  const baseClass = CSS_CLASSES.FORM_CONTROL;
  return props.error ? `${baseClass} ${CSS_CLASSES.ERROR}` : baseClass;
});

const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement;
  emit('update:modelValue', target.value);
};
</script>
