// examples/vue3-theme/src/components/TextBlock.vue
<template>
  <div class="text-block">
    <p class="text-block__content" :style="blockStyle">{{ content }}</p>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  content: {
    type: String,
    required: true,
  },
  fontSize: {
    type: Number,
    default: 16,
  },
  color: {
    type: String,
    default: '#333333',
  },
  textAlign: {
    type: String,
    default: 'left',
  },
})

const blockStyle = computed(() => ({
  textAlign: props.textAlign,
  fontSize: `${props.fontSize}px`,
  color: props.color,
  margin: 0,
  padding: '16px',
}))
</script>

// examples/react/src/components/blocks/TextBlock.tsx
interface ITextBlockProps {
  content: string
  fontSize?: number
  color?: string
  textAlign?: React.CSSProperties['textAlign']
}

export default function TextBlock({
  content,
  fontSize = 16,
  color = '#333333',
  textAlign = 'left',
}: ITextBlockProps) {
  return (
    <div className="text-block">
      <div
        className="container"
        style={{
          textAlign,
          fontSize: `${fontSize}px`,
          color,
          padding: '10px',
          border: '1px solid #e9ecef',
          borderRadius: '4px',
          background: '#f8f9fa',
        }}
      >
        {content}
      </div>
    </div>
  )
}
