// examples/nuxt3/components/blocks/ToggleRepeaterBlock.vue
<template>
  <div class="toggle-repeater-block">
    <div class="container">
      <p class="toggle-repeater-block__hint">
        Regression: enable "Main logos" or "Links" — a repeater should appear inside the toggle-group in the form.
      </p>

      <section v-if="showLogos && logos?.length" class="toggle-repeater-block__section">
        <h3 class="toggle-repeater-block__title">Logos</h3>
        <ul class="toggle-repeater-block__list">
          <li v-for="(item, index) in logos" :key="`logo-${index}`">
            <strong>{{ item.name || `Logo ${index + 1}` }}</strong>
            <span v-if="item.url"> — {{ item.url }}</span>
          </li>
        </ul>
      </section>

      <section v-if="showLinks && links?.length" class="toggle-repeater-block__section">
        <h3 class="toggle-repeater-block__title">Links</h3>
        <ul class="toggle-repeater-block__list">
          <li v-for="(item, index) in links" :key="`link-${index}`">
            <a v-if="item.url" :href="item.url" class="toggle-repeater-block__link">{{ item.name || item.url }}</a>
            <span v-else>{{ item.name || `Link ${index + 1}` }}</span>
          </li>
        </ul>
      </section>
    </div>
  </div>
</template>

<script setup>
defineProps({
  showLogos: {
    type: Boolean,
    default: false,
  },
  logos: {
    type: Array,
    default: () => [],
  },
  showLinks: {
    type: Boolean,
    default: false,
  },
  links: {
    type: Array,
    default: () => [],
  },
})
</script>

<style scoped>
.toggle-repeater-block {
  padding: 16px 0;
}

.toggle-repeater-block__hint {
  margin: 0 0 16px;
  padding: 12px 16px;
  border-radius: 8px;
  background: #fff8e6;
  border: 1px solid #f0d78c;
  color: #6b5a1e;
  font-size: 14px;
  line-height: 1.5;
}

.toggle-repeater-block__section + .toggle-repeater-block__section {
  margin-top: 20px;
}

.toggle-repeater-block__title {
  margin: 0 0 8px;
  font-size: 16px;
}

.toggle-repeater-block__list {
  margin: 0;
  padding-left: 20px;
}

.toggle-repeater-block__link {
  color: var(--bb-color-primary, #0066cc);
  text-decoration: none;
}

.toggle-repeater-block__link:hover {
  text-decoration: underline;
}
</style>

// examples/react/src/components/blocks/ToggleRepeaterBlock.tsx
interface IToggleRepeaterItem {
  name?: string
  url?: string
}

interface IToggleRepeaterBlockProps {
  showLogos?: boolean
  logos?: IToggleRepeaterItem[]
  showLinks?: boolean
  links?: IToggleRepeaterItem[]
}

export default function ToggleRepeaterBlock({
  showLogos = false,
  logos = [],
  showLinks = false,
  links = [],
}: IToggleRepeaterBlockProps) {
  return (
    <div className="toggle-repeater-block" style={{ padding: '16px 0' }}>
      <div className="container">
        <p
          style={{
            margin: '0 0 16px',
            padding: '12px 16px',
            borderRadius: 8,
            background: '#fff8e6',
            border: '1px solid #f0d78c',
            color: '#6b5a1e',
            fontSize: 14,
            lineHeight: 1.5,
          }}
        >
          Regression: включите «Основные логотипы» или «Ссылки» — в форме должен появиться repeater внутри
          toggle-group.
        </p>

        {showLogos && logos.length > 0 ? (
          <section style={{ marginBottom: 20 }}>
            <h3 style={{ margin: '0 0 8px', fontSize: 16 }}>Логотипы</h3>
            <ul style={{ margin: 0, paddingLeft: 20 }}>
              {logos.map((item, index) => (
                <li key={`logo-${index}`}>
                  <strong>{item.name || `Логотип ${index + 1}`}</strong>
                  {item.url ? ` — ${item.url}` : null}
                </li>
              ))}
            </ul>
          </section>
        ) : null}

        {showLinks && links.length > 0 ? (
          <section>
            <h3 style={{ margin: '0 0 8px', fontSize: 16 }}>Ссылки</h3>
            <ul style={{ margin: 0, paddingLeft: 20 }}>
              {links.map((item, index) => (
                <li key={`link-${index}`}>
                  {item.url ? (
                    <a
                      href={item.url}
                      style={{ color: 'var(--bb-color-primary, #0066cc)', textDecoration: 'none' }}
                    >
                      {item.name || item.url}
                    </a>
                  ) : (
                    item.name || `Ссылка ${index + 1}`
                  )}
                </li>
              ))}
            </ul>
          </section>
        ) : null}
      </div>
    </div>
  )
}
